-- ============================================
-- BATCH 4: New Brands (29-75)
-- ============================================
INSERT INTO brands (brand_id, brand_name, brand_slug, country_of_origin, is_active) VALUES
(29, 'Laneige', 'laneige', 'Güney Kore', true),
(30, 'Dr. Jart+', 'dr-jart', 'Güney Kore', true),
(31, 'Etude House', 'etude-house', 'Güney Kore', true),
(32, 'Torriden', 'torriden', 'Güney Kore', true),
(33, 'Round Lab', 'round-lab', 'Güney Kore', true),
(34, 'Axis-Y', 'axis-y', 'Güney Kore', true),
(35, 'Skin1004', 'skin1004', 'Güney Kore', true),
(36, 'Anua', 'anua', 'Güney Kore', true),
(37, 'Medicube', 'medicube', 'Güney Kore', true),
(38, 'Numbuzin', 'numbuzin', 'Güney Kore', true),
(39, 'Heimish', 'heimish', 'Güney Kore', true),
(40, 'By Wishtrend', 'by-wishtrend', 'Güney Kore', true),
(41, 'Benton', 'benton', 'Güney Kore', true),
(42, 'Neogen', 'neogen', 'Güney Kore', true),
(43, 'Holika Holika', 'holika-holika', 'Güney Kore', true),
(44, 'Senka', 'senka', 'Japonya', true),
(45, 'Melano CC', 'melano-cc', 'Japonya', true),
(46, 'Canmake', 'canmake', 'Japonya', true),
(47, 'Biore', 'biore', 'Japonya', true),
(48, 'Muji', 'muji', 'Japonya', true),
(49, 'Kiehl''s', 'kiehls', 'ABD', true),
(50, 'Clinique', 'clinique', 'ABD', true),
(51, 'Estée Lauder', 'estee-lauder', 'ABD', true),
(52, 'Shiseido', 'shiseido', 'Japonya', true),
(53, 'SK-II', 'sk-ii', 'Japonya', true),
(54, 'Dermalogica', 'dermalogica', 'ABD', true),
(55, 'Murad', 'murad', 'ABD', true),
(56, 'Sunday Riley', 'sunday-riley', 'ABD', true),
(57, 'Tatcha', 'tatcha', 'ABD', true),
(58, 'Fresh', 'fresh', 'Fransa', true),
(59, 'Glow Recipe', 'glow-recipe', 'ABD', true),
(60, 'Farmacy', 'farmacy', 'ABD', true),
(61, 'Aveeno', 'aveeno', 'ABD', true),
(62, 'Simple', 'simple', 'İngiltere', true),
(63, 'Sebamed', 'sebamed', 'Almanya', true),
(64, 'Dove', 'dove', 'İngiltere', true),
(65, 'Weleda', 'weleda', 'İsviçre', true),
(66, 'Dr. Hauschka', 'dr-hauschka', 'Almanya', true),
(67, 'Caudalie', 'caudalie', 'Fransa', true),
(68, 'Embryolisse', 'embryolisse', 'Fransa', true),
(69, 'Filorga', 'filorga', 'Fransa', true),
(70, 'Lierac', 'lierac', 'Fransa', true),
(71, 'Noreva', 'noreva', 'Fransa', true),
(72, 'ACM', 'acm', 'Fransa', true),
(73, 'Altruist', 'altruist', 'İngiltere', true),
(74, 'Geek & Gorgeous', 'geek-gorgeous', 'Macaristan', true),
(75, 'Peter Thomas Roth', 'peter-thomas-roth', 'ABD', true);

SELECT setval('brands_brand_id_seq', 75);
