-- BATCH 5: 40 yeni marka
INSERT INTO brands (brand_id, brand_name, brand_slug, country_of_origin, year_founded, website_url, status, created_at, updated_at) VALUES
(76, 'Procsin', 'procsin', 'Türkiye', 2017, 'https://www.procsin.com.tr', 'active', NOW(), NOW()),
(77, 'Dermoskin', 'dermoskin', 'Türkiye', 2000, 'https://www.dermoskin.com.tr', 'active', NOW(), NOW()),
(78, 'Doa', 'doa', 'Türkiye', 2019, 'https://www.doa.com.tr', 'active', NOW(), NOW()),
(79, 'Thalia', 'thalia', 'Türkiye', 2012, 'https://www.thalia.com.tr', 'active', NOW(), NOW()),
(80, 'Incia', 'incia', 'Türkiye', 2015, 'https://www.incia.com.tr', 'active', NOW(), NOW()),
(81, 'Rosense', 'rosense', 'Türkiye', 1954, 'https://www.rosense.com.tr', 'active', NOW(), NOW()),
(82, 'Siveno', 'siveno', 'Türkiye', 2018, 'https://www.siveno.com.tr', 'active', NOW(), NOW()),
(83, 'Bebak', 'bebak', 'Türkiye', 1976, 'https://www.bebak.com.tr', 'active', NOW(), NOW()),
(84, 'Hunca', 'hunca', 'Türkiye', 1989, 'https://www.hunca.com.tr', 'active', NOW(), NOW()),
(85, 'Marjinal', 'marjinal', 'Türkiye', 2020, 'https://www.marjinal.com.tr', 'active', NOW(), NOW()),
(86, 'Mizon', 'mizon', 'Güney Kore', 2000, 'https://www.mizon.co.kr', 'active', NOW(), NOW()),
(87, 'TonyMoly', 'tonymoly', 'Güney Kore', 2006, 'https://www.tonymoly.com', 'active', NOW(), NOW()),
(88, 'Missha', 'missha-kr', 'Güney Kore', 2000, 'https://www.missha.net', 'active', NOW(), NOW()),
(89, 'Cosrx', 'cosrx-kr', 'Güney Kore', 2013, 'https://www.cosrx.com', 'active', NOW(), NOW()),
(90, 'Pyunkang Yul', 'pyunkang-yul', 'Güney Kore', 2010, 'https://www.pyunkangyul.us', 'active', NOW(), NOW()),
(91, 'Illiyoon', 'illiyoon', 'Güney Kore', 2018, 'https://www.illiyoon.com', 'active', NOW(), NOW()),
(92, 'Sulwhasoo', 'sulwhasoo', 'Güney Kore', 1966, 'https://www.sulwhasoo.com', 'active', NOW(), NOW()),
(93, 'Banila Co', 'banila-co', 'Güney Kore', 2006, 'https://www.banilaco.com', 'active', NOW(), NOW()),
(94, 'Peripera', 'peripera', 'Güney Kore', 2005, 'https://www.peripera.com', 'active', NOW(), NOW()),
(95, 'Cerave', 'cerave-tr', 'ABD', 2005, 'https://www.cerave.com', 'active', NOW(), NOW()),
(96, 'Olay', 'olay', 'ABD', 1952, 'https://www.olay.com', 'active', NOW(), NOW()),
(97, 'L''Oreal Paris', 'loreal-paris', 'Fransa', 1909, 'https://www.loreal-paris.com.tr', 'active', NOW(), NOW()),
(98, 'NYX', 'nyx', 'ABD', 1999, 'https://www.nyxcosmetics.com', 'active', NOW(), NOW()),
(99, 'Maybelline', 'maybelline', 'ABD', 1915, 'https://www.maybelline.com.tr', 'active', NOW(), NOW()),
(100, 'Revolution', 'revolution', 'İngiltere', 2014, 'https://www.revolutionbeauty.com', 'active', NOW(), NOW()),
(101, 'Catrice', 'catrice', 'Almanya', 2004, 'https://www.catrice.eu', 'active', NOW(), NOW()),
(102, 'Essence', 'essence', 'Almanya', 2001, 'https://www.essence.eu', 'active', NOW(), NOW()),
(103, 'MAC', 'mac', 'Kanada', 1984, 'https://www.maccosmetics.com.tr', 'active', NOW(), NOW()),
(104, 'Charlotte Tilbury', 'charlotte-tilbury', 'İngiltere', 2013, 'https://www.charlottetilbury.com', 'active', NOW(), NOW()),
(105, 'Rare Beauty', 'rare-beauty', 'ABD', 2020, 'https://www.rarebeauty.com', 'active', NOW(), NOW()),
(106, 'Fenty Beauty', 'fenty-beauty', 'ABD', 2017, 'https://www.fentybeauty.com', 'active', NOW(), NOW()),
(107, 'Bioderma', 'bioderma-tr', 'Fransa', 1970, 'https://www.bioderma.com.tr', 'active', NOW(), NOW()),
(108, 'Rilastil', 'rilastil', 'İtalya', 1972, 'https://www.rilastil.com', 'active', NOW(), NOW()),
(109, 'Isis Pharma', 'isis-pharma', 'Fransa', 1988, 'https://www.isispharma.com', 'active', NOW(), NOW()),
(110, 'Heliocare', 'heliocare', 'İspanya', 1995, 'https://www.heliocare.com', 'active', NOW(), NOW()),
(111, 'SkinCeuticals', 'skinceuticals', 'ABD', 1997, 'https://www.skinceuticals.com', 'active', NOW(), NOW()),
(112, 'Dercos', 'dercos', 'Fransa', 1964, 'https://www.vichy.com.tr', 'active', NOW(), NOW()),
(113, 'The Body Shop', 'the-body-shop', 'İngiltere', 1976, 'https://www.thebodyshop.com.tr', 'active', NOW(), NOW()),
(114, 'Burt''s Bees', 'burts-bees', 'ABD', 1984, 'https://www.burtsbees.com', 'active', NOW(), NOW()),
(115, 'Nuxe', 'nuxe-tr', 'Fransa', 1990, 'https://www.nuxe.com.tr', 'active', NOW(), NOW());