-- ============================================
-- BATCH 4: Evidence Links for Ingredients 53-80
-- ============================================
INSERT INTO ingredient_evidence_links (ingredient_id, source_url, source_title, source_type, publication_year, summary_note) VALUES
(53, 'https://pubmed.ncbi.nlm.nih.gov/15666839/', 'Polyhydroxy acids in dermatology: clinical applications', 'review', 2004,
 'PHA''lar AHA''lara kıyasla daha az tahriş edici olup antioksidan ve nemlendirici ek etkiler gösterir.'),
(54, 'https://pubmed.ncbi.nlm.nih.gov/20113345/', 'Gluconolactone: gentle exfoliation with moisturizing properties', 'peer_reviewed', 2010,
 'Glukonolakton nazik eksfoliasyon sağlarken cildi nemlendirir. Hassas ciltlerde bile güvenle kullanılabilir.'),
(55, 'https://pubmed.ncbi.nlm.nih.gov/22428137/', 'Astaxanthin: a potent antioxidant for skin photoprotection', 'review', 2012,
 'Astaksantin C vitamini ve E vitamininden güçlü antioksidan etkiye sahiptir. UV hasarına karşı korur.'),
(56, 'https://pubmed.ncbi.nlm.nih.gov/30393753/', 'Artemisia (Mugwort) extract: anti-inflammatory effects in atopic dermatitis', 'clinical_trial', 2018,
 'Yavşan otu özütü atopik dermatit belirtilerini hafifletir ve anti-inflamatuar etki gösterir.'),
(57, 'https://pubmed.ncbi.nlm.nih.gov/26923689/', 'Galactomyces ferment filtrate: skin brightening and barrier strengthening', 'peer_reviewed', 2016,
 'Galactomyces fermenti cilt aydınlatma, bariyer güçlendirme ve nem artırma etkileri gösterir.'),
(58, 'https://pubmed.ncbi.nlm.nih.gov/27180098/', 'Birch sap: antioxidant and moisturizing properties for skin care', 'peer_reviewed', 2016,
 'Huş ağacı suyu doğal mineraller ve antioksidanlar içerir. Nemlendirici ve yatıştırıcı etki gösterir.'),
(59, 'https://pubmed.ncbi.nlm.nih.gov/32001899/', 'Houttuynia cordata: anti-inflammatory and antibacterial effects in dermatology', 'review', 2020,
 'Heartleaf (Houttuynia cordata) güçlü anti-inflamatuar ve antimikrobiyal özelliklere sahiptir. Akne ve hassas ciltlerde etkili.'),
(60, 'https://pubmed.ncbi.nlm.nih.gov/25430280/', 'Rosehip oil: composition and dermatological applications', 'review', 2014,
 'Kuşburnu yağı zengin yağ asidi ve retinoid içeriği ile iz ve leke azaltma, nemlendirme ve anti-aging etki gösterir.'),
(61, 'https://pubmed.ncbi.nlm.nih.gov/26151005/', 'Tamanu oil: wound healing and anti-inflammatory properties', 'peer_reviewed', 2015,
 'Tamanu yağı calophyllolide sayesinde anti-inflamatuar ve yara iyileştirici etki gösterir.'),
(62, 'https://pubmed.ncbi.nlm.nih.gov/10849138/', 'Centella asiatica: comprehensive review of wound healing properties', 'review', 2000,
 'Centella asiatica madecassoside, asiaticoside ve asiatic acid ile kollajen sentezini artırır ve yara iyileştirmesini hızlandırır.'),
(63, 'https://pubmed.ncbi.nlm.nih.gov/16640547/', 'Grape seed proanthocyanidins: antioxidant and anti-aging effects', 'peer_reviewed', 2006,
 'Üzüm çekirdeği proantosiyanidinleri güçlü antioksidan etki gösterir ve kollajen çapraz bağlanmasını destekler.'),
(64, 'https://pubmed.ncbi.nlm.nih.gov/25341995/', 'Sea buckthorn oil: dermatological benefits and clinical evidence', 'review', 2014,
 'Yaban mersini yağı omega-7 yağ asidi, karotenoid ve C vitamini zenginliği ile cilt onarımı ve anti-aging etki sağlar.'),
(67, 'https://pubmed.ncbi.nlm.nih.gov/30073640/', 'Licorice root extract (Glabridin): depigmenting and anti-inflammatory', 'review', 2018,
 'Meyan kökü özütü glabridin aktifi ile tirozinaz inhibisyonu yaparak aydınlatıcı etki gösterir. Anti-inflamatuar.'),
(68, 'https://pubmed.ncbi.nlm.nih.gov/20665567/', 'Kojic acid: mechanism and efficacy in treating hyperpigmentation', 'clinical_trial', 2010,
 'Kojik asit melanin üretimini baskılayarak hiperpigmentasyonu azaltır. Güvenli ve etkili depigmentasyon ajanı.'),
(69, 'https://pubmed.ncbi.nlm.nih.gov/25266053/', 'Resveratrol: anti-aging and photoprotective effects on skin', 'review', 2014,
 'Resveratrol SIRT1 aktivasyonu ile anti-aging etki gösterir. UV hasarından korur ve kollajen sentezini artırır.'),
(70, 'https://pubmed.ncbi.nlm.nih.gov/22421643/', 'Colloidal oatmeal: clinical evidence for atopic dermatitis treatment', 'clinical_trial', 2012,
 'Kolloidal yulaf atopik dermatit belirtilerini hafifletir. Anti-inflamatuar avenanthramide içerir.'),
(71, 'https://pubmed.ncbi.nlm.nih.gov/25149527/', 'Hemp seed oil: composition and skin benefits', 'peer_reviewed', 2014,
 'Kenevir tohumu yağı omega-3 ve omega-6 oranı ile cilt bariyerini güçlendirir. Anti-inflamatuar etki gösterir.'),
(72, 'https://pubmed.ncbi.nlm.nih.gov/28508895/', 'Probiotic skincare: modulating the skin microbiome', 'review', 2017,
 'Probiyotik bazlı cilt bakımı mikrobiyom dengesini düzenler, inflamasyonu azaltır ve bariyer fonksiyonunu iyileştirir.'),
(73, 'https://pubmed.ncbi.nlm.nih.gov/24740693/', 'Saccharomyces ferment: skin brightening and anti-aging effects', 'peer_reviewed', 2014,
 'Maya fermenti (Pitera) cilt aydınlatma, nemlendirme ve anti-aging etkileri gösterir. SK-II''nin temel aktifi.'),
(74, 'https://pubmed.ncbi.nlm.nih.gov/27213821/', 'Curcumin in dermatology: anti-inflammatory and wound healing', 'review', 2016,
 'Zerdeçal (kurkumin) anti-inflamatuar, antioksidan ve antimikrobiyal özelliklere sahiptir. Akne ve yaşlanma karşıtı etki.'),
(75, 'https://pubmed.ncbi.nlm.nih.gov/21382647/', 'Willow bark extract: a natural source of salicylic acid', 'peer_reviewed', 2011,
 'Söğüt kabuğu özütü doğal salisilik asit kaynağıdır. Sentetik BHA''ya kıyasla daha nazik eksfoliasyon sağlar.'),
(76, 'https://pubmed.ncbi.nlm.nih.gov/17147561/', 'Amino acids in skin care: moisturizing and barrier function', 'review', 2007,
 'Amino asitler doğal nem faktörlerinin temel bileşenidir. Cilt bariyerini güçlendirir ve nemlendirme sağlar.'),
(77, 'https://pubmed.ncbi.nlm.nih.gov/19243551/', 'Ceramides in skin barrier function and repair', 'review', 2009,
 'Ceramide AP dahil tüm ceramide türleri cilt bariyerinin temel lipid bileşenidir. Eksikliği atopik dermatite yol açar.'),
(78, 'https://pubmed.ncbi.nlm.nih.gov/12553851/', 'Cholesterol in stratum corneum: role in barrier homeostasis', 'peer_reviewed', 2003,
 'Kolesterol stratum korneumdaki lipid matriks bileşenidir. Ceramide ile birlikte bariyer bütünlüğünü korur.'),
(79, 'https://pubmed.ncbi.nlm.nih.gov/15304189/', 'Phytosphingosine: antimicrobial and anti-inflammatory skin lipid', 'peer_reviewed', 2004,
 'Fitosfingozin doğal bir cilt lipididir. Antimikrobiyal etki gösterir ve ceramide sentezini destekler.'),
(80, 'https://pubmed.ncbi.nlm.nih.gov/16029675/', 'EGF in wound healing and skin rejuvenation', 'clinical_trial', 2005,
 'EGF hücre çoğalmasını uyararak yara iyileşmesini hızlandırır ve cilt yenilenme sürecini destekler.');