-- Sprint 5 (#14) — Tartışmalı içerikler için safety narrative seed
-- Migration 027 öncesinde uygulanmamalı (safety_narrative + controversy_summary kolonları gerekli).
--
-- Idempotent: WHERE ingredient_slug = '...' + COALESCE pattern.
-- Yalnız DB'de olan ingredient'ları günceller; yoksa sessizce atlar.
--
-- Kullanım:
--   1. Önce migration: pnpm typeorm migration:run
--   2. Seed: pnpm ts-node apps/api/src/scripts/run-sql-file.ts \
--           apps/api/src/database/seeds/ingredient-safety-narrative-seed.sql

-- ============ 1. PHENOXYETHANOL ============
UPDATE ingredients SET
  controversy_summary = 'Paraben alternatifi geniş spektrumlu koruyucu. EU ve FDA onaylı (max %1), bebek ürünlerinde tartışmalı.',
  safety_narrative = E'## Neden tartışmalı?\n\nPhenoxyethanol, kozmetiklerde paraben alternatifi olarak yaygın kullanılan bir glycol ether. EU regülasyonu max %1 konsantrasyonda izin veriyor; bu eşik altında SCCS güvenli kabul ediyor (SCCS/1575/16).\n\n## Asıl endişe noktası\n\n**ANSM (Fransa Sağlık Otoritesi)** 2012\\''de **3 yaş altı bebek wipes\\''larında %0.4 üst limit** önerdi (regülasyon değil, tavsiye). Endişe: bebek karaciğeri konjugasyon kapasitesi düşük, sistemik birikim riski.\n\nFDA güvenli kabul ediyor; Avrupa Pediatri Akademisi de 6 ay+ bebek için problemsiz bulmaktadır.\n\n## Yetişkin için\n\nNormal cilt için risk yok. Çok hassas ciltlerde kontakt dermatit (allerjen prevalansı %0.4). Kanıt seviyesi düşük.\n\n## Kaynaklar\n\n- SCCS Opinion 1575/16 (2016)\n- ANSM Avis 2012\n- FDA Status: GRAS (Generally Recognized As Safe)'
WHERE ingredient_slug = 'phenoxyethanol';

-- ============ 2. PARFUM / FRAGRANCE ============
UPDATE ingredients SET
  controversy_summary = '"Parfum" tek bir madde değil, 100+ bileşik karışımı. Alerjen riski; AB 26 alerjen parfümünü ayrıca etiketlemeyi zorunlu kılıyor.',
  safety_narrative = E'## Neden tartışmalı?\n\n"Parfum" veya "Fragrance" bir ingredient değil, **2000+ olası bileşik** içerebilen bir karışım. AB Regülasyon 1223/2009 ticari sır gereği marka, kompozisyonu açıklamak zorunda değil.\n\n## Bilinen risk\n\n**Kontakt dermatit:** AB Cilt Hastalıkları İzleme Sistemi\\''nde topikal tepkilerin **%18\\''i parfüm bileşenlerine bağlı**. En yaygın 26 alerjen ayrı etiketlemeli (>%0.001 leave-on, >%0.01 yıkanan):\n\n- Limonene, Linalool — citrus, lavanta\n- Citronellol, Geraniol — gül\n- Cinnamyl Alcohol, Eugenol — tarçın, karanfil\n- Hexyl Cinnamal, Lyral, Lilial (yasaklı 2022)\n- Benzyl Salicylate, Benzyl Alcohol\n- Coumarin, Farnesol\n- Hydroxycitronellal, Anise Alcohol\n\n## Hassas cilt için\n\n"Fragrance-free" iddiası **Türkiye yasal tanımlı değil**. Kontrol için:\n- INCI sonunda Parfum / Fragrance ara\n- "Doğal parfüm" da alerjenik (citrus uçucu yağları en yüksek)\n- "Hipoalerjenik" pazarlama terimi, garanti değil\n\n## Yıkama ürünlerinde\n\n3-5 dk derice maruziyet, leave-on\\''dan 100x daha düşük risk. Şampuan, jel temizleyici parfümü dermatologlar tarafından genelde tolere edilir kabul ediliyor.\n\n## Kanıt\n\n- SCCS Opinion 1459/11 (alerjen listesi)\n- AAD (American Academy of Dermatology) 2020 Statement on Fragrance Allergy'
WHERE ingredient_slug = 'parfum';

-- ============ 3. CYCLOPENTASILOXANE (D5) ============
UPDATE ingredients SET
  controversy_summary = 'D5 silikon. AB rinse-off (yıkanan) ürünlerde %0.1 üst limit (2020). Endokrin/biyobirikim endişeleri; leave-on güvenli kabul ediliyor.',
  safety_narrative = E'## Neden tartışmalı?\n\nCyclopentasiloxane (siklik silikon, kısaca **D5**) saç, makyaj ve cilt ürünlerinde "ipeksi" doku için kullanılır. 2018 sonrası AB regülasyon değişiklikleri var.\n\n## Düzenleme tarihçesi\n\n- **EU 2018:** SCCS D5\\''i topikal güvenli kabul etti (SCCS/1549/15)\n- **EU 2020:** REACH altında **rinse-off ürünlerde %0.1 üst limit**, leave-on hala serbest\n- **Kanada:** "Toksik madde" listesinde 2008\\''den beri (su yaşamı için)\n- **Norveç:** ek üretim sınırlamaları\n\n## Endişe nedenleri\n\n1. **Çevresel persistans** — D5 suda + toprakta yavaş bozulur, biyobirikim potansiyeli\n2. **Hayvan modelinde endokrin bozucu sinyalleri** (ratlarda yüksek doz oral)\n3. **Solunum yolu emilim** — sprey formlarında inhale edilirse sistemik\n\n## Cilt güvenliği\n\nTopikal kullanımda **sistemik emilim çok düşük** (%1 altı). Cilt iritasyonu nadir. Hassas cilt için bile genelde tolere edilir.\n\n## Pratik tavsiye\n\n- Yıkanan ürünlerde (şampuan, duş jeli) tercihen yok veya düşük\n- Leave-on (yüz kremi, primer) → sınırlı endişe, ama D5 alternatifleri (squalane, dimethicone, ester yağları) genelde mevcut\n- Sprey formlardan (saç sprey, deodorant sprey) ekstra dikkat\n\n## Kaynaklar\n\n- SCCS Opinion 1549/15 (2015)\n- ECHA SVHC Candidate List 2018\n- Health Canada Risk Assessment 2008'
WHERE ingredient_slug = 'cyclopentasiloxane';

-- ============ 4. OXYBENZONE (BENZOPHENONE-3) ============
UPDATE ingredients SET
  controversy_summary = 'Geniş spektrum UV filtresi. EU 2024''te %6''dan %2.2''ye (yüz) düşürüldü. Endokrin + plazma emilimi + mercan toksisitesi endişeleri.',
  safety_narrative = E'## Neden tartışmalı?\n\nOxybenzone (Benzophenone-3, BP-3), 1980\\''lerden beri güneş kremlerinde **UVA + UVB filtresi**. 2020 sonrası ciddi regülasyon kısıtlamaları.\n\n## 4 ana endişe\n\n### 1. Sistemik emilim (FDA 2020)\nFDA RCT çalışmasında, normal SPF kullanımıyla **plazma seviyesi 188.6 ng/mL** ölçüldü — FDA güvenli eşiği 0.5 ng/mL\\''yi 376 kat aştı. Sağlık etkisi araştırılıyor.\n\n### 2. Endokrin sinyaller\nHayvan + in vitro çalışmalarda zayıf östrojenik aktivite. İnsanda anti-androjenik sinyaller (testosteron seviyelerinde değişim — net değil).\n\n### 3. Mercan resifi toksisitesi\n2008-2018 dönemi araştırmalar oxybenzone\\''un **mercan beyazlaşmasına ve larva DNA hasarına** katkı gösterdi. Hawaii (2018), Palau, ABD Virgin Islands oxybenzone içeren güneş kremlerini yasakladı.\n\n### 4. Kontakt fotoallerjisi\nDermatolog kayıtlarında en yaygın güneş kremi alerjenlerinden biri.\n\n## Regülasyon güncel durum\n\n- **EU 2024:** Yüze sürülenlerde %2.2 max, sprey formlarda %6 max (önceki: %6 her şeyde)\n- **ABD FDA:** Hala max %6 (regülasyon güncel değil, eskiden 1999)\n- **Hawaii, Palau, US Virgin Islands, Aruba, Bonaire, Mexico (Cozumel):** yasak\n\n## Daha güvenli alternatifler\n\n- **Tinosorb S, Tinosorb M** — modern AB filtreleri, endokrin endişesi yok\n- **Mineral (Zinc Oxide):** geniş spektrum, sistemik emilim yok\n- **Mexoryl SX/XL** — L\\''Oreal patentli, çok stabil\n\n## Pratik\n\nGüneş kremi alırken etiketinde Oxybenzone / Benzophenone-3 varsa **kaçın**. Modern AB ürünleri (özellikle Avrupa\\''dan ithal) zaten alternatif filtrelerle formüle edilmiş.\n\n## Kaynaklar\n\n- FDA Matta et al., JAMA 2020 (plasma absorption)\n- SCCS Opinion 1644/22\n- Downs et al., Archives Environ Contam Toxicol 2016 (mercan)'
WHERE ingredient_slug = 'oxybenzone';

-- ============ 5. RETINOL (HAMİLELİK) ============
UPDATE ingredients SET
  controversy_summary = 'Anti-aging altın standardı. Hamilelik ve emzirmede kontraendike (yüksek doz oral A vitamini teratojenik). Topikal düşük doz tartışmalı ama "kaçın" önerisi standart.',
  safety_narrative = E'## Hangi durum tartışmalı?\n\nRetinol, A vitamininin (retinyl) topikal türevi. Cilt için **kanıt seviyesi sistematik derleme** — kırışıklık, leke, akne, genel cilt kalitesinde altın standart aktif. Tartışma **kullanım koşulları** etrafında.\n\n## 1. Hamilelik + Emzirme\n\n**Yüksek doz oral A vitamini** (özellikle izotretinoin/Roaccutane) teratojenik — fetüste cidd malformasyonlar yaratabilir.\n\n**Topikal retinolün sistemik emilimi düşük** (%1-5 plazma) — risk büyük olasılıkla yok. Ama:\n- Doğrudan teratojenite çalışması yok (etik sorun)\n- "Sıfır risk yaklaşımı" tercih ediliyor\n- FDA, SCCS, AAD, Türk Dermatoloji Derneği: **hamilelik + emzirme süresince yasak öneri**\n\n**Alternatif:** Bakuchiol (bitkisel "retinol benzeri" aktif). 2018 BJD çalışmasında retinol ile karşılaştırılabilir etkinlik gösterdi, hamilelik için güvenli kabul.\n\n## 2. Aşırı kullanım — "Retinol uçurumu"\n\nGünlük yüksek doz (%1+) retinol veya tretinoin başlangıçta:\n- Kuru, pullanan cilt\n- Yanma, kızarıklık\n- "Purging" — geçici akne artışı\n- Bariyer hasarı\n- UV hassasiyet (sunburn riski)\n\n**Çözüm:** 8 haftalık rampa planı, sandwich tekniği (bkz. Rehber: "İlk Kez Retinol Kullananlar").\n\n## 3. Güneş hassasiyeti\n\nRetinol fotodegrade olur (ışıkta bozulur) ve cildi UV\\''ye hassaslaştırır. Kurallar:\n- **Sadece akşam** kullan\n- **Sabah SPF 30+ zorunlu** (atlama)\n- Tatil/güneşli ortamda 1 hafta önce ara ver\n\n## 4. Birlikte kullanım\n\nKaçın (aynı akşam): AHA, BHA, Benzoyl Peroxide, yüksek doz Vitamin C. Tahriş katlanır.\n\nGüvenli (sinerjik): Niasinamid, Ceramide, Hyaluronik Asit, Peptit.\n\n## Doz rehberi\n\n- **Başlangıç:** %0.3 retinol veya %0.025 tretinoin\n- **Standart:** %0.5 retinol\n- **Uzman:** %1 retinol veya %0.05-0.1 tretinoin\n\nDaha yüksek doz daha hızlı sonuç değil — tahriş riski artar.\n\n## Kaynaklar\n\n- Mukherjee et al., Clin Interv Aging 2006 (kırışıklık RCT)\n- Loss et al., Br J Dermatol 2018 (bakuchiol comparison)\n- ACOG Committee Opinion (hamilelik tavsiyesi)'
WHERE ingredient_slug = 'retinol';

-- ============ 6. SALICYLIC ACID (HAMİLELİK + DOZ) ============
UPDATE ingredients SET
  controversy_summary = 'BHA (yağda çözünür eksfoliyan). %2 OTC güvenli; %20+ kabuk tedavi ofiste. Hamilelikte düşük doz topikal kabul ediliyor, yüksek doz/oral kaçın.',
  safety_narrative = E'## Tartışmanın ana hatları\n\nSalicylic Acid (SA), BHA grubunun en bilineni. Akne + siyah nokta + gözenek için altın standart. Tartışma **konsantrasyon ve hamilelikte** odaklı.\n\n## 1. Hamilelik + Emzirme\n\nOral aspirin ve SA bağlantısı doğum komplikasyonlarına neden olabilir (yüksek doz aspirin son trimester). Topikal SA için:\n\n- **%2 altı, leave-on:** sistemik emilim ihmal edilebilir, **çoğu dermatolog güvenli kabul eder**\n- **%2 üstü kabuk tedaviler (peel):** kaçın\n- **Wash-off (jel temizleyici):** %2 → güvenli\n- **Salicylic Acid + alkol bazlı tonikler:** dehydrasyon riski\n\n**ACOG (Amerikan Kadın Doğum Akademisi):** Topikal düşük doz BHA güvenli, ama doktor onayı al.\n\n## 2. Kabuk tedavi konsantrasyonları\n\nDermatolog ofislerinde **%20-30 SA peel** (kimyasal kabuk soyma):\n- Etkili akne + leke + skar tedavisi\n- Hamilelik kontraendike\n- Hassas + rosacea cilde dikkat\n\n## 3. Reye Sendromu (çocuk)\n\n12 yaş altı çocuklarda topikal SA kullanım sınırı yok ama oral aspirin Reye sendromu (karaciğer/beyin hasarı) riski. Çocuk akne tedavisinde doktor onayı.\n\n## 4. Kombinasyon riskleri\n\n- **SA + Retinol aynı akşam:** tahriş katlanır → ayrı gece\n- **SA + AHA:** çift eksfoliasyon riski → haftada birinden başla\n- **SA + Benzoyl Peroxide:** bariyer hasarı → ayrı bölge veya farklı zaman\n\n## 5. Hassas cilt + Rozasea\n\nGenelde **iyi tolere edilir** (anti-enflamatuar). Ama:\n- pH düşüklüğü (3-4) tahriş yapabilir\n- "Beta Hydroxy Acid" yerine doğal alternatif olarak **Willow Bark Extract** (içinde SA prekursörü) hassas cildi tercih edebilir\n\n## Doz rehberi\n\n- **%0.5-1:** başlangıç + hassas cilt\n- **%2:** standart OTC, günlük\n- **%2 üstü:** reçeteli veya ofis prosedürü\n\n## Kaynaklar\n\n- ACOG Committee Opinion #794\n- FDA OTC Drug Monograph for Acne\n- SCCS Opinion 1469/12'
WHERE ingredient_slug = 'salicylic-acid';

-- ============ 7. HYDROQUINONE ============
UPDATE ingredients SET
  controversy_summary = 'En etkili leke açıcı. EU''da reçetesiz yasak (2001), ABD %2 OTC. Ohronoz (cilt kararması) + olası kanserojenik kaygıları.',
  safety_narrative = E'## Neden tartışmalı?\n\nHydroquinone (HQ), tirozinaz inhibitörü olarak melanin sentezini durdurur. Lekeyi en hızlı + en etkili açan topikal aktif. Ama 1980\\''lerden beri ciddi tartışma içinde.\n\n## Düzenleme durumu\n\n| Bölge | Durum |\n|---|---|\n| **EU** | OTC yasak (2001 sonrası), sadece reçeteli |\n| **ABD** | OTC %2 ya da reçeteli %4-8 (FDA 2020 sonrası kısıtlamalar) |\n| **Türkiye** | Reçetesiz (eczane) %2 satılabilir, ama dermatolog kontrolü öneri |\n| **Asya (Japonya, Kore)** | Reçetesiz yaygın |\n| **Afrika (Güney Afrika, Nijerya)** | Yasak (cilt beyazlatıcı suistimal) |\n\n## Temel endişe: Ekzojen Ohronoz\n\nUzun süreli (6+ ay sürekli) yüksek doz (%4+) HQ kullanımı **paradoksal cilt kararması** yaratır:\n- Mavi-siyah pigmentasyon\n- Yüz, boyun bölgesinde\n- **Geri dönüşsüz** (bilinen tedavisi yok)\n- Tedavi başarısızlığı + cosmetic disfigurement\n\n**Kontrollü kullanım:** 3 ay HQ + 3 ay ara (siklik tedavi) standart pratik.\n\n## Kanserojenik tartışma\n\nIARC HQ\\''yu **Grup 3 (insanlarda kanserojenik değil)** olarak sınıflandırdı. Hayvan modelinde yüksek doz oral verildiğinde bazı tümörler. Topikal kullanımda kanser bağlantısı **yok** (uzun vadeli kohort çalışmalar).\n\n## Doğru kullanım\n\n- Sadece **gece**\n- **SPF 50+ sabah zorunlu** (UV maruziyeti tedaviyi sıfırlar + ohronoz riskini artırır)\n- Maks **3 ay sürekli, 1 ay ara** sikli\n- Sadece etki bölgesine (tüm yüz değil, lekeye lokal)\n- Dermatolog kontrolü\n\n## Daha güvenli alternatifler (ohronoz riski yok)\n\n- **Tranexamic Acid %3-5** topikal (oral düşük doz dermatolog reçetesi)\n- **Azelaic Acid %15** (kabuk tedavi olmadan)\n- **Cysteamine %5** (Cyspera) — yeni kuşak\n- **Niacinamide %10**\n- **Alpha Arbutin %2** (hidrokinin türevi, ohronoz riski yok)\n- **Kojic Acid %1**\n\n## Kaynaklar\n\n- IARC Monograph 71 (Hydroquinone)\n- EMA Public Statement on Hydroquinone (2018)\n- AAD Position Statement on Hydroquinone'
WHERE ingredient_slug = 'hydroquinone';

-- ============ 8. SODIUM LAURYL SULFATE (SLS) ============
UPDATE ingredients SET
  controversy_summary = 'Köpük yapan sürfaktant. EU + FDA güvenli kabul ediyor. "Toksik" pazarlama efsanesi yaygın; gerçek endişe: sert temizleyici, bariyer kuruluğu.',
  safety_narrative = E'## Neden tartışmalı?\n\nSodium Lauryl Sulfate (SLS), şampuan + diş macunu + duş jelinde **köpük + temizleme** sağlayan anyonik sürfaktant. 2000\\''ler "Doğal kozmetik" hareketinden bu yana "toksik" suçlamasına maruz kaldı. Çoğu suçlama bilim dışı.\n\n## Bilim ne diyor?\n\n### Kanser (efsane)\nSLS ve **kanser arasında bilimsel kanıt YOK**. ACS (American Cancer Society), EWG, FDA, SCCS hepsi bu iddiayı reddediyor. "İrritan = kanserojen" hatalı bir akıl yürütme.\n\n### Cilt iritasyonu (gerçek)\nSLS güçlü temizleyicidir → **cildin lipid bariyerini soyar**. Sürekli kullanımda:\n- Kuru, sıkı hisseden cilt\n- Pullanma\n- Atopik dermatit alevlenebilir\n- Yıkanırken yanma hissi (özellikle hassas cilt)\n\nSCCS güvenli kabul ediyor — **rinse-off ürünlerde irritan ama toksik değil**.\n\n### Konsantrasyon kritik\n- Şampuan + duş jeli: %5-15 SLS standart\n- Yüz temizleyici için **çok agresif**, alternatif sürfaktan tercih:\n  - Coco-Glucoside\n  - Decyl Glucoside\n  - Sodium Cocoyl Isethionate\n  - Disodium Cocoamphodiacetate\n\n### SLS vs SLES\nSodium Laureth Sulfate (SLES) SLS\\''ye etoxilasyon ekleyerek daha yumuşak forma dönüştürülür. Ama:\n- **1,4-Dioxane kontaminasyon riski** (etoxilasyon yan ürünü)\n- AB safsızlık limitleri var (max 10 ppm)\n- Sertifikalı markalar dioxane temizliği yapmış olur\n\n## Pratik\n\n- **Yüz için:** SLS\\''den kaçın (özellikle kuru/hassas)\n- **Vücut + saç:** uygun, eğer cilt tolere ediyorsa\n- Atopik / ekzemalı cilt için tüm sülfatlar kaçınılmalı\n- "Sülfat-free" şampuan başlangıçta köpürmez ama saçı uzun vadede daha sağlıklı tutar\n\n## Kaynaklar\n\n- SCCS Opinion 1497/12\n- ACS Statement on SLS Safety\n- FDA OTC Status'
WHERE ingredient_slug = 'sodium-lauryl-sulfate';

-- ============ 9. PARABENS (METHYL/PROPYL) ============
UPDATE ingredients SET
  controversy_summary = 'Köklü koruyucu. EU 5 paraben yasakladı (2014), Methyl/Ethyl/Propyl/Butyl güvenli kabul. 2004 meme dokusu çalışması abartılı yorumlandı.',
  safety_narrative = E'## Neden tartışmalı?\n\nParabens, kozmetiklerde **40+ yıldır** mantar/bakteri büyümesini önleyen koruyucu. 2004\\''te bir çalışmada **meme tümör dokularında paraben tespit edilmesi** medya tarafından "kanser nedeni" olarak yanlış aktarıldı. Bilim dünyası bu iddiayı **DESTEKLEMİYOR**.\n\n## Düzenleme durumu (EU)\n\n- **5 paraben yasak** (2014): Isopropyl, Isobutyl, Phenyl, Benzyl, Pentyl parabens\n- **Güvenli + izinli (max %0.4 single, %0.8 mixture):**\n  - Methylparaben\n  - Ethylparaben\n  - Propylparaben\n  - Butylparaben\n- **Bebek wipes (3 yaş altı):** Propyl + Butyl yasak (2015)\n\n## Endokrin endişe\n\nIn vitro çalışmalarda parabens **çok zayıf östrojenik aktivite** gösterir (gerçek östrojenden 100.000 kat daha zayıf). İnsan kohort çalışmalarında klinik etki tespit edilmedi.\n\n## 2004 meme dokusu çalışması\n\nDarbre et al. araştırması:\n- **Yöntem sınırı:** kontrol grubu yok, hangi yoldan girdiği belirsiz (deodorant mı, diğer ürünler mi)\n- **Korelasyon = nedensellik değil** — paraben tespitinin tümörle bağlantısı kanıtlanmadı\n- Meme cerrahları + onkologlar çalışmayı klinik öneri için yetersiz buldu\n\nSonraki **20 yıl, 100+ takip çalışması** kanser bağlantısını gösterEMEDİ. ACS, NCI, EU SCCS hepsi parabens-kanser bağlantısını **reddediyor**.\n\n## Parabensiz ürünler — Daha mı güvenli?\n\nParabens çekildiğinde formül başka koruyucularla doldurulur:\n- **Phenoxyethanol** (paraben kadar güvenli)\n- **Formaldehyde-releasers** (DMDM Hydantoin) — daha problemli!\n- **Methylisothiazolinone (MIT)** — çok yüksek alerjen prevalansı (%5+)\n\n"Paraben-free" mutlaka daha güvenli demek değil. Yedek koruyucuya bak.\n\n## Pratik tavsiye\n\nParabens kullanmaktan **kaçınmaya gerek yok** sağlık nedeniyle. Sadece şu durumlarda:\n- Kontakt dermatit hikayen varsa (alerjenik tepki — nadir, %0.5)\n- Bebek/çocuk ürünleri için EU regülasyonu zaten daha sıkı\n\n## Kaynaklar\n\n- SCCS Opinion 1446/11 (parabens safety)\n- ACS Position on Parabens (2020)\n- Darbre et al., J Appl Toxicol 2004 (orijinal kontrovers çalışma)\n- Hager et al., Front Toxicol 2022 (review of paraben endocrine claims)'
WHERE ingredient_slug = 'methylparaben';

-- ============ 10. DIMETHICONE ============
UPDATE ingredients SET
  controversy_summary = 'Silikon. Cilt yüzeyinde "nefes almayan film" efsanesi yanlış. Komedojen değil, anti-irritan, evrensel güvenli kabul ediliyor.',
  safety_narrative = E'## Neden tartışmalı?\n\nDimethicone (polidimetilsiloksan, PDMS) silikon polimer. Cilt + saç ürünlerinde **"silky" doku ve nem kilidi** sağlar. "Doğal kozmetik" pazarlamasının hedefinde olduğu için yanlış bilgi yaygın.\n\n## Yaygın efsaneler\n\n### "Cildin nefes almasını engeller" (YANLIŞ)\nCilt akciğer değil — gaz değişimi yapmaz. Dimethicone film yarı geçirgen: su buharı geçer, dış kontaminantları engeller. Bu özellik **bariyer onarımına yardımcıdır**.\n\n### "Komedojendir" (YANLIŞ)\nCenter for Cosmetic Safety + JAAD studies: Dimethicone **non-comedogenic** sınıflandırması. Aksine, akneli ciltte **zinc oxide** ile birlikte kullanılan tedavi formüllerinde bulunur.\n\n### "Çevre için zararlı" (KISMEN DOĞRU)\nD4, D5, D6 (siklik silikonlar) çevresel persistans gösterir. **Ama doğrusal silikonlar (Dimethicone gibi)** daha hızlı bozunur. EU REACH altında "preocupying" sınıflandırması yok.\n\n## Pratik faydalar\n\n1. **Bariyer onarımı:** Skar krem ve onarıcı kremlerde standart\n2. **Anti-irritan:** retinol/AHA tedavisinde "sandwich tekniği" için ideal\n3. **Makyaj baz:** primer + foundation pürüzsüz uygulama\n4. **Saç:** uç sertliği + kepeklenmeyi azaltır (ama uzun süreli build-up için ara ara clarifying şampuan)\n\n## Kimler kaçınmalı?\n\n- Belirli bir alerji geliştirenler (çok nadir — %0.1)\n- "Slip kötüsü" hisseden kişisel tercih\n- Spesifik dermatolog önerisi\n\n## Saçta build-up\n\nDimethicone saç ipliği üzerinde birikir. **Sülfatlı şampuan** veya **clarifying shampoo** ile çözülür. Sülfat-free + dimethicone-heavy kombinasyonu uzun vadede yağlı + ağır saç.\n\n## Kanıt seviyesi\n\nGüvenlik için: **CIR (Cosmetic Ingredient Review) + SCCS hepsi GÜVENLİ kabul ediyor.** 30+ yıllık güvenlik dosyası.\n\n## Kaynaklar\n\n- CIR Final Report on Dimethicone (2003, güncellenmiş 2020)\n- SCCS Opinion 1416/11\n- Lai et al., Dermatol Ther 2017 (silikonların bariyer rolü)'
WHERE ingredient_slug = 'dimethicone';

-- ============ 11. ALUMINUM CHLOROHYDRATE (DEODORANT) ============
UPDATE ingredients SET
  controversy_summary = 'Antiperspiran etken madde. Meme kanseri + Alzheimer iddiaları bilimsel destekten yoksun. Böbrek hastalarında dikkat gerekiyor.',
  safety_narrative = E'## Neden tartışmalı?\n\nAluminum Chlorohydrate (ACH), antiperspiranlarda ter kanallarını fiziksel olarak tıkayarak ter üretimini azaltır. 1990\\''lardan beri 2 ana iddia tartışılıyor: meme kanseri + Alzheimer.\n\n## Meme kanseri iddiası\n\nİddia: ACH koltuk altından emilim → meme dokusunda birikim → tümör.\n\nBilimsel durum:\n- **NCI (National Cancer Institute):** doğrulanmış kanıt yok\n- **ACS (American Cancer Society):** "Yeterli kanıt yok"\n- 50+ epidemiyolojik çalışma sonuç negatif\n- Cilt yoluyla emilim **çok düşük** (%0.012 - <%0.05)\n\n## Alzheimer iddiası\n\n1960\\''larda Alzheimer beyinlerinde alüminyum tespit edildiğinde. Sonradan:\n- Kontrol gruplarında da benzer seviyede alüminyum\n- Demir gibi çeşitli metaller benzer artış gösterdi\n- **Alzheimer Association:** "Alüminyum-Alzheimer bağlantısı kanıtlanmadı"\n\n## Gerçek dikkat noktaları\n\n### 1. Böbrek hastalığı\n**Kronik böbrek yetersizliği** olanlarda alüminyum atılımı bozuk → birikim riski. Bu hastalarda dermatolog onayı al.\n\n### 2. Tıraş + Antiperspiran\nFreshly shaved (tıraşlı) cilt geçirgenliği yüksek → tahriş riski artar. **Tıraş sonrası 30 dk bekle**, sonra uygula.\n\n### 3. Mammografi\nAntiperspiran kalsifikasyon görüntülemesini zorlaştırabilir. **Mammografi sabahı uygulama yapma** (ofiste yıkar/temizler).\n\n## Alüminyumsuz alternatifler\n\nDeodorant (terlemeyi durdurmaz, sadece kokuyu maskeler):\n- **Sodium Bicarbonate** (kabartma tozu) — pH 9, hassas cilt için tahriş edici olabilir\n- **Magnesium Hydroxide** — daha yumuşak\n- **Probiyotik deodorantlar** — koku üreten bakterileri dengeler\n\n**Kıyaslama:** Antiperspiran (alüminyum tabanlı) ter durdurur. Doğal deodorant ter durdurmaz, sadece kokulanmayı geciktirir.\n\n## Pratik\n\n- Sağlıklı yetişkin için ACH antiperspiran **güvenli**\n- Hassas koltuk altı + tıraş hattı için doğal deodorant tercih\n- Geceleri uygulama daha etkili (ter kanalı geceleri açık)\n\n## Kaynaklar\n\n- NCI Fact Sheet: Antiperspirants and Breast Cancer\n- Alzheimer Association Position Statement\n- SCCS Opinion 1613/19 (aluminum cosmetic safety)'
WHERE ingredient_slug = 'aluminum-chlorohydrate';

-- ============ 12. TALC ============
UPDATE ingredients SET
  controversy_summary = 'Magnezyum silikat (mineral). Asbest kontaminasyon riski tarihsel. Kozmetik talkı bugün test edilmiş. Kadın bölgesi pudra kullanımında over kanseri ilişkisi tartışmalı.',
  safety_narrative = E'## Neden tartışmalı?\n\nTalc, doğal mineral magnezyum silikat. Bebek pudrası, makyaj (özellikle baby/setting powder), deodorant + kişisel bakım ürünlerinde. 2 ayrı endişe:\n\n### 1. Asbest kontaminasyonu\nTalc + asbest jeolojik olarak yan yana oluşur. **1970 öncesi** kozmetik talkında asbest tespit edildi. 1976\\''dan beri kozmetik endüstri asbest-test edilmiş talc kullanır. Yine de:\n- **Türkiye + EU:** sertifikalı asbest-free zorunlu\n- **ABD:** FDA testleri sürüyor (J&J 2019 baby powder geri çağırma)\n\n### 2. Over kanseri (kadın hijyen kullanımı)\nUzun yıllar kadın bölgesinde talc bazlı pudra kullanımı + over kanseri arasında **zayıf istatistiksel korelasyon** gözlendi (RR 1.2-1.4 — yani %20-40 artış). Ama:\n- Korelasyon zayıf, kontrol grubu zorluğu\n- Asbest-free talc ile bu risk **belirgin değil**\n- IARC kadın hijyen bölgesi kullanımını **2B (insanda olası kanserojenik)** sınıflandırdı\n- ACS: "Yeterli kanıt yok ama önlem olarak kaçınılabilir"\n\n## Yüz + vücut kullanımı\n\nMakyaj ve vücut pudraları için **endişe çok daha düşük**. EU SCCS güvenli kabul ediyor (asbest-free şartıyla).\n\n## Solunum riski\n\n**Bebek pudrasını yüze püskürtmek inhale ettirir** — bebek akciğerini tahriş eder. AAP (American Academy of Pediatrics) **bebek talc pudrasını önermiyor** (1981 sonrası).\n\nAlternatif:\n- **Mısır nişastası** (cornstarch) tabanlı pudra\n- Yüksek mantar enfeksiyonu riski (cornstarch fungus için besin)\n- Doğal arrowroot, tapioca pudraları\n\n## Düzenleme\n\n- **EU:** Talc kullanımı izinli, asbest-free sertifikası zorunlu\n- **Türkiye:** AB uyumlu\n- **Kanada:** kadın bölgesi pudra için "alabilirlik şüpheli" etiketi tartışılıyor\n- **ABD:** California Prop 65 etiketi (FDA evaluating)\n\n## Pratik\n\n**Kullan:**\n- Yüz makyajında setting powder olarak (asbest-free etiketi varsa)\n- Bebek altı bezi alanında **DEĞİL**\n- Yetişkin koltuk altı için OK ama alternatif tercih edilebilir\n\n**Kaçın:**\n- Kadın hijyen bölgesi (pudra olarak)\n- Yüze sprey/aerosol pudralar (inhale riski)\n\n## Kaynaklar\n\n- IARC Monograph 93 (Talc)\n- SCCS Opinion 1568/15\n- AAP Policy Statement: Baby Powder (2009)'
WHERE ingredient_slug = 'talc';

-- ============ Post-update raporu ============
SELECT
  inci_name,
  ingredient_slug,
  CASE WHEN safety_narrative IS NOT NULL THEN '✓' ELSE '—' END AS narrative,
  CASE WHEN controversy_summary IS NOT NULL THEN '✓' ELSE '—' END AS summary
FROM ingredients
WHERE ingredient_slug IN (
  'phenoxyethanol','parfum','cyclopentasiloxane','oxybenzone',
  'retinol','salicylic-acid','hydroquinone','sodium-lauryl-sulfate',
  'methylparaben','dimethicone','aluminum-chlorohydrate','talc'
)
ORDER BY inci_name;
