-- ============================================
-- BATCH 4 Part 3: Products 701-883
-- ============================================
INSERT INTO products (product_id, brand_id, category_id, domain_type, product_name, product_slug, product_type_label, short_description, net_content_value, net_content_unit, target_area, usage_time_hint, status) VALUES
(701, 38, 3, 'cosmetic', 'Numbuzin No.7 Mild Sun Essence SPF50+', 'numbuzin-no7-mild-sun-essence', 'güneş kremi', 'Nazik güneş esansı.', '50.00', 'ml', 'face', 'morning', 'published'),
(702, 49, 1, 'cosmetic', 'Kiehl''s Rare Earth Deep Pore Cleansing Masque', 'kiehls-rare-earth-pore-masque', 'maske', 'Amazon beyaz kili gözenek maskesi.', '75.00', 'ml', 'face', 'evening', 'published'),
(703, 49, 1, 'cosmetic', 'Kiehl''s Powerful-Strength Vitamin C Serum', 'kiehls-powerful-strength-vitamin-c', 'serum', 'Güçlü C vitamini %12.5 serum.', '50.00', 'ml', 'face', 'both', 'published'),
(704, 49, 1, 'cosmetic', 'Kiehl''s Ultra Facial Overnight Hydrating Mask', 'kiehls-ultra-facial-overnight-mask', 'maske', 'Gece HA nemlendirme maskesi.', '75.00', 'ml', 'face', 'evening', 'published'),
(705, 49, 1, 'cosmetic', 'Kiehl''s Age Defender Moisturizer SPF30', 'kiehls-age-defender-moisturizer', 'gündüz kremi', 'Erkekler anti-aging nemlendirici SPF30.', '30.00', 'ml', 'face', 'morning', 'published'),
(706, 49, 5, 'cosmetic', 'Kiehl''s Lip Balm #1', 'kiehls-lip-balm-1', 'dudak bakım', 'Klasik dudak balmı. Squalane + Aloe.', '15.00', 'ml', 'lips', 'both', 'published'),
(707, 50, 1, 'cosmetic', 'Clinique Moisture Surge Overnight Mask', 'clinique-moisture-surge-overnight-mask', 'maske', 'Gece nem maskesi. 72 saat nemlendirme.', '50.00', 'ml', 'face', 'evening', 'published'),
(708, 50, 1, 'cosmetic', 'Clinique Dramatically Different Moisturizing Gel', 'clinique-dramatically-different-gel', 'nemlendirici', 'Jel nemlendirici. Yağsız formül.', '75.00', 'ml', 'face', 'both', 'published'),
(709, 50, 1, 'cosmetic', 'Clinique Fresh Pressed Vitamin C Booster', 'clinique-fresh-pressed-vitamin-c', 'serum', 'Taze sıkılmış C vitamini %10.', '20.00', 'ml', 'face', 'both', 'published'),
(710, 50, 4, 'cosmetic', 'Clinique Pep-Start Eye Cream', 'clinique-pep-start-eye-cream', 'göz kremi', 'Peptit başlangıç göz kremi.', '20.00', 'ml', 'eye', 'both', 'published'),
(711, 50, 2, 'cosmetic', 'Clinique Anti-Blemish Solutions Cleansing Gel', 'clinique-anti-blemish-cleansing-gel', 'temizleyici', 'Akne temizleme jeli. Salisilik asit.', '250.00', 'ml', 'face', 'both', 'published'),
(712, 52, 2, 'cosmetic', 'Shiseido WASO Quick Gentle Cleanser', 'shiseido-waso-quick-gentle-cleanser', 'temizleyici', 'Nazik hızlı temizleyici. Tofu filtresi.', '400.00', 'ml', 'face', 'both', 'published'),
(713, 52, 4, 'cosmetic', 'Shiseido Essential Energy Eye Definer', 'shiseido-essential-energy-eye-definer', 'göz kremi', 'Göz çevresi tanımlayıcı. ReNeura.', '30.00', 'ml', 'eye', 'both', 'published'),
(714, 52, 1, 'cosmetic', 'Shiseido Men Total Revitalizer Cream', 'shiseido-men-total-revitalizer', 'krem', 'Erkekler toplam canlandırıcı krem.', '75.00', 'ml', 'face', 'both', 'published'),
(715, 52, 3, 'cosmetic', 'Shiseido Synchro Skin Self-Refreshing SPF30', 'shiseido-synchro-skin-spf30', 'güneş kremi', 'Kendi kendini yenileyen SPF30 bakım.', '100.00', 'ml', 'face', 'morning', 'published'),
(716, 54, 2, 'cosmetic', 'Dermalogica Precleanse', 'dermalogica-precleanse-dermalogica', 'temizleme yağı', 'Ön temizleme yağı. Çift temizleme.', '150.00', 'ml', 'face', 'evening', 'published'),
(717, 54, 1, 'cosmetic', 'Dermalogica Active Moist Moisturizer', 'dermalogica-active-moist', 'nemlendirici', 'Aktif nemlendirici. Yağsız formül.', '30.00', 'ml', 'face', 'both', 'published'),
(718, 54, 1, 'cosmetic', 'Dermalogica Overnight Repair Serum', 'dermalogica-overnight-repair-serum', 'serum', 'Gece onarım serumu. Retinol + Peptit.', '20.00', 'ml', 'face', 'both', 'published'),
(719, 54, 1, 'cosmetic', 'Dermalogica Calm Water Gel', 'dermalogica-calm-water-gel', 'nemlendirici', 'Yatıştırıcı su jel. Hassas ciltler.', '100.00', 'ml', 'face', 'both', 'published'),
(720, 61, 1, 'cosmetic', 'Aveeno Oat Gel Moisturizer with Niacinamide', 'aveeno-oat-gel-niacinamide', 'nemlendirici', 'Yulaf + Niacinamide jel nemlendirici.', '50.00', 'ml', 'face', 'both', 'published'),
(721, 61, 6, 'cosmetic', 'Aveeno Daily Moisturizing Body Yogurt', 'aveeno-daily-body-yogurt', 'vücut kremi', 'Günlük vücut yoğurdu. Yulaf + prebiyotik.', '400.00', 'ml', 'body', 'both', 'published'),
(722, 61, 1, 'cosmetic', 'Aveeno Calm + Restore Redness Relief Moisturizing Cream', 'aveeno-calm-restore-redness-cream', 'krem', 'Kızarıklık yatıştırıcı krem.', '30.00', 'ml', 'face', 'both', 'published'),
(723, 61, 3, 'cosmetic', 'Aveeno Protect + Hydrate Face Sunscreen SPF50', 'aveeno-protect-hydrate-face-spf50', 'güneş kremi', 'Koruma + nemlendirme güneş kremi.', '60.00', 'ml', 'face', 'morning', 'published'),
(724, 62, 2, 'cosmetic', 'Simple Kind To Skin Cleansing Oil', 'simple-kind-cleansing-oil', 'temizleme yağı', 'Nazik temizleme yağı.', '150.00', 'ml', 'face', 'evening', 'published'),
(725, 62, 1, 'cosmetic', 'Simple Water Boost Hydrating Gel Cream', 'simple-water-boost-hydrating-gel', 'nemlendirici', 'Su takviyesi jel krem.', '30.00', 'ml', 'face', 'both', 'published'),
(726, 62, 1, 'cosmetic', 'Simple Booster Serum 10% Niacinamide', 'simple-booster-serum-niacinamide', 'serum', 'Niacinamide %10 booster serum.', '30.00', 'ml', 'face', 'both', 'published'),
(727, 62, 2, 'cosmetic', 'Simple Kind To Skin Eye Makeup Remover', 'simple-kind-eye-makeup-remover', 'micellar su', 'Göz makyajı temizleyici.', '400.00', 'ml', 'face', 'evening', 'published'),
(728, 63, 6, 'cosmetic', 'Sebamed Anti-Dry Hydrating Body Lotion', 'sebamed-anti-dry-hydrating-body-lotion', 'vücut losyonu', 'Kuruluğa karşı vücut losyonu.', '400.00', 'ml', 'body', 'both', 'published'),
(729, 63, 2, 'cosmetic', 'Sebamed Clear Face Cleansing Foam pH 5.5', 'sebamed-clear-face-foam-ph55', 'temizleyici', 'pH 5.5 temizleme köpüğü.', '250.00', 'ml', 'face', 'both', 'published'),
(730, 63, 5, 'cosmetic', 'Sebamed Lip Defense SPF30', 'sebamed-lip-defense-spf30', 'dudak bakım', 'Dudak koruyucu SPF30.', '15.00', 'ml', 'lips', 'both', 'published'),
(731, 63, 3, 'cosmetic', 'Sebamed Sensitive Skin Expert Sun Spray SPF30', 'sebamed-sensitive-sun-spray-spf30', 'güneş kremi', 'Hassas cilt güneş spreyi.', '40.00', 'ml', 'face', 'morning', 'published'),
(732, 67, 1, 'cosmetic', 'Caudalie Vinoperfect Dark Spot Correcting Glycolic Night Cream', 'caudalie-vinoperfect-glycolic-night', 'gece kremi', 'Glikolik asit leke gece kremi.', '75.00', 'ml', 'face', 'evening', 'published'),
(733, 67, 1, 'cosmetic', 'Caudalie Vinosource-Hydra SOS Deep Hydration Cream', 'caudalie-vinosource-sos-deep-cream', 'krem', 'SOS derin nemlendirme kremi.', '50.00', 'ml', 'face', 'both', 'published'),
(734, 67, 1, 'cosmetic', 'Caudalie Instant Detox Mask', 'caudalie-instant-detox-mask-caudalie', 'maske', 'Anında detoks maskesi. Pembe kil.', '30.00', 'ml', 'face', 'evening', 'published'),
(735, 67, 1, 'cosmetic', 'Caudalie Grape Water Moisturizing Face Mist', 'caudalie-grape-water-face-mist', 'mist', 'Üzüm suyu nemlendirici mist.', '150.00', 'ml', 'face', 'both', 'published'),
(736, 69, 1, 'cosmetic', 'Filorga NCEF-Shot Supreme Polyrevitalising Concentrate', 'filorga-ncef-shot-supreme', 'serum', '10 günlük yoğun kür. NCEF konsantre.', '50.00', 'ml', 'face', 'both', 'published'),
(737, 69, 1, 'cosmetic', 'Filorga Sleep & Peel Night Cream', 'filorga-sleep-peel-night-cream', 'gece kremi', 'Gece peeling krem. AHA + enzimler.', '50.00', 'ml', 'face', 'evening', 'published'),
(738, 69, 3, 'cosmetic', 'Filorga UV-Defence Sun Care SPF50+', 'filorga-uv-defence-sun-care', 'güneş kremi', 'Anti-aging güneş bakımı.', '40.00', 'ml', 'face', 'morning', 'published'),
(739, 69, 1, 'cosmetic', 'Filorga Meso-Mask Smoothing Radiance Mask', 'filorga-meso-mask-smoothing', 'maske', 'Pürüzsüzleştirici parlaklık maskesi.', '75.00', 'ml', 'face', 'evening', 'published'),
(740, 55, 1, 'cosmetic', 'Murad Vita-C Glycolic Brightening Serum', 'murad-vita-c-glycolic-brightening', 'serum', 'C vitamini + Glikolik asit aydınlatıcı.', '20.00', 'ml', 'face', 'both', 'published'),
(741, 55, 4, 'cosmetic', 'Murad Renewing Eye Cream', 'murad-renewing-eye-cream-murad', 'göz kremi', 'Yenileyici göz kremi. Retinol.', '10.00', 'ml', 'eye', 'both', 'published'),
(742, 55, 1, 'cosmetic', 'Murad Clarifying Body Spray', 'murad-clarifying-body-spray', 'mist', 'Vücut akne spreyi. Salisilik asit.', '150.00', 'ml', 'face', 'both', 'published'),
(743, 55, 3, 'cosmetic', 'Murad Oil and Pore Control Mattifier SPF45', 'murad-oil-pore-control-spf45', 'güneş kremi', 'Yağ kontrol mattifier. SPF45.', '50.00', 'ml', 'face', 'morning', 'published'),
(744, 56, 1, 'cosmetic', 'Sunday Riley Saturn Sulfur Acne Treatment Mask', 'sunday-riley-saturn-sulfur-acne-mask', 'maske', 'Kükürt akne maskesi.', '50.00', 'ml', 'face', 'evening', 'published'),
(745, 56, 1, 'cosmetic', 'Sunday Riley Juno Antioxidant + Superfood Face Oil', 'sunday-riley-juno-antioxidant-face-oil', 'yüz yağı', 'Süper gıda antioksidan yüz yağı.', '15.00', 'ml', 'face', 'evening', 'published'),
(746, 56, 1, 'cosmetic', 'Sunday Riley Tidal Brightening Enzyme Water Cream', 'sunday-riley-tidal-brightening-water-cream', 'krem', 'Enzim su krem. Aydınlatıcı.', '30.00', 'ml', 'face', 'both', 'published'),
(747, 59, 1, 'cosmetic', 'Glow Recipe Watermelon Glow Hyaluronic Clay Pore-Tight Facial', 'glow-recipe-watermelon-hyaluronic-clay', 'maske', 'Karpuz HA kil maskesi. Gözenek sıkılaştırıcı.', '50.00', 'ml', 'face', 'evening', 'published'),
(748, 59, 1, 'cosmetic', 'Glow Recipe Banana Soufflé Moisture Cream', 'glow-recipe-banana-souffle-cream', 'krem', 'Muz sufle nemlendirici krem. Magnezyum.', '75.00', 'ml', 'face', 'both', 'published'),
(749, 59, 1, 'cosmetic', 'Glow Recipe Guava Vitamin C Dark Spot Serum', 'glow-recipe-guava-vitamin-c-dark-spot', 'serum', 'Guava C vitamini leke serumu.', '20.00', 'ml', 'face', 'both', 'published'),
(750, 60, 1, 'cosmetic', 'Farmacy Honeymoon Glow AHA Resurfacing Night Serum', 'farmacy-honeymoon-glow-aha-serum', 'peeling', 'AHA gece peeling serumu. Bal + Çiçek asitleri.', '100.00', 'ml', 'face', 'evening', 'published'),
(751, 60, 1, 'cosmetic', 'Farmacy Very Cherry Bright 15% Clean Vitamin C Serum', 'farmacy-very-cherry-bright-vitamin-c', 'serum', 'Kiraz C vitamini %15 serum.', '30.00', 'ml', 'face', 'both', 'published'),
(752, 60, 1, 'cosmetic', 'Farmacy Filling Good Hyaluronic Acid Plumping Serum', 'farmacy-filling-good-ha-serum', 'serum', 'HA dolgunlaştırıcı serum.', '50.00', 'ml', 'face', 'both', 'published'),
(753, 65, 1, 'cosmetic', 'Weleda Evening Primrose Age Revitalising Body Oil', 'weleda-evening-primrose-body-oil', 'yüz yağı', 'Çuha çiçeği canlandırıcı vücut yağı.', '30.00', 'ml', 'face', 'evening', 'published'),
(754, 65, 1, 'cosmetic', 'Weleda Calendula Baby Face Cream', 'weleda-calendula-baby-face-cream', 'krem', 'Calendula bebek yüz kremi.', '30.00', 'ml', 'face', 'both', 'published'),
(755, 65, 1, 'cosmetic', 'Weleda Iris Hydrating Facial Lotion', 'weleda-iris-hydrating-facial-lotion', 'nemlendirici', 'Süsen nemlendirici losyon. Karma ciltler.', '50.00', 'ml', 'face', 'both', 'published'),
(756, 49, 2, 'cosmetic', 'Kiehl''s Amino Acid Shampoo', 'kiehls-amino-acid-shampoo', 'temizleyici', 'Amino asit şampuan. Nazik temizlik.', '150.00', 'ml', 'face', 'both', 'published'),
(757, 49, 1, 'cosmetic', 'Kiehl''s Super Multi-Corrective Cream', 'kiehls-super-multi-corrective-cream', 'krem', 'Çoklu düzeltici krem. Jasmonic asit.', '30.00', 'ml', 'face', 'both', 'published'),
(758, 49, 1, 'cosmetic', 'Kiehl''s Pure Vitality Skin Renewing Cream', 'kiehls-pure-vitality-renewing-cream', 'krem', 'Manuka balı canlandırıcı krem.', '75.00', 'ml', 'face', 'both', 'published'),
(759, 49, 5, 'cosmetic', 'Kiehl''s Buttermask for Lips', 'kiehls-buttermask-for-lips', 'dudak bakım', 'Dudak yağ maskesi. Hindistan cevizi + Mango.', '10.00', 'ml', 'lips', 'both', 'published'),
(760, 50, 5, 'cosmetic', 'Clinique Moisture Surge Lip Hydro-Plump Treatment', 'clinique-moisture-surge-lip-plump', 'dudak bakım', 'Dudak dolgunlaştırıcı. HA.', '15.00', 'ml', 'lips', 'both', 'published'),
(761, 50, 1, 'cosmetic', 'Clinique Even Better Clinical Serum Foundation SPF20', 'clinique-even-better-serum-foundation', 'gündüz kremi', 'Serum fondöten. Leke düzeltici SPF20.', '50.00', 'ml', 'face', 'morning', 'published'),
(762, 50, 3, 'cosmetic', 'Clinique Superdefense City Block SPF50 Face Protector', 'clinique-superdefense-city-block-spf50', 'güneş kremi', 'Şehir koruyucu SPF50.', '100.00', 'ml', 'face', 'morning', 'published'),
(763, 50, 2, 'cosmetic', 'Clinique Rinse-Off Foaming Cleanser', 'clinique-rinse-off-foaming-cleanser', 'temizleyici', 'Durulanan köpük temizleyici.', '500.00', 'ml', 'face', 'both', 'published'),
(764, 21, 1, 'cosmetic', 'Paula''s Choice RESIST Daily Pore-Refining Treatment 2% BHA', 'paulas-choice-resist-daily-pore-refining', 'serum', 'Gözenek rafine edici %2 BHA.', '20.00', 'ml', 'face', 'both', 'published'),
(765, 21, 1, 'cosmetic', 'Paula''s Choice Clinical Niacinamide 20% Treatment', 'paulas-choice-clinical-niacinamide-20', 'serum', 'Klinik niacinamide %20.', '30.00', 'ml', 'face', 'both', 'published'),
(766, 21, 1, 'cosmetic', 'Paula''s Choice DEFENSE Antioxidant Pore Purifier with Retinol', 'paulas-choice-defense-antioxidant-retinol', 'serum', 'Antioksidan + Retinol gözenek arındırıcı.', '30.00', 'ml', 'face', 'both', 'published'),
(767, 21, 1, 'cosmetic', 'Paula''s Choice Skin Balancing Pore-Reducing Toner', 'paulas-choice-skin-balancing-pore-toner', 'tonik', 'Denge tonik. Gözenek küçültücü.', '250.00', 'ml', 'face', 'both', 'published'),
(768, 21, 3, 'cosmetic', 'Paula''s Choice RESIST Smoothing Primer SPF30', 'paulas-choice-resist-smoothing-primer-spf30', 'güneş kremi', 'Pürüzsüzleştirici primer SPF30.', '50.00', 'ml', 'face', 'morning', 'published'),
(769, 8, 1, 'cosmetic', 'Neutrogena Hydro Boost Hyaluronic Acid Serum', 'neutrogena-hydro-boost-ha-serum', 'serum', 'HA konsantre serum.', '30.00', 'ml', 'face', 'both', 'published'),
(770, 8, 1, 'cosmetic', 'Neutrogena Rapid Wrinkle Repair Retinol Pro+', 'neutrogena-rapid-wrinkle-repair-retinol', 'serum', 'Retinol Pro+ kırışıklık serumu.', '30.00', 'ml', 'face', 'both', 'published'),
(771, 8, 2, 'cosmetic', 'Neutrogena Clear & Soothe Micellar Jelly Makeup Remover', 'neutrogena-clear-soothe-micellar-jelly', 'micellar su', 'Micellar jöle temizleyici.', '200.00', 'ml', 'face', 'evening', 'published'),
(772, 8, 4, 'cosmetic', 'Neutrogena Cellular Boost Eye Rejuvenating Cream', 'neutrogena-cellular-boost-eye-cream', 'göz kremi', 'Hücresel boost göz kremi.', '30.00', 'ml', 'eye', 'both', 'published'),
(773, 8, 6, 'cosmetic', 'Neutrogena Deep Moisture Body Lotion', 'neutrogena-deep-moisture-body-lotion', 'vücut losyonu', 'Derin nem vücut losyonu.', '250.00', 'ml', 'body', 'both', 'published'),
(774, 19, 1, 'cosmetic', 'Some By Mi AHA BHA PHA 30 Days Miracle Toner 150ml', 'some-by-mi-aha-bha-pha-miracle-toner-150', 'tonik', '30 gün mucize tonik. Büyük boy.', '200.00', 'ml', 'face', 'both', 'published'),
(775, 19, 2, 'cosmetic', 'Some By Mi Cica Peptide Anti Hair Loss Shampoo', 'some-by-mi-cica-peptide-anti-hair-loss', 'temizleyici', 'Saç dökülmesi karşıtı şampuan.', '473.00', 'ml', 'face', 'both', 'published'),
(776, 19, 1, 'cosmetic', 'Some By Mi Super Matcha Pore Tightening Serum', 'some-by-mi-super-matcha-pore-tightening', 'serum', 'Matcha gözenek sıkılaştırıcı serum.', '20.00', 'ml', 'face', 'both', 'published'),
(777, 19, 2, 'cosmetic', 'Some By Mi Bye Bye Blackhead 30 Days Miracle Green Tea Tox Bubble Cleanser', 'some-by-mi-bye-bye-blackhead-bubble', 'temizleyici', 'Siyah nokta temizleyici köpük.', '300.00', 'ml', 'face', 'both', 'published'),
(778, 19, 3, 'cosmetic', 'Some By Mi Truecica Mineral Calming Tone Up Suncream SPF50+', 'some-by-mi-truecica-tone-up-sun', 'güneş kremi', 'Cica renkli güneş kremi.', '100.00', 'ml', 'face', 'morning', 'published'),
(779, 26, 1, 'cosmetic', 'Garnier SkinActive Serum Cream SPF30 with Vitamin C', 'garnier-skinactive-serum-cream-spf30', 'gündüz kremi', 'Serum krem SPF30. C vitamini.', '30.00', 'ml', 'face', 'morning', 'published'),
(780, 26, 1, 'cosmetic', 'Garnier Bio Organic Argan Nourishing Moisturizer', 'garnier-bio-argan-nourishing', 'krem', 'Organik argan besleyici krem.', '30.00', 'ml', 'face', 'both', 'published'),
(781, 26, 2, 'cosmetic', 'Garnier PureActive Sensitive Anti-Blemish Cleansing Gel', 'garnier-pureactive-sensitive-gel', 'temizleyici', 'Hassas akne temizleme jeli.', '150.00', 'ml', 'face', 'both', 'published'),
(782, 26, 1, 'cosmetic', 'Garnier SkinActive Hyaluronic Acid Replumping Serum', 'garnier-skinactive-ha-replumping-serum', 'serum', 'HA dolgunlaştırıcı serum.', '20.00', 'ml', 'face', 'both', 'published'),
(783, 26, 3, 'cosmetic', 'Garnier Ambre Solaire Kids Sensitive SPF50+', 'garnier-ambre-solaire-kids-spf50', 'güneş kremi', 'Çocuk hassas güneş kremi.', '60.00', 'ml', 'face', 'morning', 'published'),
(784, 27, 1, 'cosmetic', 'Nivea Derma Skin Clear Scrub', 'nivea-derma-skin-clear-scrub', 'peeling', 'Cilt berraklaştırıcı peeling. Salisilik asit.', '100.00', 'ml', 'face', 'evening', 'published'),
(785, 27, 1, 'cosmetic', 'Nivea Q10 Energy Recharging Night Cream', 'nivea-q10-energy-recharging-night', 'gece kremi', 'Q10 enerji şarj gece kremi.', '75.00', 'ml', 'face', 'evening', 'published'),
(786, 27, 1, 'cosmetic', 'Nivea Urban Skin Detox Gel Moisturizer', 'nivea-urban-skin-detox-gel', 'nemlendirici', 'Şehir detoks jel nemlendirici.', '30.00', 'ml', 'face', 'both', 'published'),
(787, 27, 1, 'cosmetic', 'Nivea Derma Skin Clear Night Exfoliator', 'nivea-derma-skin-clear-night-exfoliator', 'peeling', 'Gece eksfolyan. Niacinamide.', '100.00', 'ml', 'face', 'evening', 'published'),
(788, 27, 1, 'cosmetic', 'Nivea MEN Protect & Care Face Moisturiser SPF15', 'nivea-men-protect-care-spf15', 'gündüz kremi', 'Erkekler nemlendirici SPF15.', '30.00', 'ml', 'face', 'morning', 'published'),
(789, 28, 4, 'cosmetic', 'Innisfree Green Tea Seed Eye Cream', 'innisfree-green-tea-seed-eye-cream-inn', 'göz kremi', 'Yeşil çay tohumu göz kremi.', '15.00', 'ml', 'eye', 'both', 'published'),
(790, 28, 1, 'cosmetic', 'Innisfree Super Volcanic Pore Clay Mask 2X', 'innisfree-super-volcanic-pore-2x', 'maske', 'Süper volkanik kil maskesi. 2X güçlü.', '100.00', 'ml', 'face', 'evening', 'published'),
(791, 28, 1, 'cosmetic', 'Innisfree Cherry Blossom Jelly Cream', 'innisfree-cherry-blossom-jelly-cream', 'krem', 'Kiraz çiçeği jöle krem. Aydınlatıcı.', '50.00', 'ml', 'face', 'both', 'published'),
(792, 28, 1, 'cosmetic', 'Innisfree Intensive Hydrating Cream with Green Tea Seed', 'innisfree-intensive-hydrating-green-tea', 'krem', 'Yoğun yeşil çay nemlendirici.', '75.00', 'ml', 'face', 'both', 'published'),
(793, 25, 1, 'cosmetic', 'Missha Artemisia Calming Moisture Cream', 'missha-artemisia-calming-moisture', 'krem', 'Artemisia yatıştırıcı krem.', '50.00', 'ml', 'face', 'both', 'published'),
(794, 25, 3, 'cosmetic', 'Missha All Around Safe Block Aqua Sun Gel SPF50+', 'missha-safe-block-aqua-sun-gel', 'güneş kremi', 'Aqua güneş jeli.', '100.00', 'ml', 'face', 'morning', 'published'),
(795, 25, 1, 'cosmetic', 'Missha Time Revolution Red Algae Revitalizing Cream', 'missha-red-algae-revitalizing-cream', 'krem', 'Kırmızı alg canlandırıcı krem.', '30.00', 'ml', 'face', 'both', 'published'),
(796, 25, 1, 'cosmetic', 'Missha Vita C Plus Brightening Toner', 'missha-vita-c-plus-brightening-toner', 'tonik', 'C vitamini aydınlatıcı tonik.', '150.00', 'ml', 'face', 'both', 'published'),
(797, 17, 1, 'cosmetic', 'Klairs Midnight Blue Youth Activating Drop', 'klairs-midnight-blue-youth-drop', 'serum', 'Guaiazulene gençlik damlası.', '30.00', 'ml', 'face', 'both', 'published'),
(798, 17, 4, 'cosmetic', 'Klairs Fundamental Nourishing Eye Butter', 'klairs-fundamental-eye-butter', 'göz kremi', 'Besleyici göz yağı. Shea + Ceramide.', '20.00', 'ml', 'eye', 'both', 'published'),
(799, 17, 3, 'cosmetic', 'Klairs All-Day Airy Sunscreen SPF50+', 'klairs-all-day-airy-sunscreen', 'güneş kremi', 'Tüm gün hafif güneş kremi.', '50.00', 'ml', 'face', 'morning', 'published'),
(800, 24, 3, 'cosmetic', 'Beauty of Joseon Ginseng Moist Sun Serum SPF50+', 'beauty-of-joseon-boj-ginseng-moist-sun-serum', 'güneş kremi', 'Ginseng nemlendirici güneş serumu.', '40.00', 'ml', 'face', 'morning', 'published'),
(801, 24, 1, 'cosmetic', 'Beauty of Joseon Light On Serum: Centella + Vita C', 'beauty-of-joseon-boj-light-on-serum-centella', 'serum', 'Centella + C vitamini aydınlatıcı serum.', '20.00', 'ml', 'face', 'both', 'published'),
(802, 24, 1, 'cosmetic', 'Beauty of Joseon Red Bean Refreshing Pore Mask', 'beauty-of-joseon-boj-red-bean-pore-mask', 'maske', 'Kırmızı fasulye gözenek maskesi.', '30.00', 'ml', 'face', 'evening', 'published'),
(803, 24, 1, 'cosmetic', 'Beauty of Joseon Glow Deep Serum: Rice + Alpha-Arbutin 60ml', 'beauty-of-joseon-boj-glow-deep-serum-60ml', 'serum', 'Pirinç + Arbutin serum. Büyük boy.', '30.00', 'ml', 'face', 'both', 'published'),
(804, 16, 1, 'cosmetic', 'Hada Labo Gokujyun Premium Hyaluronic Acid Cream', 'hada-labo-gokujyun-premium-cream', 'krem', 'Premium HA krem. 7 tip HA.', '50.00', 'ml', 'face', 'both', 'published'),
(805, 16, 1, 'cosmetic', 'Hada Labo Shirojyun Premium Brightening Essence', 'hada-labo-shirojyun-premium-essence', 'esans', 'Traneksamik asit aydınlatıcı esans.', '100.00', 'ml', 'face', 'both', 'published'),
(806, 16, 2, 'cosmetic', 'Hada Labo Gokujyun Oil Cleansing', 'hada-labo-gokujyun-oil-cleansing', 'temizleme yağı', 'HA temizleme yağı. Hafif doku.', '150.00', 'ml', 'face', 'evening', 'published'),
(807, 31, 5, 'cosmetic', 'Etude House SoonJung Lip Balm', 'etude-house-soonjung-lip-balm', 'dudak bakım', 'Hassas dudak balmı.', '4.00', 'ml', 'lips', 'both', 'published'),
(808, 31, 1, 'cosmetic', 'Etude House SoonJung Sleeping Pack', 'etude-house-soonjung-sleeping-pack', 'maske', 'Hassas cilt gece paketi.', '100.00', 'ml', 'face', 'evening', 'published'),
(809, 31, 1, 'cosmetic', 'Etude House SoonJung Toner Pad', 'etude-house-soonjung-toner-pad', 'peeling', 'Yatıştırıcı tonik pad.', '100.00', 'ml', 'face', 'evening', 'published'),
(810, 39, 2, 'cosmetic', 'Heimish All Clean White Clay Foam', 'heimish-all-clean-white-clay-foam', 'temizleyici', 'Beyaz kil köpük temizleyici.', '300.00', 'ml', 'face', 'both', 'published'),
(811, 39, 3, 'cosmetic', 'Heimish Artless Glow Base SPF50+', 'heimish-artless-glow-base-spf50', 'güneş kremi', 'Parlaklık bazı SPF50+.', '100.00', 'ml', 'face', 'morning', 'published'),
(812, 39, 1, 'cosmetic', 'Heimish Watermelon Soothing Gel Cream', 'heimish-watermelon-soothing-gel', 'nemlendirici', 'Karpuz yatıştırıcı jel krem.', '100.00', 'ml', 'face', 'both', 'published'),
(813, 42, 1, 'cosmetic', 'Neogen Real Vitamin C Serum', 'neogen-real-vitamin-c-serum-neogen', 'serum', 'Gerçek C vitamini serum. %22.', '50.00', 'ml', 'face', 'both', 'published'),
(814, 42, 1, 'cosmetic', 'Neogen Probiotics Youth Repair Cream', 'neogen-probiotics-youth-repair-cream', 'krem', 'Probiyotik gençlik krem.', '30.00', 'ml', 'face', 'both', 'published'),
(815, 42, 2, 'cosmetic', 'Neogen Canadian Clay Pore Cleanser', 'neogen-canadian-clay-pore-cleanser', 'temizleyici', 'Kanada kili gözenek temizleyici.', '473.00', 'ml', 'face', 'both', 'published'),
(816, 43, 1, 'cosmetic', 'Holika Holika Smooth Egg Skin Peeling Gel', 'holika-holika-smooth-egg-peeling-gel', 'peeling', 'Yumurta peeling jeli.', '100.00', 'ml', 'face', 'evening', 'published'),
(817, 43, 6, 'cosmetic', 'Holika Holika Good Cera Hand Cream', 'holika-holika-good-cera-hand-cream', 'el kremi', 'Ceramide el kremi.', '30.00', 'ml', 'hands', 'both', 'published'),
(818, 43, 1, 'cosmetic', 'Holika Holika Prime Youth Black Snail Repair Cream', 'holika-holika-black-snail-repair-cream', 'krem', 'Siyah salyangoz onarım kremi.', '75.00', 'ml', 'face', 'both', 'published'),
(819, 47, 3, 'cosmetic', 'Biore UV Perfect Protect Milk SPF50+', 'biore-uv-perfect-protect-milk', 'güneş kremi', 'Güçlü koruma güneş sütü.', '60.00', 'ml', 'face', 'morning', 'published'),
(820, 47, 2, 'cosmetic', 'Biore Cleansing Oil Cotton Facial Sheets', 'biore-cleansing-oil-cotton-sheets', 'micellar su', 'Yağlı temizleme mendilleri.', '500.00', 'ml', 'face', 'evening', 'published'),
(821, 47, 3, 'cosmetic', 'Biore UV Kids Pure Milk SPF50', 'biore-uv-kids-pure-milk', 'güneş kremi', 'Çocuk güneş sütü. Nazik formül.', '200.00', 'ml', 'face', 'morning', 'published'),
(822, 44, 1, 'cosmetic', 'Senka Perfect Aqua Rich Extra Moist Facial Cream', 'senka-perfect-aqua-rich-cream', 'krem', 'Aqua zengin nemlendirici krem.', '75.00', 'ml', 'face', 'both', 'published'),
(823, 44, 2, 'cosmetic', 'Senka All Clear Micellar Water', 'senka-all-clear-micellar-water', 'micellar su', 'Micellar temizleme suyu.', '500.00', 'ml', 'face', 'evening', 'published'),
(824, 44, 1, 'cosmetic', 'Senka White Beauty Serum in CC', 'senka-white-beauty-cc-serum', 'serum', 'CC aydınlatıcı serum. Renk düzeltici.', '20.00', 'ml', 'face', 'both', 'published'),
(825, 45, 2, 'cosmetic', 'Melano CC Anti-Spot Whitening Face Wash', 'melano-cc-anti-spot-whitening-wash', 'temizleyici', 'Leke karşıtı temizleyici. C vitamini.', '200.00', 'ml', 'face', 'both', 'published'),
(826, 45, 1, 'cosmetic', 'Melano CC Anti-Spot Moisture Cream', 'melano-cc-anti-spot-moisture-cream', 'krem', 'C vitamini leke nemlendirici krem.', '30.00', 'ml', 'face', 'both', 'published'),
(827, 45, 1, 'cosmetic', 'Melano CC Anti-Spot White Mist', 'melano-cc-anti-spot-white-mist', 'mist', 'C vitamini aydınlatıcı mist.', '150.00', 'ml', 'face', 'both', 'published'),
(828, 71, 1, 'cosmetic', 'Noreva Exfoliac NC Gel', 'noreva-exfoliac-nc-gel', 'nemlendirici', 'Akne bakım jeli. NC kompleks.', '100.00', 'ml', 'face', 'both', 'published'),
(829, 71, 1, 'cosmetic', 'Noreva Sensidiane AR Intensive Cream', 'noreva-sensidiane-ar-cream', 'krem', 'Kızarıklık yoğun bakım kremi.', '50.00', 'ml', 'face', 'both', 'published'),
(830, 71, 1, 'cosmetic', 'Noreva Noveane Premium Multi-Corrective Day Cream', 'noreva-noveane-premium-day-cream', 'gündüz kremi', 'Çoklu düzeltici gündüz kremi.', '50.00', 'ml', 'face', 'morning', 'published'),
(831, 72, 2, 'cosmetic', 'ACM Novophane Ultra-Nourishing Shampoo', 'acm-novophane-ultra-shampoo', 'temizleyici', 'Ultra besleyici şampuan.', '500.00', 'ml', 'face', 'both', 'published'),
(832, 72, 1, 'cosmetic', 'ACM Trigopax Protective Soothing Skincare', 'acm-trigopax-protective-soothing', 'balsam', 'Koruyucu yatıştırıcı bakım. Kıvrım bölgeleri.', '30.00', 'ml', 'face_body', 'both', 'published'),
(833, 72, 1, 'cosmetic', 'ACM Sebionex Hydra Repair Cream', 'acm-sebionex-hydra-repair', 'krem', 'Akne sonrası onarım kremi.', '75.00', 'ml', 'face', 'both', 'published'),
(834, 70, 1, 'cosmetic', 'Lierac Premium The Supreme Mask', 'lierac-premium-supreme-mask', 'maske', 'Lüks anti-aging maske.', '75.00', 'ml', 'face', 'evening', 'published'),
(835, 70, 1, 'cosmetic', 'Lierac Hydragenist Moisturizing Cream-Gel', 'lierac-hydragenist-cream-gel', 'nemlendirici', 'Oksijenlendirici jel krem.', '75.00', 'ml', 'face', 'both', 'published'),
(836, 73, 3, 'cosmetic', 'Altruist Invisible Fluid SPF50', 'altruist-invisible-fluid-spf50', 'güneş kremi', 'Görünmez sıvı güneş koruyucu.', '200.00', 'ml', 'face', 'morning', 'published'),
(837, 73, 3, 'cosmetic', 'Altruist Dry Touch Sunscreen SPF50', 'altruist-dry-touch-sunscreen-spf50', 'güneş kremi', 'Kuru dokunuş güneş kremi.', '60.00', 'ml', 'face', 'morning', 'published'),
(838, 74, 1, 'cosmetic', 'Geek & Gorgeous Jelly Joker 6% Mandelic + 1% Salicylic', 'geek-gorgeous-jelly-joker-mandelic-salicylic', 'peeling', 'Jöle eksfolyan. Mandelik + Salisilik.', '50.00', 'ml', 'face', 'evening', 'published'),
(839, 74, 1, 'cosmetic', 'Geek & Gorgeous 101 Liquid Gold 5% Glycolic Toner', 'geek-gorgeous-101-liquid-gold-glycolic', 'tonik', 'Glikolik asit %5 tonik. Altın eksfoliasyon.', '300.00', 'ml', 'face', 'both', 'published'),
(840, 74, 1, 'cosmetic', 'Geek & Gorgeous Calm Down 100% Niacinamide Powder', 'geek-gorgeous-calm-down-niacinamide-powder', 'serum', 'Saf niacinamide tozu. Özel karıştırma.', '30.00', 'ml', 'face', 'both', 'published'),
(841, 75, 1, 'cosmetic', 'Peter Thomas Roth Instant FIRMx Temporary Face Tightener', 'peter-thomas-roth-instant-firmx-face-tightener', 'krem', 'Anında sıkılaştırıcı. Geçici etki.', '30.00', 'ml', 'face', 'both', 'published'),
(842, 75, 1, 'cosmetic', 'Peter Thomas Roth Potent-C Moisturizer', 'peter-thomas-roth-potent-c-moisturizer', 'krem', 'C vitamini nemlendirici krem.', '50.00', 'ml', 'face', 'both', 'published'),
(843, 75, 1, 'cosmetic', 'Peter Thomas Roth Pumpkin Enzyme Mask', 'peter-thomas-roth-pumpkin-enzyme-mask', 'maske', 'Balkabağı enzim maskesi. Parlak cilt.', '30.00', 'ml', 'face', 'evening', 'published'),
(844, 22, 2, 'cosmetic', 'Drunk Elephant Beste No. 9 Jelly Cleanser', 'drunk-elephant-beste-no9-jelly-cleanser', 'temizleyici', 'Jöle temizleyici. pH 6.1.', '250.00', 'ml', 'face', 'both', 'published'),
(845, 22, 1, 'cosmetic', 'Drunk Elephant Lala Retro Whipped Cream', 'drunk-elephant-lala-retro-whipped-cream', 'krem', 'Çırpılmış retro krem. 6 yağ karışımı.', '75.00', 'ml', 'face', 'both', 'published'),
(846, 22, 1, 'cosmetic', 'Drunk Elephant C-Firma Fresh Vitamin C Day Serum', 'drunk-elephant-c-firma-fresh-vitamin-c', 'serum', 'Taze C vitamini %15. Günlük serum.', '50.00', 'ml', 'face', 'both', 'published'),
(847, 22, 1, 'cosmetic', 'Drunk Elephant F-Balm Electrolyte Waterfacial', 'drunk-elephant-f-balm-electrolyte-mask', 'maske', 'Elektrolit su maskesi. Gece.', '30.00', 'ml', 'face', 'evening', 'published'),
(848, 22, 1, 'cosmetic', 'Drunk Elephant A-Passioni Retinol Cream', 'drunk-elephant-a-passioni-retinol-cream', 'gece kremi', 'Retinol %1 gece kremi. Vegan.', '75.00', 'ml', 'face', 'evening', 'published'),
(849, 22, 3, 'cosmetic', 'Drunk Elephant Umbra Sheer Physical Daily Defense SPF30', 'drunk-elephant-umbra-sheer-physical-spf30', 'güneş kremi', 'Fiziksel güneş koruyucu SPF30.', '60.00', 'ml', 'face', 'morning', 'published'),
(850, 23, 1, 'cosmetic', 'Isntree Cica Relief Cream', 'isntree-cica-relief-cream', 'krem', 'Cica rahatlatma kremi.', '50.00', 'ml', 'face', 'both', 'published'),
(851, 23, 3, 'cosmetic', 'Isntree Onion Newpair Sunscreen SPF40', 'isntree-onion-newpair-sunscreen', 'güneş kremi', 'Soğan güneş kremi. İz + koruma.', '50.00', 'ml', 'face', 'morning', 'published'),
(852, 23, 1, 'cosmetic', 'Isntree Sensitive Balancing Moisture Cream', 'isntree-sensitive-balancing-moisture', 'krem', 'Hassas denge nemlendirici.', '75.00', 'ml', 'face', 'both', 'published'),
(853, 23, 1, 'cosmetic', 'Isntree Yam Root Vitalizing Cream', 'isntree-yam-root-vitalizing-cream', 'krem', 'Yam kökü canlandırıcı krem.', '75.00', 'ml', 'face', 'both', 'published'),
(854, 18, 1, 'cosmetic', 'Purito Oat-In Calming Gel Cream', 'purito-oat-in-calming-gel-cream', 'nemlendirici', 'Yulaf yatıştırıcı jel krem.', '30.00', 'ml', 'face', 'both', 'published'),
(855, 18, 1, 'cosmetic', 'Purito Dermide Cica Barrier Sleeping Pack', 'purito-dermide-cica-sleeping-pack', 'maske', 'Cica bariyer gece paketi.', '75.00', 'ml', 'face', 'evening', 'published'),
(856, 18, 1, 'cosmetic', 'Purito B5 Panthenol Re-Barrier Cream', 'purito-b5-panthenol-re-barrier', 'krem', 'B5 panthenol bariyer kremi.', '75.00', 'ml', 'face', 'both', 'published'),
(857, 14, 1, 'cosmetic', 'Uriage Hyseac Bi-Stick', 'uriage-hyseac-bi-stick', 'balsam', 'Çift etkili akne stick.', '100.00', 'ml', 'face_body', 'both', 'published'),
(858, 14, 1, 'cosmetic', 'Uriage Roseliane Anti-Redness Cream SPF30', 'uriage-roseliane-anti-redness-spf30', 'gündüz kremi', 'Kızarıklık karşıtı SPF30.', '50.00', 'ml', 'face', 'morning', 'published'),
(859, 14, 1, 'cosmetic', 'Uriage Eau Thermale Night Mask', 'uriage-eau-thermale-night-mask', 'maske', 'Termal su gece maskesi.', '100.00', 'ml', 'face', 'evening', 'published'),
(860, 14, 4, 'cosmetic', 'Uriage Isodense Firming Eye Contour Care', 'uriage-isodense-firming-eye', 'göz kremi', 'Sıkılaştırıcı göz çevresi bakımı.', '20.00', 'ml', 'eye', 'both', 'published'),
(861, 15, 1, 'cosmetic', 'Ducray Keracnyl Serum', 'ducray-keracnyl-serum', 'serum', 'Akne serumu. Glikolik asit.', '50.00', 'ml', 'face', 'both', 'published'),
(862, 15, 3, 'cosmetic', 'Ducray Melascreen UV Rich Cream SPF50+', 'ducray-melascreen-uv-rich-spf50', 'güneş kremi', 'Leke karşıtı güneş kremi.', '60.00', 'ml', 'face', 'morning', 'published'),
(863, 15, 2, 'cosmetic', 'Ducray Ictyane Micellar Water', 'ducray-ictyane-micellar-water', 'micellar su', 'Kuru ciltler micellar su.', '400.00', 'ml', 'face', 'evening', 'published'),
(864, 6, 1, 'cosmetic', 'SVR Sebiaclear Micro-Peel', 'svr-sebiaclear-micro-peel', 'peeling', 'Mikro peeling. Glukonolakton + Salisilik.', '30.00', 'ml', 'face', 'evening', 'published'),
(865, 6, 1, 'cosmetic', 'SVR Ampoule Lift Firming Ampoule', 'svr-ampoule-lift-firming', 'ampul', 'Sıkılaştırıcı ampul. Kollajen.', '30.00', 'ml', 'face', 'evening', 'published'),
(866, 6, 3, 'cosmetic', 'SVR Sun Secure Easy Stick SPF50+', 'svr-sun-secure-easy-stick', 'güneş stick', 'Kolay güneş stick. SPF50+.', '20.00', 'g', 'face', 'morning', 'published'),
(867, 5, 5, 'cosmetic', 'Avene Eau Thermale Lip Balm', 'avene-eau-thermale-lip-balm', 'dudak bakım', 'Termal su dudak balmı.', '10.00', 'ml', 'lips', 'both', 'published'),
(868, 5, 1, 'cosmetic', 'Avene PhysioLift Smoothing Night Balm', 'avene-physiolift-smoothing-night', 'gece kremi', 'Pürüzsüzleştirici gece balmı. Retinaldehit.', '75.00', 'ml', 'face', 'evening', 'published'),
(869, 5, 2, 'cosmetic', 'Avene Cleanance Micellar Water', 'avene-cleanance-micellar-water-av', 'micellar su', 'Akne micellar su.', '400.00', 'ml', 'face', 'evening', 'published'),
(870, 5, 1, 'cosmetic', 'Avene Tolerance Control Soothing Skin Recovery Balm', 'avene-tolerance-control-recovery-balm', 'balsam', 'Kontrollü tolerans onarım balmı.', '30.00', 'ml', 'face_body', 'both', 'published'),
(871, 68, 1, 'cosmetic', 'Embryolisse Hydra-Cream with Orange Extract', 'embryolisse-hydra-cream-orange', 'krem', 'Portakal özlü nemlendirici.', '30.00', 'ml', 'face', 'both', 'published'),
(872, 68, 4, 'cosmetic', 'Embryolisse Anti-Age Eye Care', 'embryolisse-anti-age-eye-care', 'göz kremi', 'Anti-aging göz bakımı.', '20.00', 'ml', 'eye', 'both', 'published'),
(873, 68, 1, 'cosmetic', 'Embryolisse Compresse Eye Mask', 'embryolisse-compresse-eye-mask', 'maske', 'Göz kompres maskesi.', '100.00', 'ml', 'face', 'evening', 'published'),
(874, 57, 1, 'cosmetic', 'Tatcha The Essence Plumping Skin Softener', 'tatcha-essence-plumping-skin-softener', 'esans', 'Dolgunlaştırıcı cilt yumuşatıcı.', '150.00', 'ml', 'face', 'both', 'published'),
(875, 57, 1, 'cosmetic', 'Tatcha Indigo Soothing Recovery Cream', 'tatcha-indigo-soothing-recovery', 'krem', 'İndigo yatıştırıcı onarım kremi.', '75.00', 'ml', 'face', 'both', 'published'),
(876, 58, 1, 'cosmetic', 'Fresh Vitamin Nectar Moisture Glow Face Cream', 'fresh-vitamin-nectar-glow-cream', 'krem', 'Vitamin nektar parlaklık kremi.', '75.00', 'ml', 'face', 'both', 'published'),
(877, 58, 5, 'cosmetic', 'Fresh Sugar Lip Treatment SPF15', 'fresh-sugar-lip-treatment-spf15', 'dudak bakım', 'Şeker dudak bakımı SPF15.', '10.00', 'ml', 'lips', 'both', 'published'),
(878, 58, 1, 'cosmetic', 'Fresh Black Tea Kombucha Facial Treatment Essence', 'fresh-black-tea-kombucha-essence', 'esans', 'Kombuça yüz bakım esansı.', '100.00', 'ml', 'face', 'both', 'published'),
(879, 53, 1, 'cosmetic', 'SK-II Facial Treatment Clear Lotion', 'sk-ii-facial-treatment-clear-lotion', 'tonik', 'Arındırıcı losyon. AHA + Pitera.', '300.00', 'ml', 'face', 'both', 'published'),
(880, 53, 1, 'cosmetic', 'SK-II Facial Treatment Mask', 'sk-ii-facial-treatment-mask', 'maske', 'Pitera yüz maskesi. Yoğun bakım.', '75.00', 'ml', 'face', 'evening', 'published'),
(881, 37, 1, 'cosmetic', 'Medicube Triple Cica Ampoule', 'medicube-triple-cica-ampoule', 'ampul', 'Üçlü cica ampulü.', '30.00', 'ml', 'face', 'evening', 'published'),
(882, 37, 1, 'cosmetic', 'Medicube Pore Tightening Serum', 'medicube-pore-tightening-serum-mc', 'serum', 'Gözenek sıkılaştırıcı serum.', '20.00', 'ml', 'face', 'both', 'published'),
(883, 37, 1, 'cosmetic', 'Medicube Zero Sebum Peeling Toner', 'medicube-zero-sebum-peeling-toner', 'tonik', 'Sıfır sebum peeling toneri.', '250.00', 'ml', 'face', 'both', 'published')
ON CONFLICT (product_slug) DO NOTHING;

SELECT setval('products_product_id_seq', 883);
