-- ============================================
-- BATCH 4 Part 2: Products 401-700
-- ============================================
INSERT INTO products (product_id, brand_id, category_id, domain_type, product_name, product_slug, product_type_label, short_description, net_content_value, net_content_unit, target_area, usage_time_hint, status) VALUES
(401, 63, 6, 'cosmetic', 'Sebamed Moisturizing Body Lotion', 'sebamed-moisturizing-body-lotion-sm', 'vücut losyonu', 'pH 5.5 vücut losyonu.', '200.00', 'ml', 'body', 'both', 'published'),
(402, 63, 2, 'cosmetic', 'Sebamed Clear Face Antibacterial Cleansing Foam', 'sebamed-clear-face-antibacterial-foam', 'temizleyici', 'Antibakteriyel temizleme köpüğü.', '500.00', 'ml', 'face', 'both', 'published'),
(403, 63, 1, 'cosmetic', 'Sebamed Anti-Dry Day Defence Cream SPF15', 'sebamed-anti-dry-day-defence', 'gündüz kremi', 'Kuru ciltler gündüz bakımı SPF15.', '50.00', 'ml', 'face', 'morning', 'published'),
(404, 63, 4, 'cosmetic', 'Sebamed Anti-Ageing Q10 Lifting Eye Cream', 'sebamed-anti-ageing-q10-eye', 'göz kremi', 'Q10 göz çevresi kremi. Anti-aging.', '20.00', 'ml', 'eye', 'both', 'published'),
(405, 67, 1, 'cosmetic', 'Caudalie Vinoperfect Radiance Serum', 'caudalie-vinoperfect-radiance-serum', 'serum', 'Viniferine leke serum. Doğal aydınlatıcı.', '50.00', 'ml', 'face', 'both', 'published'),
(406, 67, 1, 'cosmetic', 'Caudalie Vinosource-Hydra S.O.S Thirst-Quenching Serum', 'caudalie-vinosource-sos-serum', 'serum', 'Organik üzüm suyu nemlendirici serum.', '20.00', 'ml', 'face', 'both', 'published'),
(407, 67, 2, 'cosmetic', 'Caudalie Vinoclean Micellar Cleansing Water', 'caudalie-vinoclean-micellar', 'micellar su', 'Üzüm suyu micellar temizleyici.', '400.00', 'ml', 'face', 'evening', 'published'),
(408, 67, 1, 'cosmetic', 'Caudalie Resveratrol-Lift Firming Night Cream', 'caudalie-resveratrol-lift-night-cream', 'gece kremi', 'Resveratrol sıkılaştırıcı gece kremi.', '75.00', 'ml', 'face', 'evening', 'published'),
(409, 67, 4, 'cosmetic', 'Caudalie Resveratrol-Lift Eye Lifting Balm', 'caudalie-resveratrol-eye-balm', 'göz kremi', 'Resveratrol göz balmı. Sıkılaştırma.', '10.00', 'ml', 'eye', 'both', 'published'),
(410, 67, 2, 'cosmetic', 'Caudalie Vinopure Purifying Gel Cleanser', 'caudalie-vinopure-gel-cleanser', 'temizleyici', 'Arındırıcı jel temizleyici. BHA + Salisilik.', '400.00', 'ml', 'face', 'both', 'published'),
(411, 67, 1, 'cosmetic', 'Caudalie Premier Cru The Cream', 'caudalie-premier-cru-cream', 'krem', 'Lüks anti-aging krem. Resveratrol + HA.', '50.00', 'ml', 'face', 'both', 'published'),
(412, 67, 3, 'cosmetic', 'Caudalie Soleil Divin Anti-Ageing SPF50', 'caudalie-soleil-divin-spf50', 'güneş kremi', 'Anti-aging güneş bakımı. Üzüm polifenol.', '60.00', 'ml', 'face', 'morning', 'published'),
(413, 68, 1, 'cosmetic', 'Embryolisse Lait-Crème Concentré', 'embryolisse-lait-creme-concentre', 'krem', 'Süt krem konsantresi. Paris''in #1 nemlendirici.', '50.00', 'ml', 'face', 'both', 'published'),
(414, 68, 1, 'cosmetic', 'Embryolisse Filaderme Emulsion', 'embryolisse-filaderme-emulsion', 'nemlendirici', 'Kuru ciltler emülsiyonu. Shea + Avokado.', '100.00', 'ml', 'face', 'both', 'published'),
(415, 68, 1, 'cosmetic', 'Embryolisse Radiant Complexion Serum', 'embryolisse-radiant-complexion-serum', 'serum', 'Parlaklık serumu. C vitamini.', '50.00', 'ml', 'face', 'both', 'published'),
(416, 68, 2, 'cosmetic', 'Embryolisse Micellar Cleansing Milk', 'embryolisse-micellar-cleansing-milk', 'micellar su', 'Micellar temizleme sütü. Nazik.', '200.00', 'ml', 'face', 'evening', 'published'),
(417, 69, 4, 'cosmetic', 'Filorga Time-Filler Eyes', 'filorga-time-filler-eyes', 'göz kremi', 'Kırışıklık doldurucu göz kremi. NCEF.', '10.00', 'ml', 'eye', 'both', 'published'),
(418, 69, 1, 'cosmetic', 'Filorga NCEF-Reverse Mat Cream', 'filorga-ncef-reverse-mat-cream', 'krem', 'Anti-aging mat krem. NCEF + HA.', '30.00', 'ml', 'face', 'both', 'published'),
(419, 69, 4, 'cosmetic', 'Filorga Optim-Eyes Eye Contour Cream', 'filorga-optim-eyes-contour', 'göz kremi', 'Göz çevresi bakım. Morluk + Şişlik + Kırışıklık.', '10.00', 'ml', 'eye', 'both', 'published'),
(420, 69, 1, 'cosmetic', 'Filorga Hydra-Hyal Hydrating Plumping Serum', 'filorga-hydra-hyal-plumping-serum', 'serum', '5 tip HA dolgunlaştırıcı serum.', '30.00', 'ml', 'face', 'both', 'published'),
(421, 69, 1, 'cosmetic', 'Filorga Time-Filler Intensive Serum', 'filorga-time-filler-intensive-serum', 'serum', 'Yoğun kırışıklık serumu. Botoks benzeri peptit.', '50.00', 'ml', 'face', 'both', 'published'),
(422, 69, 1, 'cosmetic', 'Filorga Pigment-Perfect Dark Spot Corrector', 'filorga-pigment-perfect-corrector', 'serum', 'Leke düzeltici serum. Glabridin + C vitamini.', '20.00', 'ml', 'face', 'both', 'published'),
(423, 74, 1, 'cosmetic', 'Geek & Gorgeous C-Glow 15% Vitamin C Serum', 'geek-gorgeous-c-glow-15-vitamin-c', 'serum', 'C vitamini %15 + Ferulic. Aydınlatıcı serum.', '30.00', 'ml', 'face', 'both', 'published'),
(424, 74, 1, 'cosmetic', 'Geek & Gorgeous A-Game 5 0.05% Retinal Serum', 'geek-gorgeous-a-game-5-retinal', 'serum', 'Retinal %0.05 serum. Hassas ciltler anti-aging.', '20.00', 'ml', 'face', 'both', 'published'),
(425, 74, 1, 'cosmetic', 'Geek & Gorgeous A-Game 10 0.1% Retinal Serum', 'geek-gorgeous-a-game-10-retinal', 'serum', 'Retinal %0.1 serum. İleri seviye.', '20.00', 'ml', 'face', 'both', 'published'),
(426, 74, 1, 'cosmetic', 'Geek & Gorgeous Cheer Up 6% Mandelic Acid + BHA', 'geek-gorgeous-cheer-up-mandelic-bha', 'peeling', 'Mandelik asit %6 + BHA. Nazik peeling.', '20.00', 'ml', 'face', 'evening', 'published'),
(427, 74, 1, 'cosmetic', 'Geek & Gorgeous aPAD 10% Azelaic Acid', 'geek-gorgeous-apad-10-azelaic', 'serum', 'Azelaik asit %10 serum. Kızarıklık + Ton.', '20.00', 'ml', 'face', 'both', 'published'),
(428, 74, 2, 'cosmetic', 'Geek & Gorgeous Mighty Melt Cleansing Balm', 'geek-gorgeous-mighty-melt-cleansing-balm', 'temizleme yağı', 'Temizleme balmı. Jojoba + Squalane.', '200.00', 'ml', 'face', 'evening', 'published'),
(429, 74, 1, 'cosmetic', 'Geek & Gorgeous Stress Less 2% BHA Serum', 'geek-gorgeous-stress-less-bha-serum', 'serum', 'BHA %2 serum. Gözenek + Siyah nokta.', '30.00', 'ml', 'face', 'both', 'published'),
(430, 73, 3, 'cosmetic', 'Altruist Dermatologist Sunscreen SPF50', 'altruist-dermatologist-sunscreen-spf50', 'güneş kremi', 'Dermatolog güneş kremi. Yüksek koruma, düşük fiyat.', '40.00', 'ml', 'face', 'morning', 'published'),
(431, 73, 3, 'cosmetic', 'Altruist Dermatologist Sunscreen SPF30', 'altruist-dermatologist-sunscreen-spf30', 'güneş kremi', 'SPF30 güneş koruyucu. Günlük kullanım.', '50.00', 'ml', 'face', 'morning', 'published'),
(432, 73, 3, 'cosmetic', 'Altruist Face Fluid SPF50', 'altruist-face-fluid-spf50', 'güneş kremi', 'Yüz sıvısı SPF50. Mat bitiş.', '100.00', 'ml', 'face', 'morning', 'published'),
(433, 73, 3, 'cosmetic', 'Altruist Anti-Redness & Pigmentation SPF50', 'altruist-anti-redness-spf50', 'güneş kremi', 'Kızarıklık ve leke karşıtı güneş koruyucu.', '40.00', 'ml', 'face', 'morning', 'published'),
(434, 75, 1, 'cosmetic', 'Peter Thomas Roth Water Drench Hyaluronic Cloud Cream', 'peter-thomas-roth-water-drench-cloud-cream', 'krem', 'HA bulut krem. %30 HA kompleks.', '75.00', 'ml', 'face', 'both', 'published'),
(435, 75, 1, 'cosmetic', 'Peter Thomas Roth Potent-C Power Serum', 'peter-thomas-roth-potent-c-power-serum', 'serum', 'THD C vitamini %20 serum. Ultra stabil.', '50.00', 'ml', 'face', 'both', 'published'),
(436, 75, 1, 'cosmetic', 'Peter Thomas Roth Retinol Fusion PM Night Serum', 'peter-thomas-roth-retinol-fusion-pm-serum', 'serum', 'Retinol mikrokapsül gece serumu.', '50.00', 'ml', 'face', 'both', 'published'),
(437, 75, 1, 'cosmetic', 'Peter Thomas Roth FIRMx Collagen Serum', 'peter-thomas-roth-firmx-collagen-serum', 'serum', 'Kollajen sıkılaştırıcı serum.', '30.00', 'ml', 'face', 'both', 'published'),
(438, 75, 1, 'cosmetic', 'Peter Thomas Roth Cucumber Gel Mask', 'peter-thomas-roth-cucumber-gel-mask', 'maske', 'Salatalık jel maske. Yatıştırıcı + serinletici.', '30.00', 'ml', 'face', 'evening', 'published'),
(439, 75, 1, 'cosmetic', 'Peter Thomas Roth Max Complexion Correction Pads', 'peter-thomas-roth-max-complexion-pads', 'peeling', 'AHA/BHA peeling pad. Gözenek temizleyici.', '100.00', 'ml', 'face', 'evening', 'published'),
(440, 8, 1, 'cosmetic', 'Neutrogena Hydro Boost Water Gel', 'neutrogena-hydro-boost-water-gel-new', 'nemlendirici', 'Su jel nemlendirici. HA bazlı.', '100.00', 'ml', 'face', 'both', 'published'),
(441, 8, 4, 'cosmetic', 'Neutrogena Hydro Boost Eye Cream', 'neutrogena-hydro-boost-eye-cream', 'göz kremi', 'HA göz kremi. Nemlendirici.', '20.00', 'ml', 'eye', 'both', 'published'),
(442, 8, 1, 'cosmetic', 'Neutrogena Retinol Boost Day Cream SPF15', 'neutrogena-retinol-boost-day-spf15', 'gündüz kremi', 'Retinol gündüz kremi SPF15.', '50.00', 'ml', 'face', 'morning', 'published'),
(443, 8, 1, 'cosmetic', 'Neutrogena Retinol Boost Night Cream', 'neutrogena-retinol-boost-night', 'gece kremi', 'Retinol gece kremi. Anti-aging.', '50.00', 'ml', 'face', 'evening', 'published'),
(444, 8, 2, 'cosmetic', 'Neutrogena Clear & Defend Facial Wash', 'neutrogena-clear-defend-facial-wash', 'temizleyici', 'Akne temizleyici. Salisilik asit %2.', '250.00', 'ml', 'face', 'both', 'published'),
(445, 8, 6, 'cosmetic', 'Neutrogena Hydro Boost Body Gel Cream', 'neutrogena-hydro-boost-body-gel-cream', 'vücut kremi', 'HA vücut jel krem. Nemlendirici.', '150.00', 'ml', 'body', 'both', 'published'),
(446, 8, 3, 'cosmetic', 'Neutrogena Ultra Sheer Face Mist SPF50', 'neutrogena-ultra-sheer-face-mist-spf50', 'güneş kremi', 'Ultra hafif yüz mist SPF50.', '100.00', 'ml', 'face', 'morning', 'published'),
(447, 8, 1, 'cosmetic', 'Neutrogena Bright Boost Illuminating Serum', 'neutrogena-bright-boost-illuminating-serum', 'serum', 'Neoglucosamine aydınlatıcı serum.', '50.00', 'ml', 'face', 'both', 'published'),
(448, 8, 6, 'cosmetic', 'Neutrogena Norwegian Formula Hand Cream', 'neutrogena-norwegian-hand-cream', 'el kremi', 'Norveç formülü el kremi. Yoğun nemlendirme.', '75.00', 'ml', 'hands', 'both', 'published'),
(449, 8, 2, 'cosmetic', 'Neutrogena Visibly Clear Pink Grapefruit Cleanser', 'neutrogena-visibly-clear-grapefruit', 'temizleyici', 'Greyfurt temizleyici. Akne bakımı.', '473.00', 'ml', 'face', 'both', 'published'),
(450, 10, 1, 'cosmetic', 'Nuxe Huile Prodigieuse', 'nuxe-huile-prodigieuse', 'yüz yağı', 'Mucize kuru yağ. Yüz + Vücut + Saç.', '50.00', 'ml', 'face', 'evening', 'published'),
(451, 10, 1, 'cosmetic', 'Nuxe Creme Fraiche de Beaute 48H Moisturizing Cream', 'nuxe-creme-fraiche-48h', 'krem', '48 saat nemlendirici krem. Bitki sütleri.', '30.00', 'ml', 'face', 'both', 'published'),
(452, 10, 5, 'cosmetic', 'Nuxe Reve de Miel Lip Balm', 'nuxe-reve-de-miel-lip-balm', 'dudak bakım', 'Bal dudak balmı. Kuru ve çatlak dudaklar.', '10.00', 'ml', 'lips', 'both', 'published'),
(453, 10, 4, 'cosmetic', 'Nuxe Merveillance LIFT Firming Eye Cream', 'nuxe-merveillance-lift-eye', 'göz kremi', 'Sıkılaştırıcı göz kremi. Retinol benzeri.', '20.00', 'ml', 'eye', 'both', 'published'),
(454, 10, 1, 'cosmetic', 'Nuxe Super Serum 10 Anti-Aging Concentrate', 'nuxe-super-serum-10', 'serum', '10 aktifli anti-aging konsantre. HA + Niacinamide.', '50.00', 'ml', 'face', 'both', 'published'),
(455, 10, 1, 'cosmetic', 'Nuxe Creme Prodigieuse Boost Multi-Purpose Gel-Cream', 'nuxe-creme-prodigieuse-boost', 'nemlendirici', 'Antioksidan jel krem. Jasmine.', '75.00', 'ml', 'face', 'both', 'published'),
(456, 10, 2, 'cosmetic', 'Nuxe Very Rose 3-in-1 Soothing Micellar Water', 'nuxe-very-rose-micellar', 'micellar su', 'Gül suyu micellar temizleyici.', '400.00', 'ml', 'face', 'evening', 'published'),
(457, 10, 1, 'cosmetic', 'Nuxe Huile Prodigieuse Neroli', 'nuxe-huile-prodigieuse-neroli', 'yüz yağı', 'Neroli çiçeği kuru yağ.', '20.00', 'ml', 'face', 'evening', 'published'),
(458, 14, 1, 'cosmetic', 'Uriage Eau Thermale Water Cream', 'uriage-eau-thermale-water-cream', 'krem', 'Termal su krem. Nemlendirici + Koruyucu.', '50.00', 'ml', 'face', 'both', 'published'),
(459, 14, 1, 'cosmetic', 'Uriage Bariederm Cica-Cream', 'uriage-bariederm-cica-cream', 'balsam', 'Onarıcı cica krem. Bakır + Çinko.', '30.00', 'ml', 'face_body', 'both', 'published'),
(460, 14, 1, 'cosmetic', 'Uriage Hyseac 3-Regul Global Skin-Care', 'uriage-hyseac-3-regul', 'krem', 'Akne bakım kremi. Yağ kontrolü.', '75.00', 'ml', 'face', 'both', 'published'),
(461, 14, 1, 'cosmetic', 'Uriage Depiderm Anti-Brown Spot Serum', 'uriage-depiderm-anti-spot-serum', 'serum', 'Leke karşıtı serum. Aktif C vitamini.', '20.00', 'ml', 'face', 'both', 'published'),
(462, 14, 6, 'cosmetic', 'Uriage Xemose Lipid-Replenishing Cream', 'uriage-xemose-lipid-cream', 'vücut kremi', 'Lipid doldurucu atopik krem.', '150.00', 'ml', 'body', 'both', 'published'),
(463, 14, 1, 'cosmetic', 'Uriage Age Protect Multi-Action Cream SPF30', 'uriage-age-protect-cream-spf30', 'gündüz kremi', 'Anti-aging SPF30. Retinol + C vitamini.', '30.00', 'ml', 'face', 'morning', 'published'),
(464, 14, 3, 'cosmetic', 'Uriage Bariesun Mat Fluid SPF50+', 'uriage-bariesun-mat-fluid-spf50', 'güneş kremi', 'Mat sıvı güneş koruyucu. Yağlı ciltler.', '50.00', 'ml', 'face', 'morning', 'published'),
(465, 14, 2, 'cosmetic', 'Uriage Eau Thermale Micellar Water', 'uriage-eau-thermale-micellar', 'micellar su', 'Termal su micellar temizleyici.', '200.00', 'ml', 'face', 'evening', 'published'),
(466, 15, 1, 'cosmetic', 'Ducray Keracnyl PP Anti-Blemish Cream', 'ducray-keracnyl-pp-cream', 'krem', 'Akne karşıtı krem. Myrtacine.', '50.00', 'ml', 'face', 'both', 'published'),
(467, 15, 2, 'cosmetic', 'Ducray Keracnyl Foaming Gel', 'ducray-keracnyl-foaming-gel', 'temizleyici', 'Akne temizleme jeli.', '500.00', 'ml', 'face', 'both', 'published'),
(468, 15, 1, 'cosmetic', 'Ducray Melascreen Depigmenting Intense Care', 'ducray-melascreen-depigmenting', 'serum', 'Yoğun leke bakımı. Azelaic + Glycolic acid.', '30.00', 'ml', 'face', 'both', 'published'),
(469, 15, 1, 'cosmetic', 'Ducray Ictyane HD Emollient Cream', 'ducray-ictyane-hd-emollient', 'krem', 'Kuru ciltler emolyan krem.', '50.00', 'ml', 'face', 'both', 'published'),
(470, 15, 2, 'cosmetic', 'Ducray Anacaps Reactiv Hair Supplement', 'ducray-anacaps-reactiv-hair', 'temizleyici', 'Saç dökülmesi destekleyici. Biotin + Çinko.', '150.00', 'ml', 'face', 'both', 'published'),
(471, 15, 2, 'cosmetic', 'Ducray Squanorm Anti-Dandruff Shampoo', 'ducray-squanorm-anti-dandruff', 'temizleyici', 'Kepek karşıtı şampuan. Keluamid.', '300.00', 'ml', 'face', 'both', 'published'),
(472, 19, 1, 'cosmetic', 'Some By Mi AHA BHA PHA 30 Days Miracle Serum', 'some-by-mi-aha-bha-pha-miracle-serum', 'serum', 'AHA+BHA+PHA mucize serum. 3 asitli.', '30.00', 'ml', 'face', 'both', 'published'),
(473, 19, 1, 'cosmetic', 'Some By Mi AHA BHA PHA 30 Days Miracle Cream', 'some-by-mi-aha-bha-pha-miracle-cream', 'krem', '30 gün mucize krem. Akne bakım.', '50.00', 'ml', 'face', 'both', 'published'),
(474, 19, 1, 'cosmetic', 'Some By Mi Galactomyces Pure Vitamin C Glow Serum', 'some-by-mi-galactomyces-vitamin-c-serum', 'serum', 'Galactomyces + C vitamini parlaklık serumu.', '20.00', 'ml', 'face', 'both', 'published'),
(475, 19, 1, 'cosmetic', 'Some By Mi Yuja Niacin Brightening Moisture Gel Cream', 'some-by-mi-yuja-niacin-gel-cream', 'nemlendirici', 'Yuja + Niacinamide aydınlatıcı jel krem.', '30.00', 'ml', 'face', 'both', 'published'),
(476, 19, 1, 'cosmetic', 'Some By Mi Real Cica 92% Cool Calming Soothing Gel', 'some-by-mi-real-cica-92-gel', 'nemlendirici', 'Cica %92 serinletici jel. Yatıştırıcı.', '75.00', 'ml', 'face', 'both', 'published'),
(477, 19, 2, 'cosmetic', 'Some By Mi Super Matcha Pore Clean Cleansing Gel', 'some-by-mi-super-matcha-pore-cleanser', 'temizleyici', 'Matcha gözenek temizleme jeli.', '250.00', 'ml', 'face', 'both', 'published'),
(478, 19, 1, 'cosmetic', 'Some By Mi Retinol Intense Reactivating Serum', 'some-by-mi-retinol-intense-serum-sbm', 'serum', 'Retinol + Bakuchiol serum. Anti-aging.', '50.00', 'ml', 'face', 'both', 'published'),
(479, 19, 1, 'cosmetic', 'Some By Mi Snail Truecica Miracle Repair Serum', 'some-by-mi-snail-truecica-repair-serum', 'serum', 'Salyangoz + Cica onarım serumu.', '30.00', 'ml', 'face', 'both', 'published'),
(480, 19, 1, 'cosmetic', 'Some By Mi Beta Panthenol Repair Cream', 'some-by-mi-beta-panthenol-repair-cream', 'krem', 'Panthenol onarım kremi. Hassas ciltler.', '50.00', 'ml', 'face', 'both', 'published'),
(481, 19, 1, 'cosmetic', 'Some By Mi Hyaluronic Acid Moisture Barrier Cream', 'some-by-mi-hyaluronic-barrier-cream-sbm', 'krem', 'HA bariyer kremi. Nemlendirme + koruma.', '75.00', 'ml', 'face', 'both', 'published'),
(482, 17, 1, 'cosmetic', 'Klairs Supple Preparation Facial Toner', 'klairs-supple-preparation-toner', 'tonik', 'Hazırlık toneri. HA + Centella.', '150.00', 'ml', 'face', 'both', 'published'),
(483, 17, 1, 'cosmetic', 'Klairs Supple Preparation Unscented Toner', 'klairs-supple-preparation-unscented', 'tonik', 'Parfümsüz hazırlık toneri.', '250.00', 'ml', 'face', 'both', 'published'),
(484, 17, 1, 'cosmetic', 'Klairs Freshly Juiced Vitamin C Serum', 'klairs-freshly-juiced-vitamin-c', 'serum', 'C vitamini %5 nazik serum.', '20.00', 'ml', 'face', 'both', 'published'),
(485, 17, 1, 'cosmetic', 'Klairs Rich Moist Soothing Cream', 'klairs-rich-moist-soothing-cream-kl', 'krem', 'Zengin yatıştırıcı krem. Ceramide.', '75.00', 'ml', 'face', 'both', 'published'),
(486, 17, 1, 'cosmetic', 'Klairs Fundamental Water Gel Cream', 'klairs-fundamental-water-gel', 'nemlendirici', 'Su jel krem. Hafif nemlendirme.', '50.00', 'ml', 'face', 'both', 'published'),
(487, 17, 3, 'cosmetic', 'Klairs Soft Airy UV Essence SPF50+', 'klairs-soft-airy-uv-essence', 'güneş kremi', 'Hava gibi hafif güneş esansı.', '40.00', 'ml', 'face', 'morning', 'published'),
(488, 17, 6, 'cosmetic', 'Klairs All-Over Lotion', 'klairs-all-over-lotion-klairs', 'vücut losyonu', 'Yüz + Vücut losyon. Centella.', '500.00', 'ml', 'body', 'both', 'published'),
(489, 18, 1, 'cosmetic', 'Purito Centella Green Level Buffet Serum', 'purito-centella-buffet-serum', 'serum', 'Centella tampon serum. 49 bileşen.', '20.00', 'ml', 'face', 'both', 'published'),
(490, 18, 1, 'cosmetic', 'Purito Centella Unscented Recovery Cream', 'purito-centella-unscented-cream', 'krem', 'Parfümsüz centella onarım kremi.', '75.00', 'ml', 'face', 'both', 'published'),
(491, 18, 2, 'cosmetic', 'Purito Defence Barrier pH Cleanser', 'purito-defence-barrier-cleanser', 'temizleyici', 'pH 5.5 bariyer temizleyici.', '300.00', 'ml', 'face', 'both', 'published'),
(492, 18, 4, 'cosmetic', 'Purito Centella Green Level Eye Cream', 'purito-centella-eye-cream-purito', 'göz kremi', 'Centella göz kremi. Peptit.', '30.00', 'ml', 'eye', 'both', 'published'),
(493, 18, 3, 'cosmetic', 'Purito Daily Go-To Sunscreen SPF50+', 'purito-daily-go-to-sunscreen', 'güneş kremi', 'Günlük güneş kremi. Rice + Centella.', '60.00', 'ml', 'face', 'morning', 'published'),
(494, 18, 1, 'cosmetic', 'Purito Galacto Niacin 97 Power Essence', 'purito-galacto-niacin-97-essence', 'esans', 'Galactomyces %97 esans.', '50.00', 'ml', 'face', 'both', 'published'),
(495, 18, 1, 'cosmetic', 'Purito Centella Green Level Recovery Cream', 'purito-centella-green-level-cream', 'krem', 'Centella recovery krem. Onarım.', '50.00', 'ml', 'face', 'both', 'published'),
(496, 21, 1, 'cosmetic', 'Paula''s Choice Skin Perfecting 8% AHA Gel Exfoliant', 'paulas-choice-skin-perfecting-8-aha-gel', 'peeling', 'Glikolik asit %8 jel peeling.', '50.00', 'ml', 'face', 'evening', 'published'),
(497, 21, 4, 'cosmetic', 'Paula''s Choice RESIST Anti-Aging Eye Cream', 'paulas-choice-resist-anti-aging-eye', 'göz kremi', 'Retinol + Peptit anti-aging göz kremi.', '20.00', 'ml', 'eye', 'both', 'published'),
(498, 21, 1, 'cosmetic', 'Paula''s Choice Clinical 1% Retinol Treatment', 'paulas-choice-clinical-1-retinol', 'serum', 'Klinik retinol %1 tedavi serumu.', '30.00', 'ml', 'face', 'both', 'published'),
(499, 21, 1, 'cosmetic', 'Paula''s Choice RESIST Barrier Repair Moisturizer', 'paulas-choice-resist-barrier-repair', 'nemlendirici', 'Bariyer onarım nemlendirici. Retinol + HA.', '75.00', 'ml', 'face', 'both', 'published'),
(500, 21, 1, 'cosmetic', 'Paula''s Choice CALM Redness Relief Moisturizer SPF30', 'paulas-choice-calm-redness-relief-spf30', 'gündüz kremi', 'Kızarıklık yatıştırıcı SPF30.', '75.00', 'ml', 'face', 'morning', 'published'),
(501, 21, 1, 'cosmetic', 'Paula''s Choice Omega+ Complex Serum', 'paulas-choice-omega-complex-serum', 'serum', 'Omega yağ asidi serum. Bariyer güçlendirici.', '20.00', 'ml', 'face', 'both', 'published'),
(502, 21, 2, 'cosmetic', 'Paula''s Choice CLEAR Pore Normalizing Cleanser', 'paulas-choice-clear-pore-normalizer', 'temizleyici', 'Gözenek normalleştirici temizleyici.', '400.00', 'ml', 'face', 'both', 'published'),
(503, 21, 1, 'cosmetic', 'Paula''s Choice Azelaic Acid Booster', 'paulas-choice-azelaic-acid-booster-pc', 'serum', 'Azelaik asit %10 booster. Kızarıklık + leke.', '20.00', 'ml', 'face', 'both', 'published'),
(504, 21, 1, 'cosmetic', 'Paula''s Choice Defense Antioxidant Pore Purifier', 'paulas-choice-defense-antioxidant-purifier', 'serum', 'Antioksidan gözenek arındırıcı.', '50.00', 'ml', 'face', 'both', 'published'),
(505, 21, 1, 'cosmetic', 'Paula''s Choice Pro-Collagen Multi-Peptide Booster', 'paulas-choice-pro-collagen-peptide-booster', 'serum', 'Pro-kollajen peptit booster. Sıkılaştırma.', '30.00', 'ml', 'face', 'both', 'published'),
(506, 56, 1, 'cosmetic', 'Sunday Riley Good Genes All-In-One Lactic Acid Treatment', 'sunday-riley-good-genes-lactic-acid', 'peeling', 'Laktik asit tedavi serumu. Anında parlaklık.', '20.00', 'ml', 'face', 'evening', 'published'),
(507, 56, 1, 'cosmetic', 'Sunday Riley C.E.O. 15% Vitamin C Brightening Serum', 'sunday-riley-ceo-15-vitamin-c-serum', 'serum', 'C vitamini %15 THD. Aydınlatıcı.', '50.00', 'ml', 'face', 'both', 'published'),
(508, 56, 1, 'cosmetic', 'Sunday Riley Luna Retinol Sleeping Night Oil', 'sunday-riley-luna-retinol-sleeping-oil', 'yüz yağı', 'Retinol gece yağı. Trans-retinol ester.', '50.00', 'ml', 'face', 'evening', 'published'),
(509, 56, 1, 'cosmetic', 'Sunday Riley A+ High-Dose Retinoid Serum', 'sunday-riley-a-plus-retinoid-serum', 'serum', 'Yüksek doz retinoid. %5 HPR.', '20.00', 'ml', 'face', 'both', 'published'),
(510, 56, 1, 'cosmetic', 'Sunday Riley Ice Ceramide Moisturizer', 'sunday-riley-ice-ceramide-moisturizer', 'krem', 'Ceramide buz nemlendirici. Bariyer onarım.', '30.00', 'ml', 'face', 'both', 'published'),
(511, 59, 1, 'cosmetic', 'Glow Recipe Watermelon Glow Niacinamide Dew Drops', 'glow-recipe-watermelon-niacinamide-dew', 'serum', 'Karpuz + Niacinamide çiğ damlaları. Parlaklık.', '30.00', 'ml', 'face', 'both', 'published'),
(512, 59, 1, 'cosmetic', 'Glow Recipe Watermelon Glow PHA+BHA Toner', 'glow-recipe-watermelon-pha-bha-toner', 'tonik', 'Karpuz PHA+BHA tonik. Nazik peeling.', '150.00', 'ml', 'face', 'both', 'published'),
(513, 59, 1, 'cosmetic', 'Glow Recipe Plum Plump Hyaluronic Acid Serum', 'glow-recipe-plum-plump-ha-serum', 'serum', 'Erik + HA dolgunlaştırıcı serum.', '30.00', 'ml', 'face', 'both', 'published'),
(514, 59, 1, 'cosmetic', 'Glow Recipe Avocado Ceramide Recovery Serum', 'glow-recipe-avocado-ceramide-serum', 'serum', 'Avokado + Ceramide onarım serumu.', '30.00', 'ml', 'face', 'both', 'published'),
(515, 59, 1, 'cosmetic', 'Glow Recipe Strawberry Smooth BHA+AHA Salicylic Acid Serum', 'glow-recipe-strawberry-smooth-bha-aha', 'peeling', 'Çilek BHA+AHA peeling serumu.', '50.00', 'ml', 'face', 'evening', 'published'),
(516, 65, 1, 'cosmetic', 'Weleda Skin Food Original', 'weleda-skin-food-original', 'krem', 'Orijinal cilt besleyici. Bitki bazlı yoğun bakım.', '50.00', 'ml', 'face', 'both', 'published'),
(517, 65, 1, 'cosmetic', 'Weleda Skin Food Light', 'weleda-skin-food-light', 'nemlendirici', 'Hafif cilt besleyici. Günlük kullanım.', '30.00', 'ml', 'face', 'both', 'published'),
(518, 65, 1, 'cosmetic', 'Weleda Almond Soothing Facial Cream', 'weleda-almond-soothing-cream', 'krem', 'Badem yatıştırıcı krem. Hassas ciltler.', '30.00', 'ml', 'face', 'both', 'published'),
(519, 65, 4, 'cosmetic', 'Weleda Wild Rose Smoothing Eye Cream', 'weleda-wild-rose-eye-cream', 'göz kremi', 'Yaban gülü göz kremi. Antioksidan.', '20.00', 'ml', 'eye', 'both', 'published'),
(520, 65, 1, 'cosmetic', 'Weleda Pomegranate Firming Face Serum', 'weleda-pomegranate-firming-serum', 'serum', 'Nar sıkılaştırıcı serum. Anti-aging.', '30.00', 'ml', 'face', 'both', 'published'),
(521, 37, 2, 'cosmetic', 'Medicube Red Acne Body Wash', 'medicube-red-acne-body-wash', 'temizleyici', 'Akne vücut yıkama. BHA + Centella.', '200.00', 'ml', 'face', 'both', 'published'),
(522, 37, 1, 'cosmetic', 'Medicube Zero Pore Pad', 'medicube-zero-pore-pad', 'peeling', 'Gözenek peeling pad. PHA + AHA.', '20.00', 'ml', 'face', 'evening', 'published'),
(523, 37, 1, 'cosmetic', 'Medicube Deep Vita C Serum', 'medicube-deep-vita-c-serum', 'serum', 'C vitamini serum. 3 tip C vitamini.', '20.00', 'ml', 'face', 'both', 'published'),
(524, 37, 1, 'cosmetic', 'Medicube Collagen Jelly Cream', 'medicube-collagen-jelly-cream', 'krem', 'Kollajen jöle krem. Sıkılaştırma.', '30.00', 'ml', 'face', 'both', 'published'),
(525, 37, 1, 'cosmetic', 'Medicube Red Erasing Cream', 'medicube-red-erasing-cream', 'krem', 'Kızarıklık silici krem. Cica + Centella.', '50.00', 'ml', 'face', 'both', 'published'),
(526, 37, 1, 'cosmetic', 'Medicube AGE-R Booster-H', 'medicube-age-r-booster-h', 'serum', 'HA booster serum. Cihaz uyumlu.', '20.00', 'ml', 'face', 'both', 'published'),
(527, 26, 1, 'cosmetic', 'Garnier SkinActive Hyaluronic Aloe Jelly Moisturizer', 'garnier-hyaluronic-aloe-jelly', 'nemlendirici', 'HA + Aloe jöle nemlendirici.', '50.00', 'ml', 'face', 'both', 'published'),
(528, 26, 1, 'cosmetic', 'Garnier Pure Active 3-in-1 Wash Scrub Mask', 'garnier-pure-active-3in1', 'peeling', '3''ü 1 arada temizleyici. Akne bakım.', '20.00', 'ml', 'face', 'evening', 'published'),
(529, 26, 4, 'cosmetic', 'Garnier SkinActive Niacinamide + Kale Eye Cream', 'garnier-niacinamide-kale-eye-cream', 'göz kremi', 'Niacinamide göz kremi.', '15.00', 'ml', 'eye', 'both', 'published'),
(530, 26, 1, 'cosmetic', 'Garnier SkinActive Anti-Fatigue Night Cream', 'garnier-anti-fatigue-night-cream', 'gece kremi', 'Anti-yorgunluk gece kremi.', '30.00', 'ml', 'face', 'evening', 'published'),
(531, 26, 1, 'cosmetic', 'Garnier Organic Lavandin Face Moisturizer', 'garnier-organic-lavandin-moisturizer', 'nemlendirici', 'Organik lavanta nemlendirici.', '30.00', 'ml', 'face', 'both', 'published'),
(532, 26, 3, 'cosmetic', 'Garnier Ambre Solaire Super UV Face Fluid SPF50+', 'garnier-ambre-solaire-face-fluid', 'güneş kremi', 'Ultra hafif yüz sıvısı SPF50+.', '100.00', 'ml', 'face', 'morning', 'published'),
(533, 26, 1, 'cosmetic', 'Garnier SkinActive Pure Charcoal Mask', 'garnier-pure-charcoal-mask', 'maske', 'Aktif kömür arındırıcı maske.', '50.00', 'ml', 'face', 'evening', 'published'),
(534, 26, 1, 'cosmetic', 'Garnier Fructis Hair Food Banana Mask', 'garnier-fructis-hair-food-banana', 'maske', 'Muz saç maskesi. Besleyici.', '100.00', 'ml', 'face', 'evening', 'published'),
(535, 27, 1, 'cosmetic', 'Nivea Cellular Luminous 630 Anti-Spot Serum', 'nivea-cellular-luminous-630-serum', 'serum', 'Luminous630 leke serumu. Patentli aktif.', '30.00', 'ml', 'face', 'both', 'published'),
(536, 27, 1, 'cosmetic', 'Nivea Naturally Good Anti-Wrinkle Day Care', 'nivea-naturally-good-anti-wrinkle', 'gündüz kremi', 'Doğal anti-kırışıklık gündüz bakımı.', '75.00', 'ml', 'face', 'morning', 'published'),
(537, 27, 1, 'cosmetic', 'Nivea Hyaluron Cellular Filler + Elasticity Night', 'nivea-hyaluron-filler-elasticity-night', 'gece kremi', 'HA + Elasticity gece kremi.', '30.00', 'ml', 'face', 'evening', 'published'),
(538, 27, 3, 'cosmetic', 'Nivea Sun UV Face Shine Control SPF50', 'nivea-sun-shine-control-spf50', 'güneş kremi', 'Mat bitiş yüz güneş koruyucu.', '200.00', 'ml', 'face', 'morning', 'published'),
(539, 27, 2, 'cosmetic', 'Nivea MicellAIR Skin Breathe Micellar Water', 'nivea-micellair-skin-breathe', 'micellar su', 'Micellar temizleme suyu. Tüm cilt tipleri.', '400.00', 'ml', 'face', 'evening', 'published'),
(540, 27, 1, 'cosmetic', 'Nivea Essentials Enriching Day Cream SPF15', 'nivea-essentials-enriching-day', 'gündüz kremi', 'Besleyici gündüz bakımı SPF15.', '50.00', 'ml', 'face', 'morning', 'published'),
(541, 27, 4, 'cosmetic', 'Nivea Q10 Anti-Wrinkle + Firming Eye Cream', 'nivea-q10-firming-eye-cream', 'göz kremi', 'Q10 göz kremi. Kırışıklık azaltıcı.', '30.00', 'ml', 'eye', 'both', 'published'),
(542, 27, 1, 'cosmetic', 'Nivea Soft Moisturizing Creme', 'nivea-soft-moisturizing-creme', 'krem', 'Soft nemlendirici krem. Yüz + Vücut.', '75.00', 'ml', 'face', 'both', 'published'),
(543, 28, 1, 'cosmetic', 'Innisfree Retinol Cica Moisture Recovery Serum', 'innisfree-retinol-cica-recovery-serum', 'serum', 'Retinol + Cica kurtarma serumu. Anti-aging.', '20.00', 'ml', 'face', 'both', 'published'),
(544, 28, 1, 'cosmetic', 'Innisfree Jeju Cherry Blossom Tone-Up Cream', 'innisfree-cherry-blossom-tone-up', 'krem', 'Kiraz çiçeği renk düzeltici krem.', '50.00', 'ml', 'face', 'both', 'published'),
(545, 28, 1, 'cosmetic', 'Innisfree Green Tea Hyaluronic Acid Cream', 'innisfree-green-tea-ha-cream-innisfree', 'krem', 'Yeşil çay + HA krem. Nemlendirme.', '30.00', 'ml', 'face', 'both', 'published'),
(546, 28, 1, 'cosmetic', 'Innisfree Volcanic Pore Clay Mask', 'innisfree-volcanic-pore-clay-mask', 'maske', 'Volkanik kil gözenek maskesi.', '30.00', 'ml', 'face', 'evening', 'published'),
(547, 28, 1, 'cosmetic', 'Innisfree Dewy Glow Jelly Cream', 'innisfree-dewy-glow-jelly-cream', 'krem', 'Çiğli parlaklık jöle krem.', '75.00', 'ml', 'face', 'both', 'published'),
(548, 28, 1, 'cosmetic', 'Innisfree Retinol Cica Spot Serum', 'innisfree-retinol-cica-spot-serum', 'serum', 'Retinol + Cica leke serumu.', '30.00', 'ml', 'face', 'both', 'published'),
(549, 5, 1, 'cosmetic', 'Avene Cleanance Comedomed Anti-Blemish Concentrate', 'avene-cleanance-comedomed', 'serum', 'Komedomed akne konsantresi. ComedoClastin.', '20.00', 'ml', 'face', 'both', 'published'),
(550, 5, 2, 'cosmetic', 'Avene Cleanance Cleansing Gel', 'avene-cleanance-cleansing-gel', 'temizleyici', 'Akne temizleme jeli. Monolaurin.', '250.00', 'ml', 'face', 'both', 'published'),
(551, 5, 1, 'cosmetic', 'Avene Hydrance Aqua-Gel', 'avene-hydrance-aqua-gel', 'nemlendirici', 'Aqua-jel nemlendirici. Tüm cilt tipleri.', '50.00', 'ml', 'face', 'both', 'published'),
(552, 5, 1, 'cosmetic', 'Avene Hydrance UV Rich Cream SPF30', 'avene-hydrance-uv-rich-spf30', 'gündüz kremi', 'Zengin nemlendirici SPF30.', '50.00', 'ml', 'face', 'morning', 'published'),
(553, 5, 1, 'cosmetic', 'Avene Thermal Spring Water Spray', 'avene-thermal-spring-water-spray', 'mist', 'Termal su spreyi. Yatıştırıcı.', '80.00', 'ml', 'face', 'both', 'published'),
(554, 5, 6, 'cosmetic', 'Avene Xeracalm A.D Lipid-Replenishing Cream', 'avene-xeracalm-ad-lipid-cream', 'vücut kremi', 'Atopik bakım lipid krem.', '400.00', 'ml', 'body', 'both', 'published'),
(555, 5, 3, 'cosmetic', 'Avene Cleanance SPF50+ Tinted Sunscreen', 'avene-cleanance-spf50-tinted', 'güneş kremi', 'Renkli akne güneş koruyucu.', '40.00', 'ml', 'face', 'morning', 'published'),
(556, 5, 3, 'cosmetic', 'Avene Very High Protection Fluid SPF50+', 'avene-very-high-protection-fluid', 'güneş kremi', 'Ultra koruma sıvısı. Hassas ciltler.', '100.00', 'ml', 'face', 'morning', 'published'),
(557, 6, 1, 'cosmetic', 'SVR Sebiaclear Serum', 'svr-sebiaclear-serum', 'serum', 'Akne serum. Niacinamide + Glukonolakton.', '20.00', 'ml', 'face', 'both', 'published'),
(558, 6, 1, 'cosmetic', 'SVR Sebiaclear Active Cream', 'svr-sebiaclear-active-cream', 'krem', 'Aktif akne kremi. BHA + Bakır.', '30.00', 'ml', 'face', 'both', 'published'),
(559, 6, 6, 'cosmetic', 'SVR Topialyse Baume Intensif', 'svr-topialyse-baume-intensif', 'vücut kremi', 'Atopik yoğun balsam.', '250.00', 'ml', 'body', 'both', 'published'),
(560, 6, 1, 'cosmetic', 'SVR Hydraliane Light Moisturizer', 'svr-hydraliane-light', 'nemlendirici', 'Hafif nemlendirici. Tüm cilt tipleri.', '100.00', 'ml', 'face', 'both', 'published'),
(561, 6, 1, 'cosmetic', 'SVR Clairial 10 Dark Spot Concentrate', 'svr-clairial-10-dark-spot', 'serum', 'Leke konsantresi. Niacinamide %10.', '30.00', 'ml', 'face', 'both', 'published'),
(562, 6, 1, 'cosmetic', 'SVR Ampoule B3 Hydra Repairing Concentrate', 'svr-ampoule-b3-hydra', 'ampul', 'B3 + HA onarıcı ampul.', '20.00', 'ml', 'face', 'evening', 'published'),
(563, 23, 1, 'cosmetic', 'Isntree Chestnut AHA 8% Clear Essence', 'isntree-chestnut-aha-8-essence', 'esans', 'Kestane AHA %8 peeling esans.', '150.00', 'ml', 'face', 'both', 'published'),
(564, 23, 1, 'cosmetic', 'Isntree C-Niacin Toning Cream', 'isntree-c-niacin-toning-cream', 'krem', 'C vitamini + Niacinamide tonlama kremi.', '75.00', 'ml', 'face', 'both', 'published'),
(565, 23, 1, 'cosmetic', 'Isntree Aloe Soothing Gel Fresh', 'isntree-aloe-soothing-gel-fresh', 'nemlendirici', 'Aloe yatıştırıcı jel. Ferahlatıcı.', '75.00', 'ml', 'face', 'both', 'published'),
(566, 23, 1, 'cosmetic', 'Isntree Spot Saver Mugwort Ampoule', 'isntree-spot-saver-mugwort-ampoule', 'ampul', 'Yavşan otu leke ampulü.', '20.00', 'ml', 'face', 'evening', 'published'),
(567, 23, 1, 'cosmetic', 'Isntree TW-Real Bifida Ampoule', 'isntree-tw-real-bifida-ampoule', 'ampul', 'Bifida ferment ampulü. Onarım.', '30.00', 'ml', 'face', 'evening', 'published'),
(568, 23, 1, 'cosmetic', 'Isntree Clear Skin BHA Toner', 'isntree-clear-skin-bha-toner', 'tonik', 'BHA berraklaştırıcı tonik.', '300.00', 'ml', 'face', 'both', 'published'),
(569, 25, 1, 'cosmetic', 'Missha First Treatment Essence RX', 'missha-first-treatment-essence-rx', 'esans', 'Fermente maya esans. Saccharomyces.', '100.00', 'ml', 'face', 'both', 'published'),
(570, 25, 1, 'cosmetic', 'Missha Bee Pollen Renew Ampoule', 'missha-bee-pollen-renew-ampoule', 'ampul', 'Arı poleni yenileyici ampul.', '20.00', 'ml', 'face', 'evening', 'published'),
(571, 25, 1, 'cosmetic', 'Missha Chogongjin Sosaeng Cream', 'missha-chogongjin-sosaeng-cream', 'krem', 'Kore hanbang zengin krem.', '75.00', 'ml', 'face', 'both', 'published'),
(572, 25, 1, 'cosmetic', 'Missha Super Aqua Ultra Hyaluronic Acid Serum', 'missha-super-aqua-ha-serum', 'serum', 'HA serum. 3 tip hyaluronic acid.', '30.00', 'ml', 'face', 'both', 'published'),
(573, 25, 3, 'cosmetic', 'Missha Airy Fit Sun Milk SPF50+', 'missha-airy-fit-sun-milk', 'güneş kremi', 'Hafif güneş sütü.', '40.00', 'ml', 'face', 'morning', 'published'),
(574, 24, 2, 'cosmetic', 'Beauty of Joseon Ginseng Cleansing Oil', 'beauty-of-joseon-boj-ginseng-cleansing-oil', 'temizleme yağı', 'Ginseng temizleme yağı. K-beauty.', '200.00', 'ml', 'face', 'evening', 'published'),
(575, 24, 4, 'cosmetic', 'Beauty of Joseon Revive Eye Serum: Ginseng + Retinal', 'beauty-of-joseon-boj-revive-eye-serum', 'göz kremi', 'Ginseng + Retinal göz serumu.', '30.00', 'ml', 'eye', 'both', 'published'),
(576, 24, 1, 'cosmetic', 'Beauty of Joseon Glow Serum: Propolis + Niacinamide 60ml', 'beauty-of-joseon-boj-glow-serum-propolis-60ml', 'serum', 'Propolis serumu büyük boy.', '20.00', 'ml', 'face', 'both', 'published'),
(577, 24, 1, 'cosmetic', 'Beauty of Joseon Calming Serum: Green Tea + Panthenol', 'beauty-of-joseon-boj-calming-serum-green-tea', 'serum', 'Yeşil çay + Panthenol yatıştırıcı serum.', '30.00', 'ml', 'face', 'both', 'published'),
(578, 24, 1, 'cosmetic', 'Beauty of Joseon Dynasty Cream', 'beauty-of-joseon-boj-dynasty-cream', 'krem', 'Ginseng anti-aging krem. Hanbang.', '30.00', 'ml', 'face', 'both', 'published'),
(579, 24, 3, 'cosmetic', 'Beauty of Joseon Matte Sun Stick: Mugwort + Camelia SPF50+', 'beauty-of-joseon-boj-matte-sun-stick', 'güneş stick', 'Mat güneş stick. SPF50+.', '20.00', 'g', 'face', 'morning', 'published'),
(580, 16, 1, 'cosmetic', 'Hada Labo Gokujyun Premium Hyaluronic Acid Lotion', 'hada-labo-gokujyun-premium-lotion', 'tonik', 'Premium HA losyon. 7 tip hyaluronic acid.', '150.00', 'ml', 'face', 'both', 'published'),
(581, 16, 2, 'cosmetic', 'Hada Labo Gokujyun Hyaluronic Acid Cleansing Foam', 'hada-labo-gokujyun-cleansing-foam', 'temizleyici', 'HA temizleme köpüğü. Super HA.', '150.00', 'ml', 'face', 'both', 'published'),
(582, 16, 4, 'cosmetic', 'Hada Labo Gokujyun Hyaluronic Acid Eye Cream', 'hada-labo-gokujyun-eye-cream', 'göz kremi', 'HA göz kremi. Nemlendirici.', '10.00', 'ml', 'eye', 'both', 'published'),
(583, 16, 1, 'cosmetic', 'Hada Labo Gokujyun Perfect Gel', 'hada-labo-gokujyun-perfect-gel', 'nemlendirici', '5''i 1 arada jel nemlendirici.', '50.00', 'ml', 'face', 'both', 'published'),
(584, 16, 3, 'cosmetic', 'Hada Labo Koi-Gokujyun UV White Gel SPF50+', 'hada-labo-koi-gokujyun-uv-gel', 'güneş kremi', 'HA güneş jeli. Aydınlatıcı.', '40.00', 'ml', 'face', 'morning', 'published'),
(585, 31, 2, 'cosmetic', 'Etude House SoonJung pH 6.5 Whip Cleanser', 'etude-house-soonjung-ph65-cleanser', 'temizleyici', 'pH 6.5 hafif temizleyici. Hassas ciltler.', '200.00', 'ml', 'face', 'both', 'published'),
(586, 31, 1, 'cosmetic', 'Etude House SoonJung 2x Barrier Intensive Cream', 'etude-house-soonjung-2x-barrier-cream', 'krem', 'Çift bariyer yoğun krem. Panthenol + Madecassoside.', '30.00', 'ml', 'face', 'both', 'published'),
(587, 31, 1, 'cosmetic', 'Etude House SoonJung 10-Free Moist Emulsion', 'etude-house-soonjung-10free-emulsion', 'nemlendirici', '10 zararlı madde içermeyen emülsiyon.', '30.00', 'ml', 'face', 'both', 'published'),
(588, 31, 1, 'cosmetic', 'Etude House Moistfull Collagen Deep Cream', 'etude-house-moistfull-collagen-deep-cream', 'krem', 'Kollajen derin krem. Dolgunluk.', '75.00', 'ml', 'face', 'both', 'published'),
(589, 31, 1, 'cosmetic', 'Etude House SoonJung Centella 5-Panthensoside Cica Balm', 'etude-house-soonjung-cica-balm', 'balsam', 'Centella + Panthenol cica balsam.', '40.00', 'ml', 'face_body', 'both', 'published'),
(590, 31, 3, 'cosmetic', 'Etude House SoonJung Mild Defence Sun Cream SPF49', 'etude-house-soonjung-mild-sun-spf49', 'güneş kremi', 'Nazik güneş kremi. Hassas ciltler.', '200.00', 'ml', 'face', 'morning', 'published'),
(591, 71, 1, 'cosmetic', 'Noreva Exfoliac Global 6 Intensive Treatment', 'noreva-exfoliac-global-6', 'serum', '6 etkili akne tedavi serumu.', '20.00', 'ml', 'face', 'both', 'published'),
(592, 71, 1, 'cosmetic', 'Noreva Alpha KM Anti-Ageing Firming Day Cream', 'noreva-alpha-km-firming-day', 'gündüz kremi', 'Anti-aging sıkılaştırıcı gündüz kremi.', '30.00', 'ml', 'face', 'morning', 'published'),
(593, 71, 1, 'cosmetic', 'Noreva Trio White S Depigmenting Serum', 'noreva-trio-white-s-serum', 'serum', 'Üçlü aydınlatıcı leke serumu.', '30.00', 'ml', 'face', 'both', 'published'),
(594, 71, 1, 'cosmetic', 'Noreva Aquareva Moisturizing Day Cream', 'noreva-aquareva-moisturizing-day', 'gündüz kremi', '24 saat nemlendirici gündüz kremi.', '30.00', 'ml', 'face', 'morning', 'published'),
(595, 72, 1, 'cosmetic', 'ACM Depiwhite Advanced Depigmenting Cream', 'acm-depiwhite-advanced-cream', 'krem', 'Leke karşıtı krem. Lumiskin.', '75.00', 'ml', 'face', 'both', 'published'),
(596, 72, 1, 'cosmetic', 'ACM Sebionex Mattifying Cream', 'acm-sebionex-mattifying-cream', 'nemlendirici', 'Matlaştırıcı krem. Yağlı ciltler.', '30.00', 'ml', 'face', 'both', 'published'),
(597, 72, 1, 'cosmetic', 'ACM Duolys CE Intensive Antioxidant Serum', 'acm-duolys-ce-antioxidant-serum', 'serum', 'C+E vitamini antioksidan serum.', '20.00', 'ml', 'face', 'both', 'published'),
(598, 72, 1, 'cosmetic', 'ACM Vitix Gel Repigmenting', 'acm-vitix-gel-repigmenting', 'krem', 'Vitiligo bakım jeli. Repigmentasyon.', '30.00', 'ml', 'face', 'both', 'published'),
(599, 70, 1, 'cosmetic', 'Lierac Cica-Filler Anti-Wrinkle Repairing Serum', 'lierac-cica-filler-serum', 'serum', 'Cica + Dolgu kırışıklık onarım serumu.', '50.00', 'ml', 'face', 'both', 'published'),
(600, 70, 1, 'cosmetic', 'Lierac Mesolift C15 Extemporaneous Anti-Fatigue Concentrate', 'lierac-mesolift-c15-concentrate', 'serum', 'C vitamini %15 anti-yorgunluk konsantre.', '30.00', 'ml', 'face', 'both', 'published'),
(601, 70, 3, 'cosmetic', 'Lierac Sunissime Fluide Protecteur SPF50+', 'lierac-sunissime-fluide-spf50', 'güneş kremi', 'Koruyucu güneş sıvısı. Anti-aging.', '100.00', 'ml', 'face', 'morning', 'published'),
(602, 70, 1, 'cosmetic', 'Lierac Lift Integral Sculpting Lift Cream', 'lierac-lift-integral-sculpting-cream', 'krem', 'Lüks sıkılaştırıcı yontu kremi.', '50.00', 'ml', 'face', 'both', 'published'),
(603, 57, 1, 'cosmetic', 'Tatcha The Dewy Skin Cream', 'tatcha-dewy-skin-cream', 'krem', 'Japon mor pirinç çiğli krem.', '30.00', 'ml', 'face', 'both', 'published'),
(604, 57, 1, 'cosmetic', 'Tatcha The Water Cream', 'tatcha-water-cream-tatcha', 'nemlendirici', 'Hafif su krem. Hadasei-3.', '30.00', 'ml', 'face', 'both', 'published'),
(605, 57, 2, 'cosmetic', 'Tatcha The Rice Wash', 'tatcha-rice-wash-tatcha', 'temizleyici', 'Pirinç temizleyici. Enzim peeling.', '200.00', 'ml', 'face', 'both', 'published'),
(606, 57, 1, 'cosmetic', 'Tatcha Luminous Dewy Skin Mist', 'tatcha-luminous-dewy-mist', 'mist', 'Parlaklık misti. Botanik yağlar.', '100.00', 'ml', 'face', 'both', 'published'),
(607, 58, 2, 'cosmetic', 'Fresh Soy Face Cleanser', 'fresh-soy-face-cleanser', 'temizleyici', 'Soya temizleyici. Nazik makyaj çözücü.', '300.00', 'ml', 'face', 'both', 'published'),
(608, 58, 1, 'cosmetic', 'Fresh Rose Deep Hydration Face Cream', 'fresh-rose-deep-hydration-cream', 'krem', 'Gül nemlendirici krem. Damask gülü.', '30.00', 'ml', 'face', 'both', 'published'),
(609, 58, 4, 'cosmetic', 'Fresh Black Tea Firming Eye Serum', 'fresh-black-tea-eye-serum', 'göz kremi', 'Siyah çay göz serumu. Sıkılaştırıcı.', '15.00', 'ml', 'eye', 'both', 'published'),
(610, 58, 1, 'cosmetic', 'Fresh Lotus Youth Preserve Moisturizer', 'fresh-lotus-youth-preserve', 'nemlendirici', 'Lotus çiçeği anti-aging nemlendirici.', '100.00', 'ml', 'face', 'both', 'published'),
(611, 60, 2, 'cosmetic', 'Farmacy Green Clean Makeup Removing Cleansing Balm', 'farmacy-green-clean-balm', 'temizleme yağı', 'Yeşil temizleme balmı. Echinacea.', '250.00', 'ml', 'face', 'evening', 'published'),
(612, 60, 1, 'cosmetic', 'Farmacy Honey Potion Renewing Antioxidant Hydration Mask', 'farmacy-honey-potion-mask', 'maske', 'Bal antioksidan nemlendirme maskesi.', '75.00', 'ml', 'face', 'evening', 'published'),
(613, 60, 1, 'cosmetic', 'Farmacy 10% Niacinamide Night Mask', 'farmacy-niacinamide-10-night-mask', 'maske', 'Niacinamide %10 gece maskesi.', '50.00', 'ml', 'face', 'evening', 'published'),
(614, 60, 1, 'cosmetic', 'Farmacy Daily Greens Oil-Free Gel Moisturizer', 'farmacy-daily-greens-gel-moisturizer', 'nemlendirici', 'Yeşillikli jel nemlendirici. Papaya.', '75.00', 'ml', 'face', 'both', 'published'),
(615, 53, 1, 'cosmetic', 'SK-II Facial Treatment Essence', 'sk-ii-facial-treatment-essence', 'esans', 'İkonik Pitera esans. %90 Pitera.', '100.00', 'ml', 'face', 'both', 'published'),
(616, 53, 1, 'cosmetic', 'SK-II GenOptics Aura Essence', 'sk-ii-genoptics-aura-essence', 'serum', 'Aura aydınlatıcı esans. GenOptics.', '50.00', 'ml', 'face', 'both', 'published'),
(617, 53, 1, 'cosmetic', 'SK-II Skinpower Cream', 'sk-ii-skinpower-cream', 'krem', 'Güç krem. Pitera + Peptit.', '75.00', 'ml', 'face', 'both', 'published'),
(618, 53, 1, 'cosmetic', 'SK-II R.N.A. Power Airy Milky Lotion', 'sk-ii-rna-power-airy-lotion', 'nemlendirici', 'RNA hafif süt losyon.', '75.00', 'ml', 'face', 'both', 'published'),
(619, 66, 1, 'cosmetic', 'Dr. Hauschka Rose Day Cream', 'dr-hauschka-rose-day-cream', 'krem', 'Gül gündüz kremi. Doğal bakım.', '75.00', 'ml', 'face', 'both', 'published'),
(620, 66, 2, 'cosmetic', 'Dr. Hauschka Soothing Cleansing Milk', 'dr-hauschka-soothing-cleansing-milk', 'temizleyici', 'Yatıştırıcı temizleme sütü.', '250.00', 'ml', 'face', 'both', 'published'),
(621, 66, 1, 'cosmetic', 'Dr. Hauschka Revitalising Day Cream', 'dr-hauschka-revitalising-day-cream', 'gündüz kremi', 'Canlandırıcı gündüz kremi. 40+', '30.00', 'ml', 'face', 'morning', 'published'),
(622, 66, 5, 'cosmetic', 'Dr. Hauschka Lip Care Stick', 'dr-hauschka-lip-care-stick', 'dudak bakım', 'Dudak bakım stick. Doğal.', '15.00', 'ml', 'lips', 'both', 'published'),
(623, 48, 1, 'cosmetic', 'Muji Sensitive Skin Toning Water Light', 'muji-sensitive-toning-water-light', 'tonik', 'Hassas cilt toneri. Minimal formül.', '250.00', 'ml', 'face', 'both', 'published'),
(624, 48, 1, 'cosmetic', 'Muji Sensitive Skin All in One Essence', 'muji-sensitive-all-in-one-essence', 'esans', 'Hassas cilt çok fonksiyonlu esans.', '150.00', 'ml', 'face', 'both', 'published'),
(625, 48, 2, 'cosmetic', 'Muji Cleansing Oil', 'muji-cleansing-oil-muji', 'temizleme yağı', 'Temizleme yağı. Zeytinyağı bazlı.', '150.00', 'ml', 'face', 'evening', 'published'),
(626, 48, 1, 'cosmetic', 'Muji Sensitive Skin Moisturizing Cream', 'muji-sensitive-moisturizing-cream-muji', 'krem', 'Hassas cilt nemlendirici krem.', '50.00', 'ml', 'face', 'both', 'published'),
(627, 64, 6, 'cosmetic', 'Dove DermaSpa Goodness Body Cream', 'dove-dermaspa-goodness-body-cream', 'vücut kremi', 'Zengin vücut kremi. Shea yağı.', '200.00', 'ml', 'body', 'both', 'published'),
(628, 64, 2, 'cosmetic', 'Dove Sensitive Skin Beauty Bar', 'dove-sensitive-skin-beauty-bar', 'temizleyici', 'Hassas cilt temizleme barı. pH dengeli.', '400.00', 'ml', 'face', 'both', 'published'),
(629, 64, 1, 'cosmetic', 'Dove Advanced Hair Series Regenerate Nourishment Serum', 'dove-advanced-hair-serum', 'serum', 'Saç onarım serumu. Keratin.', '50.00', 'ml', 'face', 'both', 'published'),
(630, 64, 6, 'cosmetic', 'Dove Nourishing Body Care Body Lotion', 'dove-nourishing-body-lotion-dove', 'vücut losyonu', 'Besleyici vücut losyonu.', '400.00', 'ml', 'body', 'both', 'published'),
(631, 46, 3, 'cosmetic', 'Canmake Mermaid Skin Gel UV SPF50+', 'canmake-mermaid-skin-gel-uv', 'güneş kremi', 'Deniz kızı jel güneş koruyucu. Şeffaf.', '60.00', 'ml', 'face', 'morning', 'published'),
(632, 46, 3, 'cosmetic', 'Canmake Secret Beauty Powder', 'canmake-secret-beauty-powder', 'güneş kremi', 'Gizli güzellik pudrası. Mat bitiş.', '50.00', 'ml', 'face', 'morning', 'published'),
(633, 51, 1, 'cosmetic', 'Estée Lauder Advanced Night Repair Serum', 'este-lauder-advanced-night-repair-serum', 'serum', 'İkonik gece onarım serumu. Chronolux.', '50.00', 'ml', 'face', 'both', 'published'),
(634, 51, 1, 'cosmetic', 'Estée Lauder Perfectionist Pro Rapid Brightening Treatment', 'este-lauder-perfectionist-pro-brightening', 'serum', 'Hızlı aydınlatma tedavisi.', '20.00', 'ml', 'face', 'both', 'published'),
(635, 51, 1, 'cosmetic', 'Estée Lauder Revitalizing Supreme+ Global Anti-Aging Cell Power Cream', 'este-lauder-revitalizing-supreme-cream', 'krem', 'Küresel anti-aging krem.', '50.00', 'ml', 'face', 'both', 'published'),
(636, 51, 1, 'cosmetic', 'Estée Lauder DayWear Multi-Protection Anti-Oxidant Cream SPF15', 'este-lauder-daywear-anti-oxidant-spf15', 'gündüz kremi', 'Antioksidan gündüz bakımı SPF15.', '75.00', 'ml', 'face', 'morning', 'published'),
(637, 51, 4, 'cosmetic', 'Estée Lauder Advanced Night Repair Eye Supercharged Gel-Crème', 'este-lauder-anr-eye-gel-creme', 'göz kremi', 'Gece onarım göz jel krem.', '30.00', 'ml', 'eye', 'both', 'published'),
(638, 1, 1, 'cosmetic', 'La Roche-Posay Effaclar H ISO-BIOME Ultra Soothing Moisturiser', 'la-roche-posay-effaclar-h-iso-biome', 'nemlendirici', 'Kurumuş akneye eğilimli ciltler nemlendirici.', '50.00', 'ml', 'face', 'both', 'published'),
(639, 1, 1, 'cosmetic', 'La Roche-Posay Substiane Extra Riche', 'la-roche-posay-substiane-extra-riche', 'krem', 'Olgun ciltler yoğun besleyici krem.', '75.00', 'ml', 'face', 'both', 'published'),
(640, 1, 1, 'cosmetic', 'La Roche-Posay Rosaliac UV Riche SPF15', 'la-roche-posay-rosaliac-uv-riche', 'gündüz kremi', 'Kızarıklık eğilimli kuru ciltler SPF15.', '30.00', 'ml', 'face', 'morning', 'published'),
(641, 1, 2, 'cosmetic', 'La Roche-Posay Toleriane Dermo-Cleanser', 'la-roche-posay-toleriane-dermo-cleanser', 'temizleyici', 'Hassas ciltler dermo temizleyici.', '500.00', 'ml', 'face', 'both', 'published'),
(642, 1, 1, 'cosmetic', 'La Roche-Posay Effaclar Astringent Micro-Peeling Toner', 'la-roche-posay-effaclar-astringent-toner', 'tonik', 'Sıkılaştırıcı peeling tonik. LHA.', '250.00', 'ml', 'face', 'both', 'published'),
(643, 2, 2, 'cosmetic', 'CeraVe Acne Foaming Cream Cleanser', 'cerave-acne-foaming-cream-cleanser', 'temizleyici', 'Akne köpük krem temizleyici. Benzoil peroksit %4.', '300.00', 'ml', 'face', 'both', 'published'),
(644, 2, 1, 'cosmetic', 'CeraVe Diabetics Moisturizing Cream', 'cerave-diabetics-moisturizing-cream', 'krem', 'Diyabetik ciltler nemlendirici krem.', '75.00', 'ml', 'face', 'both', 'published'),
(645, 2, 6, 'cosmetic', 'CeraVe Itch Relief Moisturizing Lotion', 'cerave-itch-relief-moisturizing-lotion', 'vücut losyonu', 'Kaşıntı rahatlatıcı losyon. Pramoksin.', '300.00', 'ml', 'body', 'both', 'published'),
(646, 2, 6, 'cosmetic', 'CeraVe Therapeutic Hand Cream', 'cerave-therapeutic-hand-cream', 'el kremi', 'Terapötik el kremi. Çok kuru eller.', '30.00', 'ml', 'hands', 'both', 'published'),
(647, 2, 1, 'cosmetic', 'CeraVe Skin Renewing Nightly Exfoliating Treatment', 'cerave-renewing-nightly-exfoliating', 'peeling', 'Gece eksfolyan tedavi. Glikolik asit + Laktik asit.', '100.00', 'ml', 'face', 'evening', 'published'),
(648, 3, 6, 'cosmetic', 'The Ordinary Niacinamide 5% Face & Body Emulsion', 'the-ordinary-niacinamide-5-body-emulsion', 'vücut losyonu', 'Niacinamide %5 yüz ve vücut emülsiyonu.', '200.00', 'ml', 'body', 'both', 'published'),
(649, 3, 2, 'cosmetic', 'The Ordinary Glucoside Foaming Cleanser', 'the-ordinary-glucoside-foaming-cleanser', 'temizleyici', 'Glukoside bazlı köpük temizleyici.', '300.00', 'ml', 'face', 'both', 'published'),
(650, 3, 1, 'cosmetic', 'The Ordinary Retinal 0.2% Emulsion', 'the-ordinary-retinal-02-emulsion', 'serum', 'Retinal %0.2 emülsiyon. İleri seviye vitamin A.', '50.00', 'ml', 'face', 'both', 'published'),
(651, 3, 1, 'cosmetic', 'The Ordinary Retinal 0.05% Emulsion', 'the-ordinary-retinal-005-emulsion', 'serum', 'Retinal %0.05 emülsiyon. Başlangıç retinal.', '20.00', 'ml', 'face', 'both', 'published'),
(652, 3, 1, 'cosmetic', 'The Ordinary Multi-Peptide + Copper Peptides 1% Serum', 'the-ordinary-multi-peptide-copper-1', 'serum', 'Çoklu peptit + Bakır peptit %1.', '30.00', 'ml', 'face', 'both', 'published'),
(653, 3, 1, 'cosmetic', 'The Ordinary Ethylated Ascorbic Acid 15% Solution', 'the-ordinary-ethylated-ascorbic-acid-15', 'serum', 'Etil askorbik asit %15. Stabil C vitamini.', '20.00', 'ml', 'face', 'both', 'published'),
(654, 3, 2, 'cosmetic', 'The Ordinary Sulphate 4% Cleanser for Body and Hair', 'the-ordinary-sulphate-4-body-hair-cleanser', 'temizleyici', 'Sülfat %4 vücut ve saç temizleyici.', '500.00', 'ml', 'face', 'both', 'published'),
(655, 3, 1, 'cosmetic', 'The Ordinary Azelaic Acid 10% Suspension Brightening Gel', 'the-ordinary-azelaic-10-brightening-gel', 'serum', 'Azelaik asit %10 jel. Kızarıklık ve ton.', '50.00', 'ml', 'face', 'both', 'published'),
(656, 4, 1, 'cosmetic', 'Bioderma Sebium Hydra Moisturising Cream', 'bioderma-sebium-hydra-moisturising', 'krem', 'Akne tedavisi sonrası nemlendirici. Kurumuş ciltler.', '50.00', 'ml', 'face', 'both', 'published'),
(657, 4, 2, 'cosmetic', 'Bioderma Sebium Foaming Gel', 'bioderma-sebium-foaming-gel', 'temizleyici', 'Akneye eğilimli ciltler temizleme jeli.', '300.00', 'ml', 'face', 'both', 'published'),
(658, 4, 3, 'cosmetic', 'Bioderma Sensibio AR BB Cream SPF30', 'bioderma-sensibio-ar-bb-cream', 'güneş kremi', 'Kızarıklık kamuflajlı BB krem SPF30.', '40.00', 'ml', 'face', 'morning', 'published'),
(659, 4, 3, 'cosmetic', 'Bioderma Photoderm Bronz Dry Oil SPF30', 'bioderma-photoderm-bronz-dry-oil', 'güneş kremi', 'Bronzlaştırıcı kuru yağ SPF30.', '40.00', 'ml', 'face', 'morning', 'published'),
(660, 4, 1, 'cosmetic', 'Bioderma Cicabio Arnica+', 'bioderma-cicabio-arnica-plus', 'balsam', 'Arnika onarıcı krem. Morluk ve çürük.', '50.00', 'ml', 'face_body', 'both', 'published'),
(661, 4, 6, 'cosmetic', 'Bioderma Atoderm Hands & Nails Cream', 'bioderma-atoderm-hands-nails', 'el kremi', 'El ve tırnak bakım kremi.', '30.00', 'ml', 'hands', 'both', 'published'),
(662, 9, 1, 'cosmetic', 'Vichy Slow Age SPF25 Fluid', 'vichy-slow-age-spf25-fluid', 'gündüz kremi', 'Yaşlanma yavaşlatıcı sıvı SPF25.', '30.00', 'ml', 'face', 'morning', 'published'),
(663, 9, 1, 'cosmetic', 'Vichy LiftActiv Collagen Specialist', 'vichy-liftactiv-collagen-specialist', 'krem', 'Kollajen uzmanı krem. Peptit + C vitamini.', '30.00', 'ml', 'face', 'both', 'published'),
(664, 9, 2, 'cosmetic', 'Vichy Purete Thermale Fresh Cleansing Gel', 'vichy-purete-thermale-fresh-gel', 'temizleyici', 'Ferahlatıcı temizleme jeli.', '500.00', 'ml', 'face', 'both', 'published'),
(665, 9, 1, 'cosmetic', 'Vichy Normaderm Probio-BHA Serum', 'vichy-normaderm-probio-bha', 'serum', 'Probiyotik BHA akne serumu.', '50.00', 'ml', 'face', 'both', 'published'),
(666, 9, 1, 'cosmetic', 'Vichy Mineral 89 Fortifying Recovery Mask', 'vichy-mineral-89-recovery-mask', 'maske', 'HA güçlendirici maske.', '75.00', 'ml', 'face', 'evening', 'published'),
(667, 13, 1, 'cosmetic', 'COSRX Ultimate Nourishing Rice Overnight Spa Mask', 'cosrx-rice-overnight-spa-mask', 'maske', 'Pirinç gece maskesi. Aydınlatıcı + nemlendirici.', '100.00', 'ml', 'face', 'evening', 'published'),
(668, 13, 1, 'cosmetic', 'COSRX Aloe Vera Oil-Free Soothing Gel', 'cosrx-aloe-vera-soothing-gel', 'nemlendirici', 'Aloe vera yatıştırıcı jel. Yağsız.', '50.00', 'ml', 'face', 'both', 'published'),
(669, 13, 1, 'cosmetic', 'COSRX Hyaluronic Acid Hydra Power Essence', 'cosrx-ha-hydra-power-essence', 'esans', 'HA güç esansı. 3 tip hyaluronic acid.', '50.00', 'ml', 'face', 'both', 'published'),
(670, 13, 2, 'cosmetic', 'COSRX Low pH Good Morning Gel Cleanser 150ml', 'cosrx-low-ph-cleanser-150ml', 'temizleyici', 'Düşük pH sabah jel temizleyici. Büyük boy.', '200.00', 'ml', 'face', 'both', 'published'),
(671, 13, 1, 'cosmetic', 'COSRX Advanced Snail Radiance Dual Essence', 'cosrx-snail-radiance-dual-essence', 'esans', 'Çift fazlı salyangoz parlaklık esansı.', '100.00', 'ml', 'face', 'both', 'published'),
(672, 29, 1, 'cosmetic', 'Laneige Cica Sleeping Mask', 'laneige-cica-sleeping-mask', 'maske', 'Cica gece maskesi. Centella yatıştırıcı.', '30.00', 'ml', 'face', 'evening', 'published'),
(673, 29, 1, 'cosmetic', 'Laneige Essential Power Skin Toner', 'laneige-essential-power-skin-toner', 'tonik', 'Güç toneri. Bariyer takviyesi.', '150.00', 'ml', 'face', 'both', 'published'),
(674, 29, 1, 'cosmetic', 'Laneige Perfect Renew 3EX Cream', 'laneige-perfect-renew-3ex-cream', 'krem', 'Peptit anti-aging krem.', '75.00', 'ml', 'face', 'both', 'published'),
(675, 29, 1, 'cosmetic', 'Laneige Water Bank Moisture Essence', 'laneige-water-bank-moisture-essence', 'esans', 'Nem esansı. Mavi HA.', '100.00', 'ml', 'face', 'both', 'published'),
(676, 29, 1, 'cosmetic', 'Laneige Glowy Makeup Serum', 'laneige-glowy-makeup-serum', 'serum', 'Parlaklık makyaj serumu. Primer.', '20.00', 'ml', 'face', 'both', 'published'),
(677, 30, 1, 'cosmetic', 'Dr. Jart+ Peptidin Radiance Serum', 'dr-jart-peptidin-radiance-serum', 'serum', 'Peptit parlaklık serumu.', '20.00', 'ml', 'face', 'both', 'published'),
(678, 30, 1, 'cosmetic', 'Dr. Jart+ Cicapair Calming Gel Cream', 'dr-jart-cicapair-calming-gel-cream', 'nemlendirici', 'Cica yatıştırıcı jel krem.', '75.00', 'ml', 'face', 'both', 'published'),
(679, 30, 1, 'cosmetic', 'Dr. Jart+ Ceramidin Oil Balm', 'dr-jart-ceramidin-oil-balm', 'balsam', 'Ceramide yağ balsam. Kuru bölgeler.', '30.00', 'ml', 'face_body', 'both', 'published'),
(680, 30, 1, 'cosmetic', 'Dr. Jart+ Pore Remedy PHA Exfoliating Serum', 'dr-jart-pore-remedy-pha-serum', 'peeling', 'PHA gözenek peeling serumu.', '30.00', 'ml', 'face', 'evening', 'published'),
(681, 30, 1, 'cosmetic', 'Dr. Jart+ Ceramidin Gel Cream', 'dr-jart-ceramidin-gel-cream', 'nemlendirici', 'Ceramide jel krem. Karma ciltler.', '50.00', 'ml', 'face', 'both', 'published'),
(682, 32, 3, 'cosmetic', 'Torriden DIVE-IN Mild Sunscreen SPF50+', 'torriden-dive-in-mild-sunscreen', 'güneş kremi', 'Nazik güneş kremi. HA + Ceramide.', '60.00', 'ml', 'face', 'morning', 'published'),
(683, 32, 1, 'cosmetic', 'Torriden DIVE-IN Skin Booster', 'torriden-dive-in-skin-booster', 'tonik', 'HA cilt güçlendirici tonik.', '150.00', 'ml', 'face', 'both', 'published'),
(684, 32, 1, 'cosmetic', 'Torriden Balanceful Toner Pad', 'torriden-balanceful-toner-pad', 'peeling', 'Dengeleyici tonik pad.', '30.00', 'ml', 'face', 'evening', 'published'),
(685, 32, 1, 'cosmetic', 'Torriden DIVE-IN Multi Pad', 'torriden-dive-in-multi-pad', 'peeling', 'Çok fonksiyonlu HA pad.', '100.00', 'ml', 'face', 'evening', 'published'),
(686, 33, 1, 'cosmetic', 'Round Lab Birch Juice Moisturizing Cream', 'round-lab-birch-juice-moisturizing-cream', 'krem', 'Huş ağacı suyu nemlendirici krem.', '30.00', 'ml', 'face', 'both', 'published'),
(687, 33, 1, 'cosmetic', 'Round Lab Soybean Nourishing Toner', 'round-lab-soybean-nourishing-toner', 'tonik', 'Soya fasulyesi besleyici tonik.', '150.00', 'ml', 'face', 'both', 'published'),
(688, 33, 2, 'cosmetic', 'Round Lab Dokdo Cleansing Oil', 'round-lab-dokdo-cleansing-oil', 'temizleme yağı', 'Dokdo temizleme yağı.', '250.00', 'ml', 'face', 'evening', 'published'),
(689, 33, 1, 'cosmetic', 'Round Lab Mugwort Calming Cream', 'round-lab-mugwort-calming-cream', 'krem', 'Yavşan otu yatıştırıcı krem.', '50.00', 'ml', 'face', 'both', 'published'),
(690, 36, 2, 'cosmetic', 'Anua Heartleaf Quercetinol Pore Deep Cleansing Foam', 'anua-heartleaf-deep-cleansing-foam', 'temizleyici', 'Heartleaf derin gözenek temizleyici.', '300.00', 'ml', 'face', 'both', 'published'),
(691, 36, 1, 'cosmetic', 'Anua Dark Spot Correcting Serum', 'anua-anua-dark-spot-serum', 'serum', 'Leke düzeltici serum. Traneksamik asit.', '50.00', 'ml', 'face', 'both', 'published'),
(692, 36, 1, 'cosmetic', 'Anua Heartleaf 70% Daily Lotion', 'anua-heartleaf-70-daily-lotion', 'nemlendirici', 'Heartleaf günlük losyon.', '30.00', 'ml', 'face', 'both', 'published'),
(693, 36, 1, 'cosmetic', 'Anua BHA 2% Gentle Exfoliating Toner', 'anua-bha-2-gentle-toner', 'tonik', 'BHA %2 nazik peeling toneri.', '300.00', 'ml', 'face', 'both', 'published'),
(694, 35, 3, 'cosmetic', 'Skin1004 Madagascar Centella Air-Fit Suncream SPF50+', 'skin1004-centella-air-fit-suncream', 'güneş kremi', 'Centella hafif güneş kremi.', '50.00', 'ml', 'face', 'morning', 'published'),
(695, 35, 1, 'cosmetic', 'Skin1004 Madagascar Centella Poremizing Clear Ampoule', 'skin1004-centella-poremizing-ampoule', 'ampul', 'Gözenek küçültücü centella ampul.', '30.00', 'ml', 'face', 'evening', 'published'),
(696, 35, 1, 'cosmetic', 'Skin1004 Centella Watergel Cream', 'skin1004-centella-watergel-cream', 'nemlendirici', 'Centella su jel krem.', '100.00', 'ml', 'face', 'both', 'published'),
(697, 35, 2, 'cosmetic', 'Skin1004 Madagascar Centella Cleansing Oil', 'skin1004-centella-cleansing-oil', 'temizleme yağı', 'Centella temizleme yağı.', '200.00', 'ml', 'face', 'evening', 'published'),
(698, 38, 1, 'cosmetic', 'Numbuzin No.3 Super Glowing Essence Toner', 'numbuzin-no3-super-glowing-toner', 'tonik', 'Galactomyces parlaklık toneri.', '250.00', 'ml', 'face', 'both', 'published'),
(699, 38, 4, 'cosmetic', 'Numbuzin No.4 Collagen 73 Eye Cream', 'numbuzin-no4-collagen-eye-cream', 'göz kremi', 'Kollajen göz kremi.', '15.00', 'ml', 'eye', 'both', 'published'),
(700, 38, 1, 'cosmetic', 'Numbuzin No.6 Deep Sleep Mask', 'numbuzin-no6-deep-sleep-mask', 'maske', 'Derin uyku maskesi. Probiyotik.', '75.00', 'ml', 'face', 'evening', 'published')
ON CONFLICT (product_slug) DO NOTHING;