-- ============================================
-- BATCH 4 Part 1: Product Labels
-- ============================================
INSERT INTO product_labels (product_id, usage_instructions, warning_text, claim_texts_json, pao_info, origin_info, manufacturer_info) VALUES
(101,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(102,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(103,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Niacinamide içerir","Hyaluronic Acid","Güneş koruması","Akne bakım"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(104,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Akne bakım","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(105,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Anti-aging bakım","Yoğun nemlendirme"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(106,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(107,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(108,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(109,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(110,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(111,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(112,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(113,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Niacinamide içerir","Hyaluronic Acid","Güneş koruması","Anti-aging bakım"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(114,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(115,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(116,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(117,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(118,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(119,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(120,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(121,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(122,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'La Roche-Posay, Fransa'),

(123,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(124,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(125,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(126,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Hyaluronic Acid","Bariyer desteği","Yoğun nemlendirme"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(127,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(128,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Niacinamide içerir","Bariyer desteği","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(129,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(130,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Niacinamide içerir","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(131,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Hyaluronic Acid","Güneş koruması","Bariyer desteği","Yoğun nemlendirme"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(132,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Niacinamide içerir","Hyaluronic Acid","Bariyer desteği"]',
 '6M', 'ABD', 'CeraVe, ABD'),

(133,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'CeraVe, ABD'),

(134,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","C Vitamini","Leke karşıtı"]',
 '6M', 'ABD', 'CeraVe, ABD'),

(135,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Bariyer desteği","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'CeraVe, ABD'),

(136,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(137,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(138,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Niacinamide içerir","Akne bakım","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(139,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Akne bakım","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(140,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(141,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(142,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(143,
 'El yıkama sonrası veya ihtiyaç duyulduğunda uygulayın.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Bariyer desteği","Yoğun nemlendirme"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(144,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(145,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(146,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(147,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Kanada', 'The Ordinary, Kanada'),

(148,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(149,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(150,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(151,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(152,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(153,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(154,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(155,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(156,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(157,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(158,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(159,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(160,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(161,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Peptit kompleksi","Anti-aging bakım"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(162,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Peptit kompleksi","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(163,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(164,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Leke karşıtı","Yoğun nemlendirme"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(165,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(166,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Bariyer desteği","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(167,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Kanada', 'The Ordinary, Kanada'),

(168,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Peptit kompleksi","Anti-aging bakım"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(169,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(170,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Kanada', 'The Ordinary, Kanada'),

(171,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(172,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Bioderma, Fransa'),

(173,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(174,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(175,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Bioderma, Fransa'),

(176,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(177,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(178,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(179,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Bioderma, Fransa'),

(180,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(181,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["C Vitamini","Güneş koruması","Leke karşıtı"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(182,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'Bioderma, Fransa'),

(183,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(184,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(185,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(186,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Vichy, Fransa'),

(187,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Vichy, Fransa'),

(188,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(189,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Hyaluronic Acid","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(190,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'Vichy, Fransa'),

(191,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(192,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(193,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Niacinamide içerir","Güneş koruması","Anti-aging bakım"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(194,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Niacinamide içerir","Güneş koruması","Akne bakım"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(195,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(196,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(197,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(198,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(199,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(200,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(201,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Almanya', 'Eucerin, Almanya'),

(202,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(203,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(204,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(205,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(206,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(207,
 'El yıkama sonrası veya ihtiyaç duyulduğunda uygulayın.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(208,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(209,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(210,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","C Vitamini","Dermatolojik test edilmiş"]',
 '6M', 'Almanya', 'Eucerin, Almanya'),

(211,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(212,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(213,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(214,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(215,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Eucerin, Almanya'),

(216,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(217,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'COSRX, Güney Kore'),

(218,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Peptit kompleksi","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'COSRX, Güney Kore'),

(219,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Centella / Cica","Akne bakım","Leke karşıtı"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(220,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(221,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'COSRX, Güney Kore'),

(222,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(223,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'COSRX, Güney Kore'),

(224,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'COSRX, Güney Kore'),

(225,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Retinoid içerir","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(226,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'COSRX, Güney Kore'),

(227,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Centella / Cica","Akne bakım"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(228,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Hyaluronic Acid","Akne bakım","Leke karşıtı"]',
 '6M', 'Güney Kore', 'COSRX, Güney Kore'),

(229,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(230,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(231,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(232,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(233,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(234,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'COSRX, Güney Kore'),

(235,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","C Vitamini","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(236,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(237,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(238,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(239,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Laneige, Güney Kore'),

(240,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Bariyer desteği","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(241,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(242,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Laneige, Güney Kore'),

(243,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Peptit kompleksi","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(244,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(245,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Laneige, Güney Kore'),

(246,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(247,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(248,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(249,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Bariyer desteği","Peptit kompleksi","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(250,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(251,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(252,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Bariyer desteği","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(253,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(254,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(255,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(256,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(257,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(258,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(259,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(260,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(261,
 'El yıkama sonrası veya ihtiyaç duyulduğunda uygulayın.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(262,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(263,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(264,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(265,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(266,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Torriden, Güney Kore'),

(267,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Torriden, Güney Kore'),

(268,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Bariyer desteği","Yoğun nemlendirme"]',
 '12M', 'Güney Kore', 'Torriden, Güney Kore'),

(269,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Torriden, Güney Kore'),

(270,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Torriden, Güney Kore'),

(271,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Peptit kompleksi","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Torriden, Güney Kore'),

(272,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Centella / Cica","Akne bakım","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Torriden, Güney Kore'),

(273,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Torriden, Güney Kore'),

(274,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(275,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(276,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(277,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(278,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(279,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Round Lab, Güney Kore'),

(280,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(281,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Axis-Y, Güney Kore'),

(282,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Axis-Y, Güney Kore'),

(283,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Axis-Y, Güney Kore'),

(284,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Axis-Y, Güney Kore'),

(285,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Axis-Y, Güney Kore'),

(286,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Axis-Y, Güney Kore'),

(287,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Axis-Y, Güney Kore'),

(288,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Skin1004, Güney Kore'),

(289,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Niacinamide içerir","Centella / Cica","Leke karşıtı"]',
 '6M', 'Güney Kore', 'Skin1004, Güney Kore'),

(290,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Skin1004, Güney Kore'),

(291,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Hyaluronic Acid","Güneş koruması","Centella / Cica"]',
 '12M', 'Güney Kore', 'Skin1004, Güney Kore'),

(292,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Skin1004, Güney Kore'),

(293,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Skin1004, Güney Kore'),

(294,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Anua, Güney Kore'),

(295,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Anua, Güney Kore'),

(296,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Anua, Güney Kore'),

(297,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Anua, Güney Kore'),

(298,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Anua, Güney Kore'),

(299,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Anua, Güney Kore'),

(300,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Anua, Güney Kore'),

(301,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(302,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(303,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(304,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(305,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(306,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Niacinamide içerir","C Vitamini","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(307,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(308,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(309,
 'Yüze 20-30 cm mesafeden püskürtün. Makyaj üzerine de kullanılabilir.',
 'Gözlere püskürtmeyin.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(310,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(311,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(312,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Hyaluronic Acid","Bariyer desteği","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(313,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'By Wishtrend, Güney Kore'),

(314,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'By Wishtrend, Güney Kore'),

(315,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'By Wishtrend, Güney Kore'),

(316,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'By Wishtrend, Güney Kore'),

(317,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'By Wishtrend, Güney Kore'),

(318,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'By Wishtrend, Güney Kore'),

(319,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Benton, Güney Kore'),

(320,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Benton, Güney Kore'),

(321,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Benton, Güney Kore'),

(322,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Benton, Güney Kore'),

(323,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Benton, Güney Kore'),

(324,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Benton, Güney Kore'),

(325,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Neogen, Güney Kore'),

(326,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Neogen, Güney Kore'),

(327,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Neogen, Güney Kore'),

(328,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Akne bakım","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Neogen, Güney Kore'),

(329,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Neogen, Güney Kore'),

(330,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Holika Holika, Güney Kore'),

(331,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Holika Holika, Güney Kore'),

(332,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Holika Holika, Güney Kore'),

(333,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Holika Holika, Güney Kore'),

(334,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Senka, Japonya'),

(335,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Senka, Japonya'),

(336,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Senka, Japonya'),

(337,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Senka, Japonya'),

(338,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Japonya', 'Melano CC, Japonya'),

(339,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Japonya', 'Melano CC, Japonya'),

(340,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["C Vitamini","Leke karşıtı","Yoğun nemlendirme"]',
 '12M', 'Japonya', 'Melano CC, Japonya'),

(341,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'Japonya', 'Melano CC, Japonya'),

(342,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Biore, Japonya'),

(343,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Biore, Japonya'),

(344,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Biore, Japonya'),

(345,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Biore, Japonya'),

(346,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Biore, Japonya'),

(347,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(348,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Kiehl''s, ABD'),

(349,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Kiehl''s, ABD'),

(350,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(351,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(352,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Peptit kompleksi","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Kiehl''s, ABD'),

(353,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Bariyer desteği","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Kiehl''s, ABD'),

(354,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Kiehl''s, ABD'),

(355,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(356,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Kiehl''s, ABD'),

(357,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(358,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(359,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(360,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(361,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Clinique, ABD'),

(362,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Peptit kompleksi","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Clinique, ABD'),

(363,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Clinique, ABD'),

(364,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(365,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Clinique, ABD'),

(366,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Clinique, ABD'),

(367,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Japonya', 'Shiseido, Japonya'),

(368,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(369,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(370,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(371,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(372,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(373,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(374,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(375,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Dermalogica, ABD'),

(376,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Dermalogica, ABD'),

(377,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Dermalogica, ABD'),

(378,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Hyaluronic Acid","Güneş koruması","Peptit kompleksi","Anti-aging bakım"]',
 '12M', 'ABD', 'Dermalogica, ABD'),

(379,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Dermalogica, ABD'),

(380,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Dermalogica, ABD'),

(381,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Akne bakım","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Dermalogica, ABD'),

(382,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Dermalogica, ABD'),

(383,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Murad, ABD'),

(384,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Murad, ABD'),

(385,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Murad, ABD'),

(386,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Murad, ABD'),

(387,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Murad, ABD'),

(388,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Murad, ABD'),

(389,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(390,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(391,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(392,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(393,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(394,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(395,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Simple, İngiltere'),

(396,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Simple, İngiltere'),

(397,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Simple, İngiltere'),

(398,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Simple, İngiltere'),

(399,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Simple, İngiltere'),

(400,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Sebamed, Almanya');