-- ============================================
-- BATCH 4 Part 3: Product Labels
-- ============================================
INSERT INTO product_labels (product_id, usage_instructions, warning_text, claim_texts_json, pao_info, origin_info, manufacturer_info) VALUES
(701,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(702,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(703,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Kiehl''s, ABD'),

(704,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(705,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Anti-aging bakım","Yoğun nemlendirme"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(706,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(707,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(708,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(709,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Clinique, ABD'),

(710,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Peptit kompleksi","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Clinique, ABD'),

(711,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(712,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(713,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Japonya', 'Shiseido, Japonya'),

(714,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(715,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Shiseido, Japonya'),

(716,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Dermalogica, ABD'),

(717,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Dermalogica, ABD'),

(718,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Peptit kompleksi","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Dermalogica, ABD'),

(719,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Dermalogica, ABD'),

(720,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Niacinamide içerir","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(721,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(722,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(723,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Aveeno, ABD'),

(724,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Simple, İngiltere'),

(725,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Simple, İngiltere'),

(726,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'İngiltere', 'Simple, İngiltere'),

(727,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Simple, İngiltere'),

(728,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Sebamed, Almanya'),

(729,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Sebamed, Almanya'),

(730,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Sebamed, Almanya'),

(731,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Sebamed, Almanya'),

(732,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(733,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(734,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(735,
 'Yüze 20-30 cm mesafeden püskürtün. Makyaj üzerine de kullanılabilir.',
 'Gözlere püskürtmeyin.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(736,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Filorga, Fransa'),

(737,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Filorga, Fransa'),

(738,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Filorga, Fransa'),

(739,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Filorga, Fransa'),

(740,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Murad, ABD'),

(741,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Murad, ABD'),

(742,
 'Yüze 20-30 cm mesafeden püskürtün. Makyaj üzerine de kullanılabilir.',
 'Gözlere püskürtmeyin.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Murad, ABD'),

(743,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Murad, ABD'),

(744,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Sunday Riley, ABD'),

(745,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Sunday Riley, ABD'),

(746,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Sunday Riley, ABD'),

(747,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Glow Recipe, ABD'),

(748,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Glow Recipe, ABD'),

(749,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Glow Recipe, ABD'),

(750,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Farmacy, ABD'),

(751,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Farmacy, ABD'),

(752,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Farmacy, ABD'),

(753,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'İsviçre', 'Weleda, İsviçre'),

(754,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İsviçre', 'Weleda, İsviçre'),

(755,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İsviçre', 'Weleda, İsviçre'),

(756,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(757,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(758,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(759,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Kiehl''s, ABD'),

(760,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(761,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Clinique, ABD'),

(762,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(763,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Clinique, ABD'),

(764,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(765,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(766,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(767,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Paula''s Choice, ABD'),

(768,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Paula''s Choice, ABD'),

(769,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Neutrogena, ABD'),

(770,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Neutrogena, ABD'),

(771,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(772,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Neutrogena, ABD'),

(773,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(774,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(775,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(776,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(777,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(778,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Centella / Cica","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(779,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["C Vitamini","Güneş koruması","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(780,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(781,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(782,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Garnier, Fransa'),

(783,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(784,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Almanya', 'Nivea, Almanya'),

(785,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(786,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(787,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Almanya', 'Nivea, Almanya'),

(788,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(789,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Innisfree, Güney Kore'),

(790,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Innisfree, Güney Kore'),

(791,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Innisfree, Güney Kore'),

(792,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Innisfree, Güney Kore'),

(793,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Missha, Güney Kore'),

(794,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Missha, Güney Kore'),

(795,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Missha, Güney Kore'),

(796,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Missha, Güney Kore'),

(797,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Klairs, Güney Kore'),

(798,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Klairs, Güney Kore'),

(799,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Klairs, Güney Kore'),

(800,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(801,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Centella / Cica","Leke karşıtı"]',
 '6M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(802,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(803,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(804,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Hada Labo, Japonya'),

(805,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Hada Labo, Japonya'),

(806,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Hada Labo, Japonya'),

(807,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Etude House, Güney Kore'),

(808,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Etude House, Güney Kore'),

(809,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Etude House, Güney Kore'),

(810,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(811,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(812,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Heimish, Güney Kore'),

(813,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Neogen, Güney Kore'),

(814,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Neogen, Güney Kore'),

(815,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Neogen, Güney Kore'),

(816,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Holika Holika, Güney Kore'),

(817,
 'El yıkama sonrası veya ihtiyaç duyulduğunda uygulayın.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Holika Holika, Güney Kore'),

(818,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Holika Holika, Güney Kore'),

(819,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Biore, Japonya'),

(820,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Biore, Japonya'),

(821,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Biore, Japonya'),

(822,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Senka, Japonya'),

(823,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Senka, Japonya'),

(824,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Japonya', 'Senka, Japonya'),

(825,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'Japonya', 'Melano CC, Japonya'),

(826,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["C Vitamini","Leke karşıtı","Yoğun nemlendirme"]',
 '12M', 'Japonya', 'Melano CC, Japonya'),

(827,
 'Yüze 20-30 cm mesafeden püskürtün. Makyaj üzerine de kullanılabilir.',
 'Gözlere püskürtmeyin.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'Japonya', 'Melano CC, Japonya'),

(828,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Noreva, Fransa'),

(829,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Noreva, Fransa'),

(830,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Noreva, Fransa'),

(831,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'ACM, Fransa'),

(832,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'ACM, Fransa'),

(833,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'ACM, Fransa'),

(834,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Lierac, Fransa'),

(835,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Lierac, Fransa'),

(836,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Altruist, İngiltere'),

(837,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Altruist, İngiltere'),

(838,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(839,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(840,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(841,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Peter Thomas Roth, ABD'),

(842,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["C Vitamini","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Peter Thomas Roth, ABD'),

(843,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Peter Thomas Roth, ABD'),

(844,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Drunk Elephant, ABD'),

(845,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Drunk Elephant, ABD'),

(846,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Drunk Elephant, ABD'),

(847,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Drunk Elephant, ABD'),

(848,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Drunk Elephant, ABD'),

(849,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Drunk Elephant, ABD'),

(850,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Isntree, Güney Kore'),

(851,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Isntree, Güney Kore'),

(852,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Isntree, Güney Kore'),

(853,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Isntree, Güney Kore'),

(854,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Purito, Güney Kore'),

(855,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Bariyer desteği","Centella / Cica","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Purito, Güney Kore'),

(856,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Purito, Güney Kore'),

(857,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(858,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(859,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(860,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Uriage, Fransa'),

(861,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Ducray, Fransa'),

(862,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Ducray, Fransa'),

(863,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Ducray, Fransa'),

(864,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'SVR, Fransa'),

(865,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'SVR, Fransa'),

(866,
 'Güneş koruyucu üzerine veya tek başına uygulayın. Tazeleme için ideal.',
 'Göz çevresine dikkat edin. Tek başına tam koruma sağlamaz.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'SVR, Fransa'),

(867,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(868,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(869,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(870,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(871,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Embryolisse, Fransa'),

(872,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Embryolisse, Fransa'),

(873,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Embryolisse, Fransa'),

(874,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Tatcha, ABD'),

(875,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Tatcha, ABD'),

(876,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Fresh, Fransa'),

(877,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Fresh, Fransa'),

(878,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Fresh, Fransa'),

(879,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'SK-II, Japonya'),

(880,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'SK-II, Japonya'),

(881,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Medicube, Güney Kore'),

(882,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Medicube, Güney Kore'),

(883,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Medicube, Güney Kore');