-- ============================================
-- BATCH 4 Part 2: Product Labels
-- ============================================
INSERT INTO product_labels (product_id, usage_instructions, warning_text, claim_texts_json, pao_info, origin_info, manufacturer_info) VALUES
(401,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Sebamed, Almanya'),

(402,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Sebamed, Almanya'),

(403,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Sebamed, Almanya'),

(404,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Almanya', 'Sebamed, Almanya'),

(405,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Caudalie, Fransa'),

(406,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Caudalie, Fransa'),

(407,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(408,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(409,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Caudalie, Fransa'),

(410,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(411,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(412,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Caudalie, Fransa'),

(413,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Embryolisse, Fransa'),

(414,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Embryolisse, Fransa'),

(415,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Embryolisse, Fransa'),

(416,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Embryolisse, Fransa'),

(417,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Filorga, Fransa'),

(418,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Filorga, Fransa'),

(419,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Filorga, Fransa'),

(420,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Filorga, Fransa'),

(421,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Peptit kompleksi","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'Filorga, Fransa'),

(422,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'Filorga, Fransa'),

(423,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(424,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(425,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(426,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(427,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(428,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(429,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Macaristan', 'Geek & Gorgeous, Macaristan'),

(430,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Altruist, İngiltere'),

(431,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Altruist, İngiltere'),

(432,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Altruist, İngiltere'),

(433,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'İngiltere', 'Altruist, İngiltere'),

(434,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Peter Thomas Roth, ABD'),

(435,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Peter Thomas Roth, ABD'),

(436,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Peter Thomas Roth, ABD'),

(437,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Peter Thomas Roth, ABD'),

(438,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Peter Thomas Roth, ABD'),

(439,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Peter Thomas Roth, ABD'),

(440,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(441,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Neutrogena, ABD'),

(442,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Retinoid içerir","Güneş koruması","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(443,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Retinoid içerir","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(444,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(445,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(446,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(447,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Neutrogena, ABD'),

(448,
 'El yıkama sonrası veya ihtiyaç duyulduğunda uygulayın.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(449,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Neutrogena, ABD'),

(450,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Nuxe, Fransa'),

(451,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Nuxe, Fransa'),

(452,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Nuxe, Fransa'),

(453,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Nuxe, Fransa'),

(454,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Hyaluronic Acid","Anti-aging bakım"]',
 '6M', 'Fransa', 'Nuxe, Fransa'),

(455,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Nuxe, Fransa'),

(456,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Nuxe, Fransa'),

(457,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Nuxe, Fransa'),

(458,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(459,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(460,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(461,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'Uriage, Fransa'),

(462,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(463,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Retinoid içerir","C Vitamini","Güneş koruması","Anti-aging bakım"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(464,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(465,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Uriage, Fransa'),

(466,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Ducray, Fransa'),

(467,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Ducray, Fransa'),

(468,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Ducray, Fransa'),

(469,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Ducray, Fransa'),

(470,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Ducray, Fransa'),

(471,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Ducray, Fransa'),

(472,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(473,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(474,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(475,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Niacinamide içerir","Leke karşıtı","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(476,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(477,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(478,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(479,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(480,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(481,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Bariyer desteği","Yoğun nemlendirme"]',
 '12M', 'Güney Kore', 'Some By Mi, Güney Kore'),

(482,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Centella / Cica","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Klairs, Güney Kore'),

(483,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Klairs, Güney Kore'),

(484,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Klairs, Güney Kore'),

(485,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Klairs, Güney Kore'),

(486,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Klairs, Güney Kore'),

(487,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Klairs, Güney Kore'),

(488,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Klairs, Güney Kore'),

(489,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Purito, Güney Kore'),

(490,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Purito, Güney Kore'),

(491,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Purito, Güney Kore'),

(492,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Centella / Cica","Peptit kompleksi","Dermatolojik test edilmiş"]',
 '6M', 'Güney Kore', 'Purito, Güney Kore'),

(493,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Centella / Cica","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Purito, Güney Kore'),

(494,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Purito, Güney Kore'),

(495,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Purito, Güney Kore'),

(496,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(497,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Retinoid içerir","Peptit kompleksi","Anti-aging bakım"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(498,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(499,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Hyaluronic Acid","Retinoid içerir","Bariyer desteği","Yoğun nemlendirme"]',
 '12M', 'ABD', 'Paula''s Choice, ABD'),

(500,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Paula''s Choice, ABD'),

(501,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(502,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Paula''s Choice, ABD'),

(503,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(504,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(505,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Peptit kompleksi","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Paula''s Choice, ABD'),

(506,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Sunday Riley, ABD'),

(507,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'ABD', 'Sunday Riley, ABD'),

(508,
 'Akşam bakım rutininin son adımı olarak 2-3 damla yüze uygulayın.',
 'Hassas ciltlerde patch test yapın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Sunday Riley, ABD'),

(509,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Sunday Riley, ABD'),

(510,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'ABD', 'Sunday Riley, ABD'),

(511,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Glow Recipe, ABD'),

(512,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Glow Recipe, ABD'),

(513,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Glow Recipe, ABD'),

(514,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Glow Recipe, ABD'),

(515,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Glow Recipe, ABD'),

(516,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İsviçre', 'Weleda, İsviçre'),

(517,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İsviçre', 'Weleda, İsviçre'),

(518,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İsviçre', 'Weleda, İsviçre'),

(519,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'İsviçre', 'Weleda, İsviçre'),

(520,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'İsviçre', 'Weleda, İsviçre'),

(521,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Hyaluronic Acid","Centella / Cica","Akne bakım"]',
 '12M', 'Güney Kore', 'Medicube, Güney Kore'),

(522,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Medicube, Güney Kore'),

(523,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Medicube, Güney Kore'),

(524,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Medicube, Güney Kore'),

(525,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Medicube, Güney Kore'),

(526,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Medicube, Güney Kore'),

(527,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(528,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Garnier, Fransa'),

(529,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Garnier, Fransa'),

(530,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(531,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(532,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(533,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(534,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Garnier, Fransa'),

(535,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Almanya', 'Nivea, Almanya'),

(536,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(537,
 'Akşam temizleme ve serum sonrası yüze uygulayın. Gece boyunca çalışır.',
 'Yalnızca harici kullanım. Göz çevresine dikkat edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(538,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(539,
 'Pamuğa bol miktarda uygulayın. Yüz ve göz bölgesini nazikçe silin. Durulama gerektirmez.',
 'Göz hassasiyeti devam ederse kullanmayı bırakın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(540,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(541,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Almanya', 'Nivea, Almanya'),

(542,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Nivea, Almanya'),

(543,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Centella / Cica","Anti-aging bakım"]',
 '6M', 'Güney Kore', 'Innisfree, Güney Kore'),

(544,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Innisfree, Güney Kore'),

(545,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Innisfree, Güney Kore'),

(546,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Innisfree, Güney Kore'),

(547,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Innisfree, Güney Kore'),

(548,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Centella / Cica","Leke karşıtı"]',
 '6M', 'Güney Kore', 'Innisfree, Güney Kore'),

(549,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Avene, Fransa'),

(550,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(551,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(552,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(553,
 'Yüze 20-30 cm mesafeden püskürtün. Makyaj üzerine de kullanılabilir.',
 'Gözlere püskürtmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(554,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(555,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Akne bakım","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(556,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Avene, Fransa'),

(557,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Akne bakım","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'SVR, Fransa'),

(558,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Hyaluronic Acid","Akne bakım","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'SVR, Fransa'),

(559,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'SVR, Fransa'),

(560,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'SVR, Fransa'),

(561,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Niacinamide içerir","Leke karşıtı","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'SVR, Fransa'),

(562,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'SVR, Fransa'),

(563,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Isntree, Güney Kore'),

(564,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Niacinamide içerir","C Vitamini","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Isntree, Güney Kore'),

(565,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Isntree, Güney Kore'),

(566,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Isntree, Güney Kore'),

(567,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Isntree, Güney Kore'),

(568,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Isntree, Güney Kore'),

(569,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Missha, Güney Kore'),

(570,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Missha, Güney Kore'),

(571,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Missha, Güney Kore'),

(572,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Missha, Güney Kore'),

(573,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Missha, Güney Kore'),

(574,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(575,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(576,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(577,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(578,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(579,
 'Güneş koruyucu üzerine veya tek başına uygulayın. Tazeleme için ideal.',
 'Göz çevresine dikkat edin. Tek başına tam koruma sağlamaz.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Beauty of Joseon, Güney Kore'),

(580,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Hada Labo, Japonya'),

(581,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Hada Labo, Japonya'),

(582,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '6M', 'Japonya', 'Hada Labo, Japonya'),

(583,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Hada Labo, Japonya'),

(584,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Hyaluronic Acid","Güneş koruması","Leke karşıtı"]',
 '12M', 'Japonya', 'Hada Labo, Japonya'),

(585,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Etude House, Güney Kore'),

(586,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Etude House, Güney Kore'),

(587,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Etude House, Güney Kore'),

(588,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Etude House, Güney Kore'),

(589,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Etude House, Güney Kore'),

(590,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Etude House, Güney Kore'),

(591,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Noreva, Fransa'),

(592,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Noreva, Fransa'),

(593,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Noreva, Fransa'),

(594,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Noreva, Fransa'),

(595,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'ACM, Fransa'),

(596,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'ACM, Fransa'),

(597,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'ACM, Fransa'),

(598,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'ACM, Fransa'),

(599,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Centella / Cica","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'Lierac, Fransa'),

(600,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Lierac, Fransa'),

(601,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Lierac, Fransa'),

(602,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Lierac, Fransa'),

(603,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Tatcha, ABD'),

(604,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Tatcha, ABD'),

(605,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Tatcha, ABD'),

(606,
 'Yüze 20-30 cm mesafeden püskürtün. Makyaj üzerine de kullanılabilir.',
 'Gözlere püskürtmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Tatcha, ABD'),

(607,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Fresh, Fransa'),

(608,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Fresh, Fransa'),

(609,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Fransa', 'Fresh, Fransa'),

(610,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Anti-aging bakım","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Fresh, Fransa'),

(611,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Farmacy, ABD'),

(612,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Farmacy, ABD'),

(613,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Farmacy, ABD'),

(614,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Farmacy, ABD'),

(615,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'SK-II, Japonya'),

(616,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Japonya', 'SK-II, Japonya'),

(617,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Peptit kompleksi","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'SK-II, Japonya'),

(618,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'SK-II, Japonya'),

(619,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Dr. Hauschka, Almanya'),

(620,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Dr. Hauschka, Almanya'),

(621,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Dr. Hauschka, Almanya'),

(622,
 'Dudaklara ihtiyaç duyulduğunda uygulayın. Gece yoğun bakım olarak kalın tabaka.',
 'Yalnızca harici kullanım. Yutmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Almanya', 'Dr. Hauschka, Almanya'),

(623,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Muji, Japonya'),

(624,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Muji, Japonya'),

(625,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Muji, Japonya'),

(626,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Muji, Japonya'),

(627,
 'Kuru bölgelere günde 1-2 kez uygulayın. Masaj yaparak yedirin.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Dove, İngiltere'),

(628,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Dove, İngiltere'),

(629,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'İngiltere', 'Dove, İngiltere'),

(630,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'İngiltere', 'Dove, İngiltere'),

(631,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Canmake, Japonya'),

(632,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Japonya', 'Canmake, Japonya'),

(633,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Estée Lauder, ABD'),

(634,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Estée Lauder, ABD'),

(635,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Anti-aging bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Estée Lauder, ABD'),

(636,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'Estée Lauder, ABD'),

(637,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'Estée Lauder, ABD'),

(638,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Akne bakım","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(639,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(640,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(641,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(642,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'La Roche-Posay, Fransa'),

(643,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(644,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(645,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(646,
 'El yıkama sonrası veya ihtiyaç duyulduğunda uygulayın.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'ABD', 'CeraVe, ABD'),

(647,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'ABD', 'CeraVe, ABD'),

(648,
 'Banyo sonrası nemli cilde uygulayın. Günde 1-2 kez.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Niacinamide içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Kanada', 'The Ordinary, Kanada'),

(649,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Kanada', 'The Ordinary, Kanada'),

(650,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(651,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Retinoid içerir","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(652,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Peptit kompleksi","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(653,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["C Vitamini","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(654,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Kanada', 'The Ordinary, Kanada'),

(655,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Kanada', 'The Ordinary, Kanada'),

(656,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Akne bakım","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(657,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Akne bakım","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(658,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(659,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(660,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(661,
 'El yıkama sonrası veya ihtiyaç duyulduğunda uygulayın.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Bioderma, Fransa'),

(662,
 'Sabah temizleme sonrası yüze uygulayın. Güneş koruyucu öncesi veya yerine.',
 'Göz çevresine uygulamayın. SPF içerse de şapka kullanın.',
 '["Güneş koruması","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(663,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["C Vitamini","Peptit kompleksi","Dermatolojik test edilmiş"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(664,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(665,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Hyaluronic Acid","Akne bakım","Dermatolojik test edilmiş"]',
 '6M', 'Fransa', 'Vichy, Fransa'),

(666,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Fransa', 'Vichy, Fransa'),

(667,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Leke karşıtı","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(668,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(669,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(670,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(671,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'COSRX, Güney Kore'),

(672,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(673,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(674,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Peptit kompleksi","Anti-aging bakım","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(675,
 'Tonik sonrası birkaç damla avuç içine alın, yüze hafifçe bastırarak uygulayın.',
 'Hassas ciltlerde patch test yapın.',
 '["Hyaluronic Acid","Yoğun nemlendirme","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Laneige, Güney Kore'),

(676,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Laneige, Güney Kore'),

(677,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Peptit kompleksi","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(678,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(679,
 'Temiz cilde ince tabaka halinde uygulayın. Tahriş olmuş bölgelerde kullanılabilir.',
 'Derin ve enfekte yaralarda kullanmayın.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(680,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(681,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Bariyer desteği","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Dr. Jart+, Güney Kore'),

(682,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Hyaluronic Acid","Güneş koruması","Bariyer desteği"]',
 '12M', 'Güney Kore', 'Torriden, Güney Kore'),

(683,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Torriden, Güney Kore'),

(684,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Torriden, Güney Kore'),

(685,
 'Akşam temizleme sonrası uygulayın. Haftada 2-3 kez başlayın. Güneş koruyucu kullanın.',
 'Güneş hassasiyeti artırır — güneş koruyucu kullanın. Retinol ile dikkatli kombine edin.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Torriden, Güney Kore'),

(686,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Yoğun nemlendirme","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(687,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(688,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(689,
 'Temizleme ve serum sonrası yüze uygulayın. İnce tabaka yeterlidir.',
 'Yalnızca harici kullanım.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Round Lab, Güney Kore'),

(690,
 'Islak yüze masaj yaparak uygulayın. Köpürtün ve ılık su ile durulayın. Sabah ve akşam.',
 'Göz temasından kaçının. Tahriş olursa kullanımı durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Anua, Güney Kore'),

(691,
 'Temizleme ve tonik sonrası birkaç damla yüze uygulayın. Nemlendirici öncesi.',
 'Hassas ciltlerde az miktarla başlayın. Göz çevresinden kaçının.',
 '["Leke karşıtı","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Anua, Güney Kore'),

(692,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Anua, Güney Kore'),

(693,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Hyaluronic Acid","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Anua, Güney Kore'),

(694,
 'Güneşe çıkmadan 15 dakika önce bol miktarda uygulayın. 2 saatte bir yenileyin.',
 'Güneş koruyucu tek başına tam koruma sağlamaz. Gölge ve koruyucu giysi kullanın.',
 '["Güneş koruması","Centella / Cica","Dermatolojik test edilmiş"]',
 '12M', 'Güney Kore', 'Skin1004, Güney Kore'),

(695,
 'Tonik sonrası 2-3 damla yüze uygulayın. Kür olarak veya sürekli kullanılabilir.',
 'Hassas ciltlerde patch test önerilir. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Skin1004, Güney Kore'),

(696,
 'Serum sonrası yüze ve boyuna uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Tahriş olursa durdurun.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Skin1004, Güney Kore'),

(697,
 'Kuru yüze 2-3 pompa uygulayın. Dairesel masaj yapın. Islak elle emülsifiye edin, durulayın.',
 'Göz temasından kaçının. Yalnızca harici kullanım.',
 '["Centella / Cica","Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Skin1004, Güney Kore'),

(698,
 'Temizleme sonrası pamukla veya avuç içiyle yüze uygulayın. Sabah ve akşam.',
 'Yalnızca harici kullanım. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(699,
 'Sabah ve akşam göz çevresine yüzük parmağıyla hafifçe vurarak uygulayın.',
 'Göze doğrudan temas ettirmeyin.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '6M', 'Güney Kore', 'Numbuzin, Güney Kore'),

(700,
 'Temiz cilde uygulayın. 10-20 dakika bekletin. Ilık su ile durulayın.',
 'Tahriş hissederseniz hemen durulayın. Açık yaralara uygulamayın.',
 '["Dermatolojik test edilmiş","Tüm cilt tipleri için"]',
 '12M', 'Güney Kore', 'Numbuzin, Güney Kore');