import { Client } from 'pg';
import { config } from 'dotenv';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
config({ path: resolve(__dirname, '../../../../../.env') });
const c = new Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
await c.connect();
const r = await c.query(`SELECT content_type, status, COUNT(*) FROM content_articles GROUP BY content_type, status ORDER BY content_type`);
console.log('content_articles content_type breakdown:');
for (const row of r.rows) console.log(`  ${row.content_type} (${row.status}): ${row.count}`);
await c.end();
