import { Client } from 'pg';
import { config } from 'dotenv';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
config({ path: resolve(__dirname, '../../../../../.env') });
const c = new Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
await c.connect();
const r = await c.query(`SELECT i.ingredient_slug, i.inci_name, COUNT(*) AS uses FROM ingredients i JOIN product_ingredients pi ON pi.ingredient_id=i.ingredient_id WHERE (i.detailed_description IS NULL OR length(i.detailed_description) < 100) GROUP BY i.ingredient_id ORDER BY uses DESC LIMIT 40`);
for (const x of r.rows) console.log(`${String(x.uses).padStart(4)} | ${x.ingredient_slug.padEnd(45)} | ${x.inci_name}`);
await c.end();
